### ISSUE TITLE
Android ChatSDK, take Picture BUG

### ISSUE THREAD

**Issue by matheuaviczki** [chat-sdk/chat-sdk-android#101]
There is a bug in the android version, where when you take and send a photo and click, it does not open, is as can be seen in the following image ...
![screenshot_2017-06-05-11-31-23](https://cloud.githubusercontent.com/assets/17489055/26788205/d70cdbc6-49e2-11e7-96ca-0ed3424a1b80.png)

But if you clear the cache or reinstall the application, the image opens normally, why is this happening?

**Comment by bensmiley** [comment]
Fixed in v4.0.
