### ISSUE TITLE
C2D_Message duplicated in generated Manifest.java

### ISSUE THREAD

**Issue by charlesinwald** [chat-sdk/chat-sdk-android#103]
I downloaded the sdk and tried the sample app and I get:

Error:(13, 32) error: variable C2D_MESSAGE is already defined in class permission"

I took a look at the AndroidManifest.xml , and there appears to be several permissions that use this but I'm not sure what do here.

**Comment by jpsjanuario** [comment]
I am getting this error too

**Comment by Richard010** [comment]
I am getting this error too, please fix!

**Comment by RyanElliott94** [comment]
Have you tried just copying and pasting the manifest code from the sample project? That's what i did and i just added to it if i had my own activities and changed the package name to my own

**Comment by cinwald** [comment]
I fixed it by commenting out the google maps/Backendless stuff, I dont need that at the moment but people with the same problem that do need it may need a more complex issue

**Comment by bensmiley** [comment]
Fixed in v4.0.
