### ISSUE TITLE
Adding to existing project, install it got 2 same icons show on device - Android APP

### ISSUE THREAD

**Issue by Richard010** [chat-sdk/chat-sdk-android#108]
I am developing an Android messaging app, got an issue, was adding to an existing project, then install it got 2 same icons show on the device. is that something duplication need to remove. I have followed all the steps.

If I kill the app on memory, click one of the icons got a force close,
crash log:
Attempt to invoke virtual method 'boolean com.braunster.chatsdk.network.AbstractNetworkAdapter.facebookEnabled()' on a null object reference at com.braunster.chatsdk.activities.ChatSDKLoginActivity.onCreate(ChatSDKLoginActivity.java:44)

but click on the second icon works. is that something duplication needs to be removed?

The app can add a room, can chart, can search username, can get notifications. Pretty cool!

**Comment by matheuaviczki** [comment]
You need configure on the Android manifest

**Comment by marmik57** [comment]
Remove this code from your manifest if your trying to add SDK in existing project. Because it has two launcher activities.
<intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>

**Comment by jvlichai** [comment]
Hi matheuaviczki and marmik57, 

OK, problem solved. You're so helpful. Thanks a lot.
