### ISSUE TITLE
Contacts not shown when adding users to group chat

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#11]
Create a group chat and then click the + button. Although we can search for users, our contacts are not shown under the contacts section title.

**Comment by kykrueger** [comment]
Hey Ben,

Did you fix this already? I don't have any problems on this view.

![screenshot_1489255095](https://cloud.githubusercontent.com/assets/7158199/23825593/ead9574a-068c-11e7-9d43-80f486fae09a.png)

-- Kyle

**Comment by bensmiley** [comment]
If it's working now we can close the issue.
