### ISSUE TITLE
New message not get notified if stop running the app.

### ISSUE THREAD

**Issue by jvlichai** [chat-sdk/chat-sdk-android#111]
New message not get notified if stop running the app. To run the app, and then press on back button, it sill can get new message notification. But if I do kill the app by pressing Android Phone' square button and then it do not get new coming message any more. Why? Like What's App, no mater I kill the app, I still get new message from my friends.

**Comment by prajitkk** [comment]
can you please post the solution if found, i also have same problem

**Comment by bensmiley** [comment]
Fixed in v4.0.
