### ISSUE TITLE
Replace  com.astuetz:pagerslidingtabstrip:1.0.1 with android slidingtabs

### ISSUE THREAD

**Issue by kykrueger** [chat-sdk/chat-sdk-android#113]
The project included for the sliding tabs has since been adopted into the main android sdk. Migrating would be nice.

**Comment by rohitbhoite** [comment]
@bensmiley What is the expected date for this migration?

**Comment by bensmiley** [comment]
This will be available in the new version of the Android project. We expect it to be released before the 8th of September.
