### ISSUE TITLE
ChatSdkMainActivity hangs when number of threads are too high

### ISSUE THREAD

**Issue by mp-studycopter** [chat-sdk/chat-sdk-android#117]
We are using ChatSDK in our android application to add "Tutor-Student" chat feature. Work flow is as follows,

- When ever user logs into our app, a rest API is called which creates the firebase data which is required for following use case,

1. This newly logged in user should have a friend added by default which is tutor
2. This user should receive a message from tutor "Hi, This is your tutor. How may I help you ?"
    

- When ever user enters ChatSDKMainActivity, he/she should be able to see Tutor thread with default message.

Our implementation is working fine.

Issue :-

We are facing an issue with this implementation. When ever we login from tutor's account we see that there are more than hundreds of threads created. But Tutor account is not able to load those threads efficiently. We have seen following issues,

    

1. when number of chats exceed a certain number N, chats stops refreshing the new messages
2. If a new message is arrived in tutor's account neither push notification is shown nor new message in seen in respected thread.
3. Sometimes Mobile screen becomes black on ChatSDKMainActivivy
4. Contacts list does not show any contact on Tutor Account
5. Application crashes with following exception,
    ANR in com.study.copter.ibps
                                PID: 8180
                                Reason: Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=com.study.copter.ibps cmp=com.study.copter.ibps/com.braunster.androidchatsdk.firebaseplugin.firebase.backendless.ChatSDKReceiver (has extras) }
                                Load: 8.26 / 8.02 / 7.65
                                CPU usage from 0ms to 5199ms later

Can you please provide some help what could possibly have been the reason for all these issues ?

**Comment by bensmiley** [comment]
Fixed in v4.0.
