### ISSUE TITLE
Simplify integration via Gradle

### ISSUE THREAD

**Issue by bagage** [chat-sdk/chat-sdk-android#118]
Instead of having to add the Chat SDK as project Modules (and commit them in our own repository), would you consider instead replace:

```gradle
compile project(':firebase_plugin')
```

With:

```gradle
compile('com.braunster.chatsdk:1.0') {
    exclude mode: "facebook"
}
```

It would be so much easier to setup and update to latest version if needed :).

**Comment by bensmiley** [comment]
This will be available shortly.

**Comment by bensmiley** [comment]
This has been added in the [latest release](https://github.com/chat-sdk/chat-sdk-android#gradle)
