### ISSUE TITLE
Optionnal dependencies: Facebook, Google Maps, …

### ISSUE THREAD

**Issue by bagage** [chat-sdk/chat-sdk-android#119]
Related to #118, it would be cool if we could remove some dependencies easily. 

Developers may have their own authentication logic, thus don't need Google+, Facebook and login/signin facilities.
Similarly Google Maps feature might be unneeded / unwished.

Having multiple gradle modules (#118) would definitely help going toward this direction. 

I tried removing Facebook module for instance but there are a bunch of dependencies with the chat `sdk` module.

**Comment by bensmiley** [comment]
This is fixed in v4.0. Social login has been moved to a separate module.
