### ISSUE TITLE
Text formatting and misalignment in group / users screen

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#12]
In the group / users screen the text that says the admin's name is smaller and the admin text is misaligned and also smaller. 

![screenshot_20170208-180746](https://cloud.githubusercontent.com/assets/5514010/22750917/92e371aa-ee00-11e6-988d-b70c7b4c6144.png)

**Comment by kykrueger** [comment]
You said the admin text is misaligned,

What does it look like in the iOS view? 

For now I fixed the size of the font for the Admin's user name, and centered the admin tag. However, I think the admin tag should be directly under the userName. See the second attached image to see what I mean.

If you pick one I will merge it from the hotfixes branch.
![threaddetails-admincentered-layout-2017-03-11-164454](https://cloud.githubusercontent.com/assets/7158199/23824640/432d3136-067a-11e7-9445-8776614974e9.png)


![threaddetails-adminbelow-layout-2017-03-11-164454](https://cloud.githubusercontent.com/assets/7158199/23824728/1c669c84-067c-11e7-9151-e1e81bd5bd87.png)

**Comment by bensmiley** [comment]
Hi @kykrueger 

I think the second one is better but the "Admin name" text should be moved up and there should be more space between the name and the "Admin" text. If this is difficult, then the first one is fine - it would be even better if the admin text was moved down a little - so it looked like it was sitting on the same line as the name text. Otherwise it could just be set to the same size as that text. 

This isn't a critical issue so just do what's easiest.

**Comment by kykrueger** [comment]
The layout has been updated in the latest hotfix. There was no pull request made, but the changes have been merged and pushed. I am closing this issue.
