### ISSUE TITLE
Use Support library for better integration

### ISSUE THREAD

**Issue by bagage** [chat-sdk/chat-sdk-android#121]
From what I've gathered here and here, even when targetting 15+ sdk version, one should stick with support library instead of direct API (fragment, activity, etc.). 

Few reasons from this [SO post](https://stackoverflow.com/questions/41593636/fragment-vs-support-fragment-when-targeting-api-21-android-5-0-and-above), but not limited to, are:

> * Future features may be added and backported, and then you'd need to rewrite to use them
> * Consistency. The support library works to make sure support fragments always work the same. Whereas the native fragments may have subtle differences between versions.
> * The support library can contain bug fixes to the platform and can be updated much more frequently.

Furthermore it would ease a lot integration within apps which target older API versions. WDYT?

**Comment by kykrueger** [comment]
Hi @bagage 

We have been refactoring the project for a new major update. When it is released, you will find that we have updated a few facets of the UI. One of the improvements is exactly this, but not just for fragments. Moving forward, the SDK is using the support library as often as possible.

-- Kyle

**Comment by bagage** [comment]
Hi @kykrueger,
Cool, this is great news! Can't wait to test this new version then! Any ETA for it?
Feel free to close the issue anytime.

**Comment by bensmiley** [comment]
Fixed in v4.0.
