### ISSUE TITLE
notifications stop coming after adding to existing project

### ISSUE THREAD

**Issue by prajitkk** [chat-sdk/chat-sdk-android#122]
when i use chat-sdk app alone notifications are working but after adding to the existing project it stopped to show notifications, i have done all the steps as indicated by you, should i have to include anything new to get notifications

**Comment by simonsmiley64** [comment]
Hi @prajitkk,

We have found that sometimes Backendless starts working once the app is added to iTunes Connect. This doesn't mean it needs to be released but there is something in the upload to iTunes that seems to enable the set up to work consistently. 

If you have completed all the steps in the instructions I would check the following:

1. Go to the Backendless dashboard and confirm the push notifications are being sent. You can click on the specific device and see them when your device sends them.
2. If you can't confirm 1 let me know and I will show you where to look. If 1 isn't working you need to ensure you have set up push notifications correctly.
3. If you can complete 1 and 2 correctly then I would upload your app to iTunes connect. You can then download a version using TestFlight and once again test the push notifications. If your pushes were previously being sent then they should be received correctly now. 
4. If 3 doesn't work then you should get back to us on this thread and also post a bug report on the Backendless support page. 

Let me know if this helps,

Simon

**Comment by bensmiley** [comment]
Hi @prajitkk,

We have found that sometimes Backendless starts working once the app is added to iTunes Connect. This doesn't mean it needs to be released but there is something in the upload to iTunes that seems to enable the set up to work consistently.

If you have completed all the steps in the instructions I would check the following:

1. Go to the Backendless dashboard and confirm the push notifications are being sent. You can click on the specific device and see them when your device sends them.
2. If you can't confirm 1 let me know and I will show you where to look. If 1 isn't working you need to ensure you have set up push notifications correctly.
3. If you can complete 1 and 2 correctly then I would upload your app to iTunes connect. You can then download a version using TestFlight and once again test the push notifications. If your pushes were previously being sent then they should be received correctly now.
4. If 3 doesn't work then you should get back to us on this thread and also post a bug report on the Backendless support page.

Let me know if this helps,

Ben

**Comment by prajitkk** [comment]
hello ben, 
thanks for your reply, i don't need push notifications, i meant that the new messages to the chat are not getting notified, upon entering the app i get notifications of the new messages and after closing in background i am not getting alert on new messages

**Comment by prajitkk** [comment]
i am getting an error
  java.lang.RuntimeException: Could not register device on Backendless server: Version is disabled or provided wrong application info (application id or secret key)
 at com.backendless.push.BackendlessBroadcastReceiver.onError(BackendlessBroadcastReceiver.java:148 at com.backendless.push.BackendlessBroadcastReceiver$1.handleFault(BackendlessBroadcastReceiver.java:310) at com.backendless.Messaging$2.handleFault(Messaging.java:247)at com.backendless.async.message.AsyncMessage$FaultHandler.handle(AsyncMessage.java:83) at com.backendless.async.message.AsyncMessage.handleCallback(AsyncMessage.java:41) at com.backendless.core.AndroidCarrier$1.handleMessage(AndroidCarrier.java:37)at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:207)at android.app.ActivityThread.main(ActivityThread.java:5740) at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

**Comment by Allansk2** [comment]
Are you working on android or ios? If you are working on android, I got same error, here is the step I fixed it
1. In build.gradle (Module:sdk),
replace the backendless 
`compile 'com.backendless:backendless:4.0.+'`
2. in class BBackendlessHandler, check backendless api document for details. Replace the appKey and secreKey.

```
    public void setContext(Context ctx) {
        context = ctx;
    }

    public void initWithAppKey(String appKey, String secretKey, String appUrl)
    {
        Backendless.setUrl(appUrl);
        Backendless.initApp(context, appKey, secretKey);
    }

    @Override
    public boolean subscribeToPushChannel(final String channel) {
        if (!BNetworkManager.sharedManager().getNetworkAdapter().backendlessEnabled())
            return false;

        try {

            Backendless.Messaging.registerDevice(context.getString(R.string.google_project_number), channel, new AsyncCallback<Void>() {
                @Override
                public void handleResponse(Void response) {
                    if(DEBUG) Timber.v("Device has been subscribed to channel " + channel);

                    String deviceToken = settings.getString("regid", ""); // get your device token 

                    List<String> channels = new ArrayList<String>();
                    channels.add(channel);
                    Backendless.Messaging.registerDeviceOnServer(deviceToken, channels, 4000000000000L, new AsyncCallback<String>() {
                        @Override
                        public void handleResponse(String response) {
                        }

                        @Override
                        public void handleFault(BackendlessFault fault) {
                        }
                    });

                }

                @Override
                public void handleFault(BackendlessFault fault) {
                    if(DEBUG) Timber.v("Device subscription failed. " + fault.getMessage());
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }

        return true;
    }

    @Override
    public boolean unsubscribeToPushChannel(String channel) {
        if (!BNetworkManager.sharedManager().getNetworkAdapter().backendlessEnabled())
            return false;

        // TODO: unsubscribe from push channel backendless
        // http://support.backendless.com/topic/push-notification-unregister-from-a-specific-channel
        DeviceRegistration devReg = null;

        try {
            devReg = Backendless.Messaging.getDeviceRegistration();
        } catch (Exception e) {
            e.printStackTrace();
        }

        if(devReg != null) {
            Backendless.Messaging.unregisterDevice();
        }

        return true;
    }

    @Override
    public void pushToChannels(Collection<String> channels, JSONObject data) {

        // Configure the header
        PublishOptions publishOptions = new PublishOptions();
        try {
        publishOptions.putHeader("android-ticker-text", data.getString(BDefines.Keys.CONTENT));
        publishOptions.putHeader("android-content-title", "Message from " + data.getString(BDefines.Keys.MESSAGE_SENDER_NAME));
        publishOptions.putHeader("android-content-text", data.getString(BDefines.Keys.MESSAGE_PAYLOAD));
        publishOptions.setPublisherId(data.getString(BDefines.Keys.MESSAGE_SENDER_ENTITY_ID));
        } catch (JSONException e) {
            e.printStackTrace();
        }

        // Only push to android devices
        DeliveryOptions deliveryOptions = new DeliveryOptions();
        deliveryOptions.setPublishPolicy(PublishPolicyEnum.BOTH);
        deliveryOptions.setPushBroadcast(PushBroadcastMask.ALL);

        // Publish a push notification to each channel
        for(final String channel : channels) {
            try {
                data.put(BDefines.Keys.Channel, channel);
            } catch (JSONException e) {
                e.printStackTrace();
            }

            Backendless.Messaging.publish(channel, data.toString(), publishOptions, deliveryOptions, new AsyncCallback<MessageStatus>() {
                @Override
                public void handleResponse(MessageStatus response) {
                }

                @Override
                public void handleFault(BackendlessFault fault) {

                }
            });

        }
    }
```
