### ISSUE TITLE
Can this sdk support to use my own server to host  my data instead of using firebase?

### ISSUE THREAD

**Issue by LovelyLich** [chat-sdk/chat-sdk-android#123]
I want to connect my app to my own server , in order to save data on my own host, instead of firebase.
Because in my country, it is a big problem to connect to firebase service. 
Thanks for your replay in advanced.

**Comment by bensmiley** [comment]
Unfortunately, this isn't possible with the Firebase version of the app. If you want to do that, you should use the [XMPP version of the project](https://chatsdk.co/downloads/xmpp-chat-sdk-for-android/). With this version you can run the messenger using the [open source eJabberd server](https://www.ejabberd.im/). This project is scheduled to be released in several weeks.
