### ISSUE TITLE
Messages not sent are kept in history with "sending…" state indefinitely

### ISSUE THREAD

**Issue by bagage** [chat-sdk/chat-sdk-android#126]
Using the demo APK:

1. Start chatting with someone
2. Activate airplane mode (no network anymore)
3. Send message. Message state is `delivered=yes, state=sending`
4. Kill application
5. Disable airplane mode (network available)
6. Start application and restart chatting with the previous contact

## Expected
Either the pending message is resubmitted, or it is marked as `state=failed`.

## Actual
The message is kept in the list with `delivered=yes, state=sending` but ChatSDK is not trying to send it anymore.

**Comment by simonsmiley64** [comment]
Hi @bagage,

Currently the SDK does not have an offline mode. This is something on our long list of modifications to add but hasn't been an issue thus far. We find people rarely attempt to send a message while in offline mode so although it can be easily reproduced in test conditions it hasn't been an issue for any of our current apps available using the ChatSDK.

If you want to add this feature we can give you some guidance on how to make the changes, if you then submit a pull request we will check the code and then maintain it going forward. 

Simon

**Comment by bagage** [comment]
Hey @simonsmiley64, I managed to handle it on my own, can close it for now, thanks.
