### ISSUE TITLE
ChatSDK in not getting opened in Android Studio

### ISSUE THREAD

**Issue by SandeepADexoit** [chat-sdk/chat-sdk-android#129]
<img width="960" alt="chatsdkerror" src="https://user-images.githubusercontent.com/31063996/29398338-a5e38598-8341-11e7-96db-1d2b794a177d.png">

I have downloaded the zip file from github and imported in my android studio.
It asked INSTALL 25.0.1 gradle file and sync. So I went to project structure and changed the 
Compile SDK Version to API 25 and 
Build Tools Version to 25.0.1 and then build the project.
It is showing this error. Can i get an assistance regarding this ?

**Comment by LeoSBl3** [comment]
Hello, I had went through the same issues and couldn't fix it,
You need to follow the instructions of how to Configuring Chat SDK , down in the page.
https://github.com/chat-sdk/chat-sdk-android#configuring-chat-sdk
then you can run the ChatSDK.
Everything worked for me except the configuring Backendless Push Notifictions and Google Maps, appreciate after you try if you let me know whether Backendless setup and google maps worked for you or not.
good luck

**Comment by SandeepADexoit** [comment]
But I am not able to build my gradle file due to this issue -> "Failed to find Build Tools revision 25.0.1".
Though I have updated my Android build tools to 26.
What should I do ?

**Comment by LeoSBl3** [comment]
Follow the below note then , start all over again (unzip then open the ChatSDK), and run the project , it worked for me.
Note: You should make sure that the correct SDK versions and build tools are installed in Android Studio. To do this open the Preferences panel and navigate to Appearance & Behavour -> System Settings -> Android SDK or click on the SDK Manager icon in the tool bar. Android SDK versions 4.4 and onwards should be installed. Android SDK Build-Tools version 21.1.0 should be installed.

**Comment by SandeepADexoit** [comment]
I updated Android SDK Build Tools and now my gradle has successfully synced.
Now i will be checking firebase integration.

**Comment by SandeepADexoit** [comment]
I also removed the Android() from Project Gradle file and everything worked fine.
