### ISSUE TITLE
User details in group are not updated

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#13]
If you create a group chat and add several users and then one of those users leaves, the group still displays as having all the original users. 

This affects the thread name and thread details screens.

**Comment by kykrueger** [comment]
@bensmiley 
How did you handle the removal of users on iOS? The current android SDK doesn't have a listener for users leaving the chat. We could either read the firebase path for the users and see if the users have a deleted flag upon opening details, or create a listener and add a new field for deleted users in chats within the database.

**Comment by bensmiley** [comment]
In iOS, we do this in the `usersOn` method.

```
    [threadDetailsRef observeEventType:FIRDataEventTypeChildRemoved withBlock:^(FIRDataSnapshot * snapshot) {
        if (![snapshot.value isEqual: [NSNull null]]) {
            // Update the thread
            CCUserWrapper * user = [CCUserWrapper userWithSnapshot:snapshot];
            [_model removeUser:user.model];
            [[NSNotificationCenter defaultCenter] postNotificationName:bNotificationThreadUsersUpdated object:Nil];
        }
    }];
```

We just check Firebase to see if the user is removed and if it is, we remove it from the thread ORM object.
