### ISSUE TITLE
App hangs after clicking on Register Button

### ISSUE THREAD

**Issue by SandeepADexoit** [chat-sdk/chat-sdk-android#130]
I have run the App on device. Screen appears with Login and Register buttons.
I entered the credentials and clicked on REGISTER Button. 
It's not proceeding and displaying a progressbar with text as "Registering..."
What might be the issue ?

**Comment by SandeepADexoit** [comment]
Now it gave me a Toast saying "PERMISSION DENIED".

Do I need to give some extra permissions for that ?

**Comment by simonsmiley64** [comment]
Hi @SandeepADexoit,

Can you confirm that you have configured Firebase to your project correctly? You can find a tutorial for this in the [wiki](https://github.com/chat-sdk/chat-sdk-android/wiki/Chat-SDK-Android:-Firebase-Configuration).

The fact that you are getting a permission denied error suggests you are not being able to connect with Firebase properly. Once you add the Chat SDK to your own project you will need to configure your own accounts.

Let me know how this goes,

Simon
