### ISSUE TITLE
Crash on Android O due to SuperToasts

### ISSUE THREAD

**Issue by bagage** [chat-sdk/chat-sdk-android#132]
Supertoast [is not compatible with Android O](https://github.com/JohnPersano/SuperToasts/issues/108), so if you target it and chatSDK starts a supertoast, app will crash. 

Since Supertoast library has been abandoned for a year now, you should consider dropping it/replace it with something more maintained.

**Comment by bensmiley** [comment]
I'll aim to do this for the upcoming release.

**Comment by bensmiley** [comment]
This has been replaced with the default Android [Toast](https://developer.android.com/guide/topics/ui/notifiers/toasts.html) class.

**Comment by jaspreeterlang** [comment]
You can use it's child class **SuperToastActivity** instead of **SuperToast**. It'll help to let it run on all OS Versions.
