### ISSUE TITLE
User online or offline

### ISSUE THREAD

**Issue by DaveGram** [chat-sdk/chat-sdk-android#133]
Hi,
is it possible to see if the person in the chat is online? 

Thank you.

**Comment by simonsmiley64** [comment]
There should be an online characteristic on the user object. Go to the user object class and you should be able to find the correct one, they just call that to check if the user is online. The Chat SDK is set up to update user objects in the app when other users change their state.

If you go to the Firebase database you should be able to see that the user is updated as online or offline when they login or out. 

Let me know if this helps,

Simon
