### ISSUE TITLE
Modified/deleted messages are still present

### ISSUE THREAD

**Issue by bagage** [chat-sdk/chat-sdk-android#134]
If you modify a message (edit content or remove it or...) directly within firebase console or from a third party app, ChatSDK doesn't update the message locally. It seems that once it gets into the DAO it is never refreshed.
I think that ChatSDK `InMessagesListener` class should subscribe to Firebase `onChildChanged` and `onChildRemoved` to keep sync with Firebase. But these methods are not invoked when modifications are made while application is killed (as expected), so on startup you won't be notified of these changes which is unfortunate...

For now, my workaround is to wipe ChatSDK database out totally with:

```java
DaoMaster.dropAllTables(DaoCore.db, true); // db field was made public
DaoMaster.createAllTables(DaoCore.db, true); 
```

**Comment by bensmiley** [comment]
Currently this is just how the app is designed. Message updates aren't supported. I'll add it to the backlog as a possible enhancement.

**Comment by jay2342** [comment]
bensmiley can you help me in issue

**Comment by jay2342** [comment]
help me

**Comment by KAPLANDROID** [comment]
Are there any move for this issue? @bensmiley

**Comment by KAPLANDROID** [comment]
Are there any move for this?

**Comment by timhuang1018** [comment]
need to update messages as well,  any idea how to implement this ?
