### ISSUE TITLE
ChatSDKLogin activity Error

### ISSUE THREAD

**Issue by singireddysravankumar** [chat-sdk/chat-sdk-android#137]
Hi,    i am new to android
 I got error in                                                                Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.braunster.chatsdk.network.AbstractNetworkAdapter.facebookEnabled()' on a null object reference
                                                                  at com.braunster.chatsdk.activities.ChatSDKLoginActivity.onCreate(ChatSDKLoginActivity.java:44)
please can any one help me
Thanks in advance

**Comment by sfuantos** [comment]
Make sure that your are creating the adapter before setting it

**Comment by jay2342** [comment]
help me for my issues
