### ISSUE TITLE
Daily Active Users Estimation

### ISSUE THREAD

**Issue by ohenepee** [chat-sdk/chat-sdk-android#139]
_Generally speaking, the free plan will support around 10,000 daily active users._

Please how did you arrive at this figure? B'cos I read from the Firebase pricing that the free plan *Spark Plan* supports only 100 simultaneous connections.

**Comment by bensmiley** [comment]
It's explained in this [blog post](https://chatsdk.co/mobile-messaging-service-price-comparison/). Firebase base their pricing on bandwidth and concurrent connections so the best we can do is estimate how many DAUs would be supported by a particular plan. It would depend a lot of the specifics of the app.

**Comment by ohenepee** [comment]
Except that I can't read that blog post nor register on the site. This is the message I get and there's no way to register. Absolutely None!

_This content is restricted to site members. If you are an existing user, please log in. New users may register below._

**Comment by bensmiley** [comment]
This issue has now been resolved. You can access the page without a user account.
