### ISSUE TITLE
Re-download dependecies and sync project

### ISSUE THREAD

**Issue by nowantednameisavailabel** [chat-sdk/chat-sdk-android#14]
whenever I load project in I got an error re-download dependencies and sync project again. Kindly tell me how to resolve this issue. I tried downloading gradle zip files but don't know where and how to place that files in project folder.

**Comment by jhonnysins69** [comment]
@kykrueger  please help.

**Comment by bensmiley** [comment]
Can you send a screenshot of the error you're getting?

**Comment by jhonnysins69** [comment]
![image](https://cloud.githubusercontent.com/assets/23380362/22855826/09357b38-f0a8-11e6-80a5-9db803f8b7bd.png)

**Comment by kykrueger** [comment]
I am surprised to see that it is saying it failed to open a zip file. Are you opening your project from a compressed folder? If so, can you try decompressing it and re-opening before compiling?

**Comment by jhonnysins69** [comment]
I am opening it after decompressing the folder, but still getting this error.

**Comment by jhonnysins69** [comment]
@kykrueger the cause of error may be because of gradle-2.14.1-all.zip in distributionurl. Please help.
![image](https://cloud.githubusercontent.com/assets/23380362/22861114/c10e8e5e-f132-11e6-868c-947a3644c849.png)

**Comment by kykrueger** [comment]
Hello again,

Have you tried invalidating your cache and / or re-downloading your dependencies as suggested by the gradle error. I'd like to provide more help, but this issue is not reproducible on my end.

-- Kyle

**Comment by nowantednameisavailabel** [comment]
Thanks for helping, problem is resolved.
