### ISSUE TITLE
Message not sent 

### ISSUE THREAD

**Issue by Allansk2** [chat-sdk/chat-sdk-android#140]
Sometimes the message didn't saved in firebase. sendMessageWithText return Done, but in firebase, the message doesn't exist. Some of them were saved to firebase a minute later, but some of them didn't. I thought it was because something wrong and sign out, but I did try login again, but still didn't send out.

**Comment by bensmiley** [comment]
Have you made any modifications to the SDK. For example, adding your own Firebase details? Also, is there any kind of error message in the console? Finally, which country are you based in? How good is your internet connection?

**Comment by Allansk2** [comment]
Hi, I do add my own firebase info. I didn't get any error message. After some debugging, I find out that it cause that user is not online. I did make some modifications to adapt to my custom login, what I did is when user login to my server, I also auto login to firebase. When user open a chat room, I open up ChatSDKChatActivity directly. 
`Intent intent =new Intent(context, ChatSDKChatActivity.class);`
From firebase, I can see sometimes once open up ChatSDKChatActivity, user "online" become true (it's working) and other time stay false (that when message will not send out). I see a lot of online checking in other activity, such as enableCheckOnlineOnResumed. I wonder it's because in the ChatSDKMainActivity, it push user online, but mine go to the ChatSDKChatActivity directly. 


```
Map<String, Object> data = AbstractNetworkAdapter.getMap(
                        new String[]{BDefines.Prefs.LoginTypeKey, BDefines.Prefs.LoginEmailKey, BDefines.Prefs.LoginPasswordKey},
                        BDefines.BAccountType.Password, email, FIRE_BASE_PASSWORD);

                BNetworkManager.sharedManager().getNetworkAdapter()
                        .authenticateWithMap(data).done(new DoneCallback<Object>() {
                    @Override
                    public void onDone(Object o) {
                        BUser currentUser = BNetworkManager.sharedManager().getNetworkAdapter().currentUserModel();
                        Log.e("user firebase id", currentUser.getEntityID());
 
                        // 2. update user name
                        currentUser.setMetaName(userBean.getName());
                        BNetworkManager.sharedManager().getNetworkAdapter().pushUser();
 
                    }
                }).fail(new FailCallback<BError>() {
                    @Override
                    public void onFail(BError bError) {
                        Log.e("error", "fire base login error " + bError.message);
                    }
                });
```

**Comment by Allansk2** [comment]
It seem like it's not connected to firebase in ChatSDKBaseActivity, goOnline or userGoOnline isn't working, I have to logout and relogin.

public void goOnline() {
        DatabaseReference.goOnline();

        setUserOnline();
    }

 @Override
    protected void onStart() {
        super.onStart();
        getNetworkAdapter().setUserOnline();
    }

    @Override
    protected void onStop() {
        super.onStop();
        getNetworkAdapter().setUserOffline();
    }

**Comment by jay2342** [comment]
help me some for my issues

**Comment by Allansk2** [comment]
I find that the problem is in login, neither success or error shown in logcat, not sure why.

                ```
Map<String, Object> data = AbstractNetworkAdapter.getMap(
                        new String[]{BDefines.Prefs.LoginTypeKey, BDefines.Prefs.LoginEmailKey, BDefines.Prefs.LoginPasswordKey},
                        BDefines.BAccountType.Password, email, FIRE_BASE_PASSWORD);

                BNetworkManager.sharedManager().getNetworkAdapter()
                        .authenticateWithMap(data).done(new DoneCallback<Object>() {
                    @Override
                    public void onDone(Object o) {
                        BUser currentUser = BNetworkManager.sharedManager().getNetworkAdapter().currentUserModel();
                        Log.e("error", "firebase login success user firebase id " + currentUser.getEntityID());
                    }
                }).fail(new FailCallback<BError>() {
                    @Override
                    public void onFail(BError bError) {
                        Log.e("error", "firebase login error " + bError.message);
                    }
                });
```

**Comment by bensmiley** [comment]
This needs to be re-tested in v4.0 and reopened if necessary.
