### ISSUE TITLE
Deleting threads

### ISSUE THREAD

**Issue by kairosart** [chat-sdk/chat-sdk-android#141]
Hi,
I'm develoving some admin funcions for chatSDK but I can't delete a group thread. I've been watching how to delete a 1 to 1 thread, using 
`showAlertDialog("", getResources().getString(R.string.alert_delete_thread), getResources().getString(R.string.delete),
                            getResources().getString(R.string.cancel), null, new DeleteThread(adapter.getItem(position).getEntityId()));`

but if I try to use on deleting a group thread, it doesn't delete it. 

Can you give any idea about how to delete a group thread?

Thanks.

**Comment by bensmiley** [comment]
The group thread is stored in two places:

![screen shot 2017-09-12 at 2 22 58 pm](https://user-images.githubusercontent.com/5514010/30325686-ef7e2a76-97c5-11e7-8e58-bdbe811b3f61.png)

The `public-threads` path and the `threads` path. To delete it you would need to remove it from both places in Firebase.

**Comment by bensmiley** [comment]
If you mean a private group thread, when you delete it you are actually just leaving the thread. We didn't add the ability to delete a group thread because it's a bit more complex. You would need to remove all the data from the `threads/[thread id]` path in Firebase and then loop over the user IDs in the `threads/[thread id]/users` path and remove the thread from each user.

**Comment by kairosart** [comment]
Doesn't the next code make all the work?
`public class DeleteThread implements Callable{

        private String threadID;
        public DeleteThread(String threadID){
            this.threadID = threadID;
        }

        @Override
        public Object call() throws Exception {
            getNetworkAdapter().deleteThreadWithEntityID(threadID)
                    .done(new DoneCallback<Void>() {
                        @Override
                        public void onDone(Void aVoid) {
                            showToast( getString(R.string.delete_thread_success_toast) );
                            refreshOnBackground();
                        }
                    })
                    .fail(new FailCallback<BError>() {
                        @Override
                        public void onFail(BError error) {
                            showAlertToast(  getString(R.string.delete_thread_fail_toast)  );
                        }
                    });

            return null;
        }
    }`

**Comment by kairosart** [comment]
So, you can create as many public threads as you want and nobody can't delete them?
