### ISSUE TITLE
contacts are not displaying in it 

### ISSUE THREAD

**Issue by jay2342** [chat-sdk/chat-sdk-android#142]
contacts are not displaying in it please help me with this problem

**Comment by jay2342** [comment]
any one reply

**Comment by bensmiley** [comment]
This needs to be retested in v4.0 and reopened if necessary.

**Comment by jay2342** [comment]
why

**Comment by bensmiley** [comment]
If you want to re-open the issue, could you fill out the [issue template](https://github.com/chat-sdk/chat-sdk-android/blob/master/Issue%20Template.md)?
