### ISSUE TITLE
Two android icons

### ISSUE THREAD

**Issue by thanos04** [chat-sdk/chat-sdk-android#144]
Hello,

I am adding chatSDK to an existing application. After following the basic instructions and running the app, I get two app icons instead of  1. Upon opening either one, I briefly see the login screen before the app crashes and closes. I am new to android development. Maybe the problem is in my android manifest file?

This is what I have:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.flakapp.test">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>-->

        <activity
            android:name="com.braunster.chatsdk.activities.ChatSDKLoginActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:theme="@style/ChatSDKTheme"
            android:windowSoftInputMode="stateHidden|adjustPan"
            >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>

</manifest>

Thanks!

**Comment by jay2342** [comment]
send me screenshot

**Comment by prajitkk** [comment]
<intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>

delete this lines in manifest (second one)

**Comment by jay2342** [comment]
parjitkk help me i have a diff problem

**Comment by Allansk2** [comment]
<activity
        android:name="com.braunster.chatsdk.activities.ChatSDKLoginActivity"
        android:label="@string/app_name"
        android:screenOrientation="portrait"
        android:theme="@style/ChatSDKTheme"
        android:windowSoftInputMode="stateHidden|adjustPan"
        >
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
    </activity>


should be 

<activity
        android:name="com.braunster.chatsdk.activities.ChatSDKLoginActivity"
        android:screenOrientation="portrait"
        >
  </activity>

**Comment by bensmiley** [comment]
This should be retested in v4.0. and reopened if necessary.
