### ISSUE TITLE
Backendless notification not working 

### ISSUE THREAD

**Issue by shishram** [chat-sdk/chat-sdk-android#145]
I have added Backendless to the my app but it return below error 

Fatal Exception: java.lang.RuntimeExceptionCould not register device on Backendless server: Version is disabled or provided wrong application info (application id or secret key) Raw Text
--
  | com.backendless.push.BackendlessBroadcastReceiver.onError (BackendlessBroadcastReceiver.java:148)
  | com.backendless.push.BackendlessBroadcastReceiver$1.handleFault (BackendlessBroadcastReceiver.java:310)
  | com.backendless.Messaging$2.handleFault (Messaging.java:247)
  | com.backendless.async.message.AsyncMessage$FaultHandler.handle (AsyncMessage.java:83)
  | com.backendless.async.message.AsyncMessage.handleCallback (AsyncMessage.java:41)
  | com.backendless.core.AndroidCarrier$1.handleMessage (AndroidCarrier.java:37)
  | android.os.Handler.dispatchMessage (Handler.java:98)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:629)

Can you help me out here, I am confused also for secret key for Version3.

**Comment by shishram** [comment]
found this link [http://support.backendless.com/topic/can-i-create-new-app-in-backendless-3-x-version](url)

its no more available for free, need to purchase license for this.

**Comment by bensmiley** [comment]
We've removed support for Backendless because we found their customer service to be poor. You can support Firebase Cloud Messaging which will give you an unlimited number of pushes for free. You can follow the guide [here](https://github.com/chat-sdk/chat-sdk-android/wiki/Supporting-Firebase-push-notifications-with-v3-of-the-project).
