### ISSUE TITLE
Add support for Firestore - vote here!

### ISSUE THREAD

**Issue by Aexyn** [chat-sdk/chat-sdk-android#148]
Greetings
 I was looking into your sdk and found it great.. A great tool to integrate Firebase I must say. But as FireStore is there now, are there any plans to upgrade this.. . I mean is this actively maintained. Will it introduce breaking changes.? Cheers :)

**Comment by bensmiley** [comment]
We will look at the advantages and disadvantages of FireStore and upgrade the project if necessary. The main benefit of FireStore seems to be that you can support over 100k concurrent users more easily. That would equate to well over 20 million monthly users so this will only be a benefit to very large apps. Over the coming months we'll assess if the benefits outweigh the drawbacks and decide whether to support the new service.

**Comment by Shajeel-Afzal** [comment]
@bensmiley! Thanks for creating this awesome library! Do you have any plan to add support for Firestore?

**Comment by bensmiley** [comment]
We are considering supporting Firestore but it would depend on the level of interest because it's a fairly big job. If you're interested +1 this comment.

**Comment by mrmisat** [comment]
Awesomeee

**Comment by chanhbc** [comment]
yes

**Comment by VivekRajNei** [comment]
Yes

**Comment by monowar1993** [comment]
yes

**Comment by btrautmann** [comment]
Yes!

**Comment by HygorLBM** [comment]
Yes, I want to add this into a project where I'm using Firestore.

**Comment by Torry12** [comment]
Yes please....

**Comment by silvazaki** [comment]
yes please

**Comment by pinkeshdarji** [comment]
WE WANT FIRESTORE.

**Comment by creativephoenix** [comment]
+1

**Comment by srinathvidapu** [comment]
+1

**Comment by spungkyb** [comment]
+1

**Comment by waqasashiq31** [comment]
Yes

**Comment by asepmaulanaismail** [comment]
Yes!

**Comment by jiraya85** [comment]
Yes! Absolutely FireStore!

**Comment by emmanuellmota** [comment]
+1

**Comment by sagarsurani** [comment]
+1

**Comment by philippesimard** [comment]
Yes ! 👍

**Comment by Alifyz** [comment]
+1
That would be awesome!

**Comment by akour** [comment]
yes

**Comment by Davechpn** [comment]
yes

**Comment by kevendra** [comment]
+1

**Comment by bensmiley** [comment]
Hi Everyone, 

At the moment we're trying to transition away from consulting work to focus on the Chat SDK core library full time. We would love to add support for Firestore but it's a big job and at the moment we are spending all our time either working on client projects to pay the bills or maintaining the core Chat SDK library. I've just made a Patreon page because if we get enough support, I could start working on the core library full time. If you are in the position to support the project to any degree it would really help us get the Firestore project moving. Here's our [Patreon page](https://www.patreon.com/chatsdk).

Thanks,

Ben

**Comment by Sid1249** [comment]
Yes, Please

**Comment by piseysen** [comment]
yes, please, i hope you will use firestore

**Comment by max6363** [comment]
Yes.

**Comment by Nikhil-z** [comment]
Yes

**Comment by fabwoofer** [comment]
+1

**Comment by maxmya** [comment]
+1

**Comment by SunnyDayDev** [comment]
+1

**Comment by soushu** [comment]
+1

**Comment by Oziomajnr** [comment]
yes

**Comment by dankeos** [comment]
yes, i hope this project grow! so many blessings

**Comment by aymenhs** [comment]
Thank you for this great library, if our application starts to work,I'm sure we'll be very good supporters 👍

**Comment by Inzimam-Tariq** [comment]
add Firestore support

**Comment by Hussamalsh** [comment]
+1

**Comment by Kufo2018** [comment]
Yes Please!

**Comment by abdallavsh** [comment]
yes

**Comment by hardikamal** [comment]
+1

**Comment by KonsoltCorp** [comment]
+1

**Comment by YAMexchange** [comment]
Now Firestore is out of BETA, YES YES YES PLEASE - And if you could add in the WebApp chat as per ChatCat.io as well so we can create a seemless chat / messaging experience across our web and mobile apps we would pay as well!

**Comment by hoang17** [comment]
+1

**Comment by Mrudulamrudu25** [comment]
+1

**Comment by kutakmir** [comment]
Yes!

**Comment by fernandodeveloper** [comment]
yes

**Comment by bensonokiora** [comment]
yes

**Comment by AnastasiosF** [comment]
+1

**Comment by LadyKrystalline** [comment]
**Yes!**

**Comment by wg-mblazin** [comment]
yes

**Comment by tadasz** [comment]
let's do it!

**Comment by Creative-Ash** [comment]
yes

**Comment by ganico** [comment]
yes

**Comment by marceariel** [comment]
Yes

**Comment by Amigo927** [comment]
yes

**Comment by mshenawy22** [comment]
yes vote

**Comment by Antol** [comment]
+1

**Comment by loicleprogrammeur** [comment]
+1

**Comment by bensmiley** [comment]
We finally have an update. We have released the beta version of our Firestore messaging library. You can check it out [here](https://github.com/chat-sdk/firestream-android).

**Comment by hoangvuanhdevelopervn** [comment]
+1

**Comment by bensmiley** [comment]
Check out:
https://github.com/chat-sdk/firestream-android
