### ISSUE TITLE
Supporting Firebase push notifications with error , 

### ISSUE THREAD

**Issue by helpdevs** [chat-sdk/chat-sdk-android#149]
io.reactivex.android.schedulers.AndroidSchedulers;
import com.braunster.chatsdk.Utils.FileUploadResult;  not exist  

does not explain how to implement well, since you have to import a dependency to io.reactivex
@bensmiley  @itzikBraun

**Comment by rohitbhoite** [comment]
@helpdevs Library is not currently maintained it seems.

**Comment by bensmiley** [comment]
Try adding this to your build.gradle file:

```
    compile 'io.reactivex.rxjava2:rxjava:2.0.0'
    compile 'io.reactivex.rxjava2:rxandroid:2.0.0'
```

**Comment by helpdevs** [comment]
it does not work

**Comment by bensmiley** [comment]
Could you explain what doesn't work? Is there a crash? Could you post a stack trace?
