### ISSUE TITLE
APP APP COMPLETED WITH CHAT SDK

### ISSUE THREAD

**Issue by helpdevs** [chat-sdk/chat-sdk-android#150]
I AM FROM CCOLOMBIA

HELLO FRIENDS I JUST FINISHED MY APPLICATION FOR ANDROID USING THE CHAT SDK, I HAVE IMPROVED IT IN SOME ASPECTS, THERE ARE SOME ERRORCITES. I THANK YOU FOR THE AID

https://play.google.com/store/apps/details?id=com.helpdevs.nexttv#

![screenshot_1507249787](https://user-images.githubusercontent.com/20031330/31468843-3af9f8b8-aea5-11e7-85cf-6480a91bd4f3.png)
![screenshot_1507249791](https://user-images.githubusercontent.com/20031330/31468844-3b11d776-aea5-11e7-9b0d-aa826a517dd9.png)
![screenshot_1507249794](https://user-images.githubusercontent.com/20031330/31468845-3b2a6408-aea5-11e7-88fd-077b849aa72a.png)
![screenshot_1507249853](https://user-images.githubusercontent.com/20031330/31468846-3b435616-aea5-11e7-9763-49db9929b189.png)
![screenshot_1507249861](https://user-images.githubusercontent.com/20031330/31468847-3b5b1ae4-aea5-11e7-9f19-85c60183cc01.png)
![screenshot_1507249905](https://user-images.githubusercontent.com/20031330/31468848-3b7c8b8e-aea5-11e7-8753-33eecc95f98d.png)
![screenshot_1507250272](https://user-images.githubusercontent.com/20031330/31468850-3ba6bdb4-aea5-11e7-957d-e4d2f4fd233b.png)
![screenshot_1507250281](https://user-images.githubusercontent.com/20031330/31468851-3be04d0e-aea5-11e7-9a83-3e389f5c61a9.png)
![screenshot_1507250285](https://user-images.githubusercontent.com/20031330/31468853-3c1b0494-aea5-11e7-80eb-34f53b28f9d7.png)
![screenshot_1507250538](https://user-images.githubusercontent.com/20031330/31468854-3c337bc8-aea5-11e7-8a07-3dfb25b52646.png)
![screenshot_1507250548](https://user-images.githubusercontent.com/20031330/31468855-3ca752a0-aea5-11e7-8e0e-80174b76dfde.png)
![screenshot_1507479208](https://user-images.githubusercontent.com/20031330/31468856-3cecafb2-aea5-11e7-9720-da9074221f2b.png)
![screenshot_1507479470](https://user-images.githubusercontent.com/20031330/31468857-3d2ecf6e-aea5-11e7-862e-5c35a1069d0f.png)
![screenshot_1507479497](https://user-images.githubusercontent.com/20031330/31468858-3d5c4bba-aea5-11e7-9baa-096863fbb821.png)
![screenshot_1507479995](https://user-images.githubusercontent.com/20031330/31468859-3d7356a2-aea5-11e7-95ef-eeeac1183a6a.png)
![screenshot_1507479999](https://user-images.githubusercontent.com/20031330/31468860-3db7d480-aea5-11e7-9f41-b686586e1211.png)
![screenshot_1507480027](https://user-images.githubusercontent.com/20031330/31468861-3dfb564c-aea5-11e7-9644-0244d6e82f47.png)
![screenshot_1507480133](https://user-images.githubusercontent.com/20031330/31468862-3e457ee8-aea5-11e7-99da-6296b1a3c065.png)
![screenshot_1507480464](https://user-images.githubusercontent.com/20031330/31468863-3e91463e-aea5-11e7-92cd-249b34380939.png)
![screenshot_1507480472](https://user-images.githubusercontent.com/20031330/31468865-3ed5ea3c-aea5-11e7-8493-54133440be4c.png)
![screenshot_1507481077](https://user-images.githubusercontent.com/20031330/31468867-3f53bd22-aea5-11e7-91f4-187a2f1a77e0.png)
![screenshot_1507481081](https://user-images.githubusercontent.com/20031330/31468868-3f98546e-aea5-11e7-9bb8-9abef7828634.png)
![screenshot_1507481086](https://user-images.githubusercontent.com/20031330/31468869-3fdc9af2-aea5-11e7-83ce-84a1bfb3c360.png)
![screenshot_1507482976](https://user-images.githubusercontent.com/20031330/31468870-40092630-aea5-11e7-8227-e6d0aa6adf95.png)
![screenshot_1507483008](https://user-images.githubusercontent.com/20031330/31468871-402e75d4-aea5-11e7-92af-912e912dfaa5.png)

@bensmiley @itzikBraun @kykrueger @simonsmiley64 @Erkberg

**Comment by bensmiley** [comment]
It looks great! I've added a link to the Github main page. I'll also send a tweet out tomorrow. I hope it gets you some traffic.

**Comment by helpdevs** [comment]
thank you very much, the app is for now with content in Spanish, but I will include content in English to make it more global
