### ISSUE TITLE
Getting below error while setting up the sdk in existing project

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#152]
I am trying to setup the latest sdk in the existing android app.I am following the sdk documentation.But getting below error in android studio while building the app.
![image](https://user-images.githubusercontent.com/32955380/31815681-036747e0-b5ab-11e7-8ba6-0af18eef987a.png)
How this issue can be resolved?
(Note-I have downloaded latest sdk code on 20 oct)

**Comment by bensmiley** [comment]
I think you need to add the following to your `gradle.properties`

```
MIN_SDK = 16
ANDROID_BUILD_SDK_VERSION = 25
ANDROID_BUILD_TOOLS_VERSION = 25.0.2
ANDROID_BUILD_TARGET_SDK_VERSION = 25
ANDROID_COMPILE_SDK_VERSION = 25

GOOGLE_SERVICES_VERSION = 10.2.1
ANDROID_SUPPORT_VERSION = 25.3.1

CHAT_SDK_MAJOR_VERSION = 0
CHAT_SDK_MINOR_VERSION = 9
CHAT_SDK_PATCH_VERSION = 6
CHAT_SDK_BUILD_VERSION = 1
```

**Comment by bensmiley** [comment]
I'll remove this requirement from the next version.

**Comment by myeduapp** [comment]
Thank you for quick turnaround.
After making above changes I am getting below error.
Error:Execution failed for task ':app:processDebugManifest'.

> > Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [EducareTeacher:chat_sdk_firebase_push:unspecified] C:\Users\chat_sdk_firebase_push\build\intermediates\bundles\default\AndroidManifest.xml
> 	Suggestion: use tools:overrideLibrary="com.example.firebasepushnotifications" to force usage

Can MinSDkVersion  be changed to 15?

**Comment by bensmiley** [comment]
Reduced min API level to 15.
