### ISSUE TITLE
App crashes when Clicking + icon to open Actions Popup and then clicking Chose photo option 

### ISSUE THREAD

**Issue by rohitbhoite** [chat-sdk/chat-sdk-android#154]
Getting below error Page when clicking chose photo
Steps to reproduce:
1. Click + to open Actions popup
2. Click Chose photo(Pop up opens for Complete action using (Gallery,Photos))
3. Press Hardware back button
![screenshot_2017-10-23-21-34-52-982_com miui bugreport](https://user-images.githubusercontent.com/13239043/31900103-09dce1e2-b83b-11e7-959d-cb691135ad6c.png)

also How to create custom chat name when the user login to the app(Instead of CHATSDK***) and back button press should hide the chat activity instead of closing entire app?
Not able to find documentation around it with latest code.

**Comment by bensmiley** [comment]
This will be fixed in the next commit.

**Comment by rohitbhoite** [comment]
Thanks. Other issue is related to fetching contact. It is showing infinite
fetching pop up
