### ISSUE TITLE
Remove dependency on Fresco

### ISSUE THREAD

**Issue by brucexia** [chat-sdk/chat-sdk-android#157]
Lots of apps(including ours) are using glide or picasso, the ui module should not depend on Fresco.

**Comment by bensmiley** [comment]
We tried a number of different frameworks including Glide and Picasso but Fresco just worked the best. I think this problem will come up which ever image loading library we use. If we use Picasso, the host app may use Glide etc... If we use Glide, the host app may use Fresco. Is there a reason why you particularly don't like Fresco?

**Comment by brucexia** [comment]
No I haven't tried Fresco. I am a long time user of Glide and picasso. Maybe I should try fresco, but the point is as a sdk it should minimize the dependencies to allow more flexibility and easier integration for host app.

**Comment by bensmiley** [comment]
We have tried to minimize dependencies as much as possible but after evaluating Volley, Picasso and Glide, we decided that Fresco is the best fit. If it causes significant problems or if we see that the other libraries could offer a similar level of performance, I'd be happy to consider switching.
