### ISSUE TITLE
Firebase adapter module should not depend on ui module

### ISSUE THREAD

**Issue by brucexia** [chat-sdk/chat-sdk-android#158]
This is a weird dependency.  Can you assess the possibility to break this dependency?
There're three dependencies in FirebaseModule and FirebaseThreadHandler:
import co.chatsdk.ui.BaseInterfaceAdapter;
import co.chatsdk.ui.InterfaceManager;
import co.chatsdk.ui.utils.Strings;
The interfaceManager is initialized in FirebaseModule but only referenced in the ui module. Why not move it to the UI module?
        InterfaceManager.shared().a = new BaseInterfaceAdapter(context);

The Strings util can probably be moved to core module.

**Comment by bensmiley** [comment]
The ui dependency will be removed from the Firebase module in the latest version.
