### ISSUE TITLE
Add thread owner and index by owner(and possibly by participant)

### ISSUE THREAD

**Issue by brucexia** [chat-sdk/chat-sdk-android#159]
Not sure if there's better way but the goal is to achieve this:
-- implement some security rules to only allow owner update/delete a thread details
--Allow quick retrieving of threads owned(or possibly member of) by a user.

**Comment by brucexia** [comment]
You can assign tickets to me if you want me to fix. Just don't want to duplicate work @bensmiley

**Comment by bensmiley** [comment]
I was planning to update the security rules. If you want to have a go and submit a pull request, I can double check them.
