### ISSUE TITLE
Link in chat_sdk_firebase_social_login causes import to fail

### ISSUE THREAD

**Issue by StevenWoo** [chat-sdk/chat-sdk-android#162]
The link to chat_sdk_firebase_social_login in chat_sdk_firebase_social_login causes Android Studio to never be able to import the project when starting a new project and following the directions.  Deleting the link allows Android Studio to import the project.  Nobody else has whatever the link is pointing to on the developer's system.

**Comment by bensmiley** [comment]
This will be fixed in the next commit.
