### ISSUE TITLE
After logout & login back(with anonymous user)in old user data is shown in threads/profile

### ISSUE THREAD

**Issue by jagas** [chat-sdk/chat-sdk-android#167]
1.Login with any user
2. log out
3. Login with anonymous user
4. Old data stays in  threads/profile

it is fixed after app kill and resync

**Comment by bensmiley** [comment]
I tried this with the latest version and I can't replicate the issue. Are you testing on the unmodified code downloaded from Github? or is the Chat SDK integrated with your project?

**Comment by jagas** [comment]
I have 2 versions I check before I report.
one is cloned version where I have very little modifications.
but to confirm I use official demo to replicate a bug.

Maybe demo apk is old version and I should always compile directly from master/dev branches?

**Comment by bensmiley** [comment]
Could you see if you can produce this issue by compiling the app with the latest version?

**Comment by jagas** [comment]
checked with newest version, this cannot be replicated, closing a ticket
