### ISSUE TITLE
when pressing action "choose photo" intent is started multiple times

### ISSUE THREAD

**Issue by jagas** [chat-sdk/chat-sdk-android#168]
1. Accidentally double tapped on "Choose photo"
2. When chose first photo I`ve been transfered again to the same "choosing" window
3. After doing that few times, its enough one normal click for behavior to repeat itself

**Comment by bensmiley** [comment]
I tried the following:
1. Open chat screen
2. Click options
3. Choose photo tapping multiple times

**-and-**

1. Open edit profile screen
2. Tap photo multiple times

The intent is only started once. 

Are these the correct steps? Are you using the default project? What hardware and Android version are you using?

**Comment by jagas** [comment]
I managed to start activity more than once in both cases, using freshly built project from SDK, you got to tap real fast though, maybe this is low priority.

android version 6.0.1, samsung note 4

**Comment by bensmiley** [comment]
Can you check to see if you can still replicate this on the latest version?

**Comment by bensmiley** [comment]
Fixed in `4.0.7`.
