### ISSUE TITLE
It is possible to create a 1-to-1 thread with same user twice

### ISSUE THREAD

**Issue by jagas** [chat-sdk/chat-sdk-android#169]
Not sure if this is by design; If it is it should be at least allowed to rename each 1-to-1 thread

1. Create a thread from thread view pressing + sign
2. Create second thread from contacts view->single contact view-> pressing top right thread icon

**Comment by bensmiley** [comment]
This isn't supported by the default user interface by design. However, it is possible to do. I added a new function:

```
Single<Thread> createThread(String name, List<User> users, int type);
```

Using this, you could create a private group thread between two users:

```
NM.thread().createThread("Name", users, ThreadType.PrivateGroup).subscribe(...);
```
