### ISSUE TITLE
App terminates after showing main screen.

### ISSUE THREAD

**Issue by iamsharzil** [chat-sdk/chat-sdk-android#17]
Hi there,
I have followed all the steps correctly except facebook setup. I can register the user on my firebase account but after that the app gets terminate after showing the main layout screen.  Please help me. I want to use this as my final year project(200 marks) :(

**Comment by nowantednameisavailabel** [comment]
What is your project? In which university you study?

**Comment by bensmiley** [comment]
Can you please send a copy of the stack trace, and your google-services.json file and the BDefines.java file?

Also, bear in mind that you are not allowed to remove any copyright information from the project. Claiming that you wrote the project would be both a breach of the licensing conditions and plagiary and is definitely not recommended.
