### ISSUE TITLE
freshly cloned project wont compile because of gradle error

### ISSUE THREAD

**Issue by jagas** [chat-sdk/chat-sdk-android#171]
Android studio 3.0 needs flavorDimension

I just added solution specified here in order for project to compile
https://stackoverflow.com/questions/44105127/android-studio-3-0-flavor-dimension-issue

```
android { 
    ...
    flavorDimensions "default"
    ...
}
```

**Comment by bensmiley** [comment]
Currently this is only supported by Android Studio 3 which is still in beta. You can checkout this [branch](https://github.com/chat-sdk/chat-sdk-android/tree/master_gradle_3) that solves the issue.  Once the new version of Android Studio is released, this branch will be merged with the master.
