### ISSUE TITLE
Error:(52, 0) Could not get unknown property 'CHAT_SDK_GROUP' for project ':chat_sdk_core' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by bazear85** [chat-sdk/chat-sdk-android#174]
I am having this problem when I sync the project.

At chat_sdk_core/build.gradle, I get an error like this.

`group = CHAT_SDK_GROUP + '.core'
version = CHAT_SDK_VERSION

//bintray {
//    user = System.getenv("BINTRAY_USER")
//    key = System.getenv("BINTRAY_API_KEY")
//    configurations = ['archives']
//    pkg {
//        repo = 'chat-sdk-android'
//        name = 'chat-sdk-core'
//        userOrg = System.getenv("BINTRAY_ORG")
//        licenses = ['GPL-3.0']
//        vcsUrl = 'https://github.com/chat-sdk/chat-sdk-android.git'
//
//        version {
//            name = CHAT_SDK_VERSION
//            desc = 'Chat SDK Core'
//            released  = new Date()
//            vcsTag = CHAT_SDK_VERSION
//        }
//    }
`

**Comment by lHernan** [comment]
I have the exact same problem.

**Comment by bensmiley** [comment]
Add the following to `gradle.properties`

```
CHAT_SDK_VERSION = 4.0.0
CHAT_SDK_BUILD_NUMBER = 4000
CHAT_SDK_GROUP = co.chatsdk
```
