### ISSUE TITLE
How can I start chat activity between two users?

### ISSUE THREAD

**Issue by himanshubhaisare** [chat-sdk/chat-sdk-android#178]
Seems like `void startChatActivityForID(Context context, String threadEntityID);` would be my answer? But then what is threadEntityID? How do I get thread entity ID?

I would like to note that I don't my users to go through the login activity. Sort of want to force the anonymous login by default when a user clicks on chat button on a list item.

**Comment by himanshubhaisare** [comment]
I went through closed issues and found this to be the closest to what I am trying to achieve https://github.com/chat-sdk/chat-sdk-android/issues/96 but also seems outdated.

**Comment by bensmiley** [comment]
I think [this](https://github.com/chat-sdk/docs#creating-a-private-thread) should answer your question. 

But one thing to note is that the Chat SDK requires users to be authenticated. This can be anonymous, but the user has to be authenticated before you can start creating or joining threads. I'd recommend authenticating the user anonymously as soon as they open your app. An alternative would be to use semi-anonymous login. 

To do this, you would generate a unique username and a random password the first time the user opened the app. You would then authenticate using:

Username: [unique username]@yourdomain.com
Password: [random password]

You would then store these details on the device. The next time you would authenticate with the same details. The benefit here is that you would reduce the number of anonymous user profiles stored on Firebase.

**Comment by himanshubhaisare** [comment]
Thanks @bensmiley !

**Comment by agustinsivoplas** [comment]
@himanshubhaisare Could you find a solution? I am stuck at the same point.

**Comment by himanshubhaisare** [comment]
I actually ended up not using this sdk and re-implemented chat using firebase and this tutorial https://www.youtube.com/watch?v=XJvd8b3-Un4&index=2&list=PLGCjwl1RrtcQ3o2jmZtwu2wXEA4OIIq53
