### ISSUE TITLE
Getting cannot Resolve symbol 'FirebaseModule' with Latest code

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#179]
Getting this after downloading latest code and adding the modules to the existing project.Last time it worked properly.
 FirebaseModule.activate(context);

**Comment by rohitbhoite** [comment]
I am also facing this issue

**Comment by bensmiley** [comment]
You should review the setup instructions. They have been updated, streamlined and fully tested. See [here](https://github.com/chat-sdk/chat-sdk-android#adding-the-chat-sdk-to-your-project).
