### ISSUE TITLE
add the package name: com.braunster.androidchatsdk.firebaseplugin

### ISSUE THREAD

**Issue by nowantednameisavailabel** [chat-sdk/chat-sdk-android#18]
![image](https://cloud.githubusercontent.com/assets/23380362/23007053/74172adc-f427-11e6-8dde-acac32257578.png)
Why we have to include json file of this package? what information does it contain? why nis it necessary? please explain @bensmiley  @kykrueger

**Comment by kykrueger** [comment]
Hello,

The reason why the JSON file needs to be added is to link the android project with the firebase API. This workflow is used not only by google for firebase, but most other google APIs. Without it, you would be unable to access any google-services.

For more information on the generic use of Firebase for android, please see their [getting started guide](https://firebase.google.com/docs/android/setup).

-- Kyle

**Comment by nowantednameisavailabel** [comment]
I know JSON file is needed but why JSON file with the package name com.braunster.androidchatsdk.firebaseplugin is necessary? can we change the name of the JSON file? @kykrueger

**Comment by bensmiley** [comment]
The Chat SDK Firebase code is stored in a separate module which has it's own application id. During the build process, Gradle looks for the google-services.json file and checks that the app id defined there, matches the app id of the module. For this reason, you need to have a valid google-services.json file in the firebase_plugin folder with the id of the firebase_plugin module which is "com.braunster.androidchatsdk.firebaseplugin".

If you also want to access Firebase from your own app module, you should repeat the process to create a second google-services.json file which should be added to the app folder with your app's application id.
