### ISSUE TITLE
Permission denied on Firebase Database

### ISSUE THREAD

**Issue by volpatorafael** [chat-sdk/chat-sdk-android#180]
Hello!

     I filled the firebase rules with the recommended one (https://github.com/chat-sdk/chat-sdk-ios/blob/master/rules.json) and the sdk does not work, when the app try to interact with the database I get a "Permission Denied" error on logcat.
     When I changed the rules to a (extremely) permissive rule (*) it does work fine.
    Am I using the wrong firebase database rule or I missing anything else?

Thanks

(* permissive rule)
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null",
  }
}

**Comment by bensmiley** [comment]
I need to update the Firebase rules.

**Comment by ritesh-dubey** [comment]
I repeatedly get "DatabaseError: Permission denied" error when I try sending a message or while using the app. Any solutions?

**Comment by chogsed** [comment]
curious as well, im not getting anything :(

**Comment by AAPBD** [comment]
What kind of demo it is! Doesn't work after running the project and joining into Chat Rooms! It always say "Firebase database error: Permission denied"

You guys should give a working demo.

**Comment by bdndreams** [comment]
Not able to login in app, same error :"Firebase database error: Permission denied"

**Comment by bjs007** [comment]
Did anyone get a solution to this? I am unable to create a chat with a contact. It always shows firebase permission denied error.

**Comment by bensmiley** [comment]
Is this with your database or our test database? Did you added the security rules?

**Comment by bjs007** [comment]
I created a database as provided in the instruction to start the app. I used these rules
https://github.com/chat-sdk/chat-sdk-firebase/blob/master/chat-sdk-rules.json. It gives firebase permission error.

However, if I replace with following. It works.

(* permissive rule)
{
"rules": {
".read": "auth != null",
".write": "auth != null",
}
}

**Comment by overvox** [comment]
Having the same problem as @bjs007

**Comment by bensmiley** [comment]
Can you try with this:
https://github.com/chat-sdk/chat-sdk-firebase/blob/master/chat-sdk-rules.json

**Comment by overvox** [comment]
Looks like these changes fixed the issue. Thanks!

**Comment by optimus-droid** [comment]
> Can you try with this:
> https://github.com/chat-sdk/chat-sdk-firebase/blob/master/chat-sdk-rules.json

It's fixed the android firebase write permission issue but now web is not working. I am having 3 way communication i.e. Web, iOS, Android.
The previous rules was working between Web and iOS but not with Android.
The following error I a getting on Web -

`Error: permission_denied at /sohavest: Client doesn't have permission to access the desired data. all.js:1450:247802
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://freegeoip.net/json/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://freegeoip.net/json/. (Reason: CORS request did not succeed).`

**Comment by bensmiley** [comment]
@optimus-droid can you try with this version of the web project:

https://github.com/chat-sdk/chat-sdk-web

Also you can try it here:

http://web.sdk.guru/

If you can try to replicate the issue and tell me how to do it, I'll get it fixed.
