### ISSUE TITLE
Twitter OAuth in ChatSDK v3

### ISSUE THREAD

**Issue by sihan010** [chat-sdk/chat-sdk-android#181]
I have changed all the required values in strings file. But app's callback url is still https://chatcatsdk.firebaseapp.com/__/auth/handler
and all the tokens are still pre-given values.
How do I modify the application to use my Twitter application?

**Comment by bensmiley** [comment]
I think in v3 the Twitter key is actually defined multiple times in different Android Manifest files in different modules. Make sure that you have replaced every instance of the key with your new key. 

![screen shot 2017-11-11 at 3 14 43 pm](https://user-images.githubusercontent.com/5514010/32690206-18a189b4-c6f3-11e7-9906-5a33e135630b.png)

Do a project wide search for `twitter_consumer_key` to find the places where it's defined.
