### ISSUE TITLE
Is Chat-SDK compatible with quickblox server ?

### ISSUE THREAD

**Issue by sharp-edge** [chat-sdk/chat-sdk-android#182]
Hi, can I use Chat SDK for sending plain messages and basic features with Quickblox server ? If so are there any samples or examples for this.
Thanks

**Comment by bensmiley** [comment]
It would be possible but you would need to write a custom adapter. The Chat SDK has a clear separation between the user interface and the network backend. This is defined by the network adapter class and the network handlers. 

You should look at the [FirebaseNetworkAdapter](https://github.com/chat-sdk/chat-sdk-android/blob/master/chat-sdk-firebase-adapter/src/main/java/co/chatsdk/firebase/FirebaseNetworkAdapter.java) as an example. You will see that it contains a number of handlers and each of these handlers conforms to an interface. 

You would need to write your own handlers for Quickblox. I'd recommend starting with authentication. 

You would need to implement the following methods:

```
    Completable authenticateWithCachedToken();
    Completable authenticate (AccountDetails details);
    Boolean userAuthenticated();
    Completable logout();
    Boolean accountTypeEnabled(AccountDetails.Type type);
    Map<String, ?> getLoginInfo();
    void setLoginInfo(Map<String, Object> info);
    String getCurrentUserEntityID();
    void addLoginInfoData (String key, Object value);
```

Once you implement all these methods, you could setup your custom handler in the app start method and it should allow you to log in to Quickblox. After that you could have a look at starting to implement the core handler (which handles the user account) and the thread handler (which handles thread creation and message sending).

**Comment by sharp-edge** [comment]
Thanks for such a comprehensive answer @bensmiley . Really appreciate the response.
