### ISSUE TITLE
No Resource found error With latest gradle plugin

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#183]
@bensmiley  Getting below error when integrating latest code  with gradle plugin
![image](https://user-images.githubusercontent.com/32955380/32686987-bb14d49c-c6d7-11e7-8c08-51afd95bf923.png)

**Comment by ayounes3333** [comment]
Same here

**Comment by bensmiley** [comment]
This is fixed. You should review the setup instructions because they have changed a little. Use:

```
compile 'co.chatsdk.chatsdk:chat-sdk-core:4.0.5'
compile 'co.chatsdk.chatsdk:chat-sdk-ui:4.0.5'
compile 'co.chatsdk.chatsdk:chat-sdk-firebase-adapter:4.0.5'
compile 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.0.5'
```
