### ISSUE TITLE
how can i configure my own firebase Account?

### ISSUE THREAD

**Issue by Mubashir313** [chat-sdk/chat-sdk-android#184]

**Comment by bensmiley** [comment]
Follow the guide [here](https://github.com/chat-sdk/chat-sdk-android#firebase-setup).

**Comment by Mubashir313** [comment]
brother i dont understand this code will you please tell me
Enter your package name? 
app name? 
SHA-1 key?

**Comment by simonsmiley64** [comment]
Hi @Mubashir313,

I would recommend reading through the guide step by step and it explains exactly how to add the Chat SDK and configure it. If you are having trouble let us know as we offer configuration bundles where we can configure the Chat SDK and add it for your project for you.

**Comment by Mubashir313** [comment]
brother actually the problem is i cant figure out the package name when i put co.chatsdk.android.app as a package name the i cant configure will you please help to configure this new version app to firebase or send me some video tutorial of firebase configuration with this new version of android chat sdk
Thanks & Regards

**Comment by bensmiley** [comment]
I'd recommend looking at the [Firebase documentation](https://firebase.google.com/docs/storage/android). This appears to be an Android / Firebase issue rather than an issue with the Chat SDK. If you're really stuck, you could purchase some [priority support](https://chatsdk.co/support/) and then I could set up the project for you.

**Comment by Mubashir313** [comment]
hi.
I'm facing new error suddenly my app is going crash it can't reloaded.
please guide me
thanks

**Comment by bensmiley** [comment]
Hi, would it be possible for you to fill out the [issue template](https://github.com/chat-sdk/chat-sdk-android/blob/master/Issue%20Template.md)? That will help us to identify what's going wrong for you.
