### ISSUE TITLE
The custom token format is incorrect. Please check the documentation.

### ISSUE THREAD

**Issue by karna2605** [chat-sdk/chat-sdk-android#186]
Dear all,

I have a problem with the token authentification.
I did generate a token with an UID with this generator https://github.com/firebase/firebase-token-generator-node.

However when I try to authenticate with this token on my app with : 
`AccountDetails details = AccountDetails.token("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjowLCJkIjp7InVpZCI6IjVHbEVRdjF0Z2JodUpSbU5uSHNjODV4WkRHRzIifSwiaWF0IjoxNTExMDI5NTQ0fQ.r7S8-hrKbiUuXGHdCReFFAUZsH8kr5K8z5EmMGaOZvo");
`
`
        NM.auth().authenticate(details).subscribe(new Action() {
            @Override
            public void run() throws Exception {
                System.out.println("Test");
            }
        });`

I get this error : **The custom token format is incorrect. Please check the documentation.**

I do not understand why I am getting this user. This token is generated with the Secret Key of my Firebase account. The rest of the functions of the API works.

I look forward to hearing from any solution to this issue.

Thank you very much for your help.

**Comment by karna2605** [comment]
I apologize for disturbing the problem came from the firebase configuration on our server.

**Comment by nooralam6** [comment]
hi, i am facing the same issue, can you tell me what firebase configuration was wrong, and how did you made it work?
