### ISSUE TITLE
Public chat room

### ISSUE THREAD

**Issue by hirakchhatbar** [chat-sdk/chat-sdk-android#190]
I wish to use chat-sdk to create public chat rooms in my app. My app already includes authentication. Is it possible to by pass sdk login and create public chat rooms?
Any documentation?

**Comment by bensmiley** [comment]
To do this you will need to use [custom token authentication](https://github.com/chat-sdk/docs#custom-authentication). Once you've authenticated the user, you could use the [PublicThreadsFragment](https://github.com/chat-sdk/chat-sdk-android/blob/master/chat-sdk-ui/src/main/java/co/chatsdk/ui/threads/PublicThreadsFragment.java) to display a list of the public rooms available.
