### ISSUE TITLE
Bug with sending image message

### ISSUE THREAD

**Issue by Jinqianv** [chat-sdk/chat-sdk-android#195]
Sometimes image message is not sending properly.

**Comment by Jinqianv** [comment]
now sending two images at once

**Comment by bensmiley** [comment]
Hi @Jinqianv,

Would it be possible for you to fill out the [issue template](https://github.com/chat-sdk/chat-sdk-android/blob/master/Issue%20Template.md)? Then I can try to replicate the issue you're having and get it fixed. 

Thanks,

Ben

**Comment by Jinqianv** [comment]
This is the message I got.
...
V/MessagesListAdapter: TODO: https://firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2F70va6jrqjuugvio45v0621n2ca_image.jpg?alt=media&token=dd728c74-16f2-45d5-8ff2-532e951c48d1
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /https:/firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107: open failed: ENOENT (No such file or directory)
V/MessagesListAdapter: TODO: https://firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /https:/firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107: open failed: ENOENT (No such file or directory)
V/MessagesListAdapter: TODO: https://firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /https:/firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107: open failed: ENOENT (No such file or directory)
V/MessagesListAdapter: TODO: https://firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /https:/firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107: open failed: ENOENT (No such file or directory)
D/dalvikvm: GC_FOR_ALLOC freed 4883K, 22% free 17536K/22452K, paused 10ms, total 20ms
V/MessagesListAdapter: TODO: https://firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /https:/firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107: open failed: ENOENT (No such file or directory)
V/MessagesListAdapter: TODO: https://firebasestorage.googleapis.com/v0/b/fitlab-658a4.appspot.com/o/files%2Fuk1knkfsjod0gohrtkpfqr4r27_image.jpg?alt=media&token=d2dfdefa-3c87-4460-9fce-faf2a921d107
V/FA: Inactivity, disconnecting from the service

**Comment by Jinqianv** [comment]
after I choose photo, then should be moved to crop page, but just the activity closed.

**Comment by bensmiley** [comment]
Fixed in `4.0.7`
