### ISSUE TITLE
Contacts stored in firebase.

### ISSUE THREAD

**Issue by paakjis** [chat-sdk/chat-sdk-android#196]
Hi. 
Contacts are not stored in firebase. They are just stored on the device.
Are there plans on integrating user contacts into firebase ? So even after user deletes and reinstalls app, he still has all the users he added before.

What would be the best way for me to integrate it in my app ?

My plan is to add a column for each user that contains a list of user id's.
https://i.imgur.com/jwuBR1m.png

**Comment by bensmiley** [comment]
We do have plans to add the user contacts to Firebase although I can't give you an exact timeframe at the moment. 

Integrating this in your app would require several steps:

1. Get the IDs from Firebase

To do this you would add a listener to the that contains the user IDs. In your case, it would be:

  ```
  FirebasePaths.userRef("User ID").child("contacts").addValueEventListener(new ValueEventListener() {
                    @Override
                    public void onDataChange(DataSnapshot dataSnapshot) {
                        if(dataSnapshot.getValue() != null) {
                            // We now have access to the list of user IDs
                        }
                    }

                    @Override
                    public void onCancelled(DatabaseError databaseError) {

                    }
                });
  ```

2. Add these users to your contacts. I've updated the documentation to show you how to do this. Here's a link to the relevant section - [Adding a contact from a user ID](https://github.com/chat-sdk/docs#adding-a-contact-from-a-user-id).

**Comment by dreimanis** [comment]
Are you a Wizzard ? This is magic..It will take some time till I understand how the whole app works. 
I added these lines, and it works like magic. 
```
FirebasePaths.userRef(model.getEntityID()).child("contacts").addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                if(dataSnapshot.getValue() != null) {
                    for(DataSnapshot ds : dataSnapshot.getChildren()){
                        UserWrapper wrapper = UserWrapper.initWithEntityId(ds.getKey());
                        wrapper.metaOn();
                        wrapper.onlineOn();
                        User user = wrapper.getModel();
                        NM.contact().addContact(user, ConnectionType.Contact);
                    }
                }
            }
            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });

```

Only problem I noticed now is, when I delete contact from firebase it doesn't remove from list ( as expected ). But I'll figure it out. Thanks a lot :)

**Comment by agustinsivoplas** [comment]
In my case dataSnapshot.getValue() returns null. I am not able to add a contact. Any suggestion?

**Comment by tobimichigan** [comment]
Hi guys,
Please I just configured Chat SDK and deployed on an alpha channel.  I can't seem to know how to add and get a list of users from firebase console. Please any help will be appreciated.
 please this suggested code if implemented, where should go? Will it solve my current issue?:
`FirebasePaths.userRef(model.getEntityID()).child("contacts").addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                if(dataSnapshot.getValue() != null) {
                    for(DataSnapshot ds : dataSnapshot.getChildren()){
                        UserWrapper wrapper = UserWrapper.initWithEntityId(ds.getKey());
                        wrapper.metaOn();
                        wrapper.onlineOn();
                        User user = wrapper.getModel();
                        NM.contact().addContact(user, ConnectionType.Contact);
                    }
                }
            }
            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });`

**Comment by bensmiley** [comment]
This is now added in the latest version.
