### ISSUE TITLE
Bug with sending image message

### ISSUE THREAD

**Issue by Jinqianv** [chat-sdk/chat-sdk-android#198]
- Is the bug present in the demo Chat SDK project? (yes/no)
yes
- Steps taken to reproduce bug:
once sending an image message and go back to the thread list.
and again enter any chat activity, then I can not send image message.
- Expected result:
should be moved to the crop image activity.
- Actual result:
gallery is just closed 
- Comments:
onActivityResult in ChatActivity was not called by clicking gallery image item.

**Comment by bensmiley** [comment]
Seems to be a duplicate of #195.
