### ISSUE TITLE
User's not offline when app minimised

### ISSUE THREAD

**Issue by simonsmiley64** [chat-sdk/chat-sdk-android#2]
When a user closes the app they are set as offline in the database. This means push notifications will be sent to them.

With Android if the user minimises the app that user is still registered as online. This means they don't get sent push notifications and are marked as online in the app. How can we mark those users as offline when the app is minimised?

**Comment by kykrueger** [comment]
We have a base activity that all others in the app extend. By setting the user to offline when the activity lifecycle leaves focus, we could achieve this functionality.

**Comment by kykrueger** [comment]
Hi @simonsmiley64,

I have patched this issue in the 'hotfixes' branch. I am wondering if you could test the fix to see if it does what you expected.

If it works ill merge it into master.

-- Kyle
