### ISSUE TITLE
Build fails when trying to add to existing project

### ISSUE THREAD

**Issue by g0g0l** [chat-sdk/chat-sdk-android#20]
I am getting this error when trying to build: Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/android/volley/Request$Priority.class

Can you help please? Also I needed help about hoe to start chat activity in my existing project. My app already includes Fb and Google login feature

**Comment by bensmiley** [comment]
We recently updated the documentation for adding the Chat SDK to an existing project. Could you make sure that you've completed all the steps?

**Comment by simonsmiley64** [comment]
You can checkout a youtube video showing the steps of adding the Chat SDK to a custom project [here](https://www.youtube.com/watch?v=sMSlD_fftr0&t).

You can also see the complete wiki [here](https://github.com/chat-sdk/chat-sdk-android/wiki) with separate tutorials showing adding Chat SDK to your project and also how to configure the Firebase accounts for your new project.
