### ISSUE TITLE
Username/Password login trouble 

### ISSUE THREAD

**Issue by RogerRabbit91** [chat-sdk/chat-sdk-android#202]
I am almost certainly doing something wrong but I cannot get passed the "Authenticating..." window after attempting to login or register. The users login information is being stored in Firebase. I am not getting any error. my internet connection is strong. I hope you can help and thanks again.

**Comment by dlaravindhan** [comment]
same issue i can face. you go to firebase console and  change firebase rules seems like this

{
  "rules": {
    ".read": true,
    ".write": true
  }
}

  this is solve problem and program working

**Comment by RogerRabbit91** [comment]
Thank you this worked.
