### ISSUE TITLE
please can u give me a complete project

### ISSUE THREAD

**Issue by moekali** [chat-sdk/chat-sdk-android#203]
i get many errors like, Error:(20, 0) Could not get unknown property 'ANDROID_COMPILE_SDK_VERSION' for project ':chat-sdk-core' of type org.gradle.api.Project.
<a href="openFile:C:\Users\Admin\Desktop\android-firebase-chat-master\KhalilChat\chat-sdk-core\build.gradle">Open File</a>

**Comment by bensmiley** [comment]
The best approach would be to include the Chat SDK using Gradle as laid out in the [instructions](https://github.com/chat-sdk/chat-sdk-android#gradle).

Alternatively, if you want to import the modules manually, you should add this to your `gradle.properties`

```
MIN_SDK = 16
ANDROID_BUILD_SDK_VERSION = 25
ANDROID_BUILD_TOOLS_VERSION = 27.0.2
ANDROID_BUILD_TARGET_SDK_VERSION = 25
ANDROID_COMPILE_SDK_VERSION = 27

GOOGLE_SERVICES_VERSION = 10.2.1
ANDROID_SUPPORT_VERSION = 25.3.1
```
