### ISSUE TITLE
XMPP Chat SDK for Android

### ISSUE THREAD

**Issue by abbaselectricwala** [chat-sdk/chat-sdk-android#204]
How can we integrate or host the API for chat SDK on our server? Is there any document provided for that

**Comment by bensmiley** [comment]
It is possible to host the Chat SDK on your own server but to do that you would need the [XMPP Module](https://chatsdk.co/xmpp-2/). With that module you would be able to use either [ejabberd](https://www.ejabberd.im/) or [OpenFire](https://www.igniterealtime.org/projects/openfire/).

**Comment by abbaselectricwala** [comment]
@bensmiley  Is there any document or tutorial which tells the detailed procedure for XMPP Module

**Comment by bensmiley** [comment]
There is detailed documentation which explains how to setup the XMPP module. We usually distribute this documentation with the XMPP module but if you're interested you can see a copy [here](https://www.dropbox.com/s/9d3wrh8bi43nvco/XMPP_README.md?dl=0).
