### ISSUE TITLE
Chat SDK registeration problem

### ISSUE THREAD

**Issue by abbaselectricwala** [chat-sdk/chat-sdk-android#210]
I have setup chat SDK in my project using FCM I am using

```
NM.auth().authenticate(details)
.observeOn(AndroidSchedulers.mainThread())
.doFinally(new Action() {
@override
public void run() throws Exception {
authenticating = false;
dismissProgressDialog();
}
})
.subscribe(new Action() {
@override
public void run() throws Exception {
afterLogin();
}
}, new Consumer() {
@override
public void accept(Throwable e) throws Exception {
toastErrorMessage(e, false);
e.printStackTrace();
}
});
}
```

method to register but its not going in side subscribe method .

Also for the sample Chat SDK project when i run the same i get the following error.
com.google.firebase.auth.FirebaseAuthUserCollisionException: The email address is already in use by another account.

Please help me out

**Comment by bensmiley** [comment]
If you use the default unmodified Chat SDK that you checkout from Github, are you able to register? Also, that error is caused because you're trying to register with an email address that already exists.

**Comment by thecmart** [comment]
@abbaselectricwala There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.
