### ISSUE TITLE
createThread not creating the thread

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#211]
CreateThread Method is not creating the thread. It is giving UnSupportedOperationException in Handle Error Block.

```
 NM.thread().createThread("testthread",user).observeOn(AndroidSchedulers.mainThread())
                        .subscribe(new Consumer<Thread>() {
                            @Override
                            public void accept(Thread thread) throws Exception {
                                InterfaceManager.shared().a.startChatActivityForID(getApplicationContext(),thread.getEntityID());
                            }
                        }, new Consumer<Throwable>() {
                            @Override
                            public void accept(@NonNull Throwable throwable) throws Exception {
                                // Handle error
                                System.out.print(throwable.getMessage());
                            }
                        })
```

User with whom thread is to be created is generated as 
`StorageManager.shared().fetchEntityWithEntityID(parentId, User.class);`

It is returning the user as expected but thread is not getting created.

**Comment by myeduapp** [comment]
if below code is used then thread is opening properly.So it seems that if the thread name is passed then the method call is not working.
```
  User user1 = StorageManager.shared().fetchOrCreateEntityWithEntityID(User.class, userid);
                List<User> users=new ArrayList<User>();
                users.add(user1);
                NM.thread().createThread(users)
```

**Comment by aymenhs** [comment]
had it been resolved? I faced the same problem when using with android 5.1.1 (no problem with android 7 )

**Comment by thecmart** [comment]
@myeduapp We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.
