### ISSUE TITLE
adding navigation drawer to the MainActivity

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#212]
I am able to extend activities as per my requirement.I want to show NavigationDrawer in the main activity.In my application the navigation drawer is implemented in BaseActivity which other activities are inheriting.How the same can be achieved in chat sdk?(Any help regarding this will be useful?)

**Comment by bensmiley** [comment]
You should be able to achieve this using this [guide](https://github.com/chat-sdk/docs#subclassing-using-the-interface-manager).  You can subclass the main activity and then override the `getMainActivity` method of your custom interface adapter to return your subclass:

```
public Class getMainActivity() {
    return YourMainActivity.class;
}
```

**Comment by myeduapp** [comment]
@bensmiley Do I have to add Navigation Drawer programmatically.As I cannot extend AppBaseActivity which I am doing for my App specific activities?How it can be achieved easily?

**Comment by bensmiley** [comment]
In this situation it would be difficult to make every activity extend one base activity. Is that the recommendation for setting up this navigation draw? I would expect that you should be able to do everything you need to do by extending the main activity. In much the same way that the main activity implements a tab layout. If I get time, I'll try to implement this and add it to the core library.

**Comment by myeduapp** [comment]
Yes Navigation drawer basically needs DrawerLayout as base layout.I would be helpful if this plugin allows to setup base activity programatically. Is this possible?

**Comment by myeduapp** [comment]
When this feature will be available?

**Comment by myeduapp** [comment]
@bensmiley  I am planning to release my app to production but as chat sdk is having issues I am unable to do so.When Call the pending issues will be resolved?This library has saved our hours of effort.Thank You.

**Comment by myeduapp** [comment]
@bensmiley could you let me know when this feature will be added? I am also waiting for open issues to be closed to roll out our application.

**Comment by myeduapp** [comment]
how this can be implemented  till it becomes available in sdk?

**Comment by myeduapp** [comment]
@bensmiley  how this can be implemented till it becomes available in sdk?

**Comment by bensmiley** [comment]
Added in v5
