### ISSUE TITLE
How to show all users

### ISSUE THREAD

**Issue by dlaravindhan** [chat-sdk/chat-sdk-android#216]
i am using phone number authentication to login so i want to show contact list.that is saved in my phone contact otherwise not show like whatsapp give some reference

**Comment by bensmiley** [comment]
To do that you would need to use the [contact book integration](https://chatsdk.co/contact-book-integration/) module. It searches the contact book and shows a list of existing contacts by cross referencing the phone numbers and email addresses. It also allows you to invite other contacts by email or SMS.
