### ISSUE TITLE
Profile picture issue

### ISSUE THREAD

**Issue by dlaravindhan** [chat-sdk/chat-sdk-android#218]
when new user login then automatically create profile that is given different profile picture .

how to clear that profile picture and fix standard one. give reference

**Comment by bensmiley** [comment]
If you want to give the user a custom profile during login, you would need to set the `defaultUserAvatarURL` property during setup:

```
Configuration.Builder builder = new Configuration.Builder(context);
builder.defaultUserAvatarUrl("http://web-address-of-avatar.png");
```
