### ISSUE TITLE
Audio recording module bug. java.io.FileNotFoundException:

### ISSUE THREAD

**Issue by dreimanis** [chat-sdk/chat-sdk-android#219]
Clicking on the record button it crashes the app.
I noticed these lines
`V/AudioRecorder: Recording to: /storage/emulated/0/Documents/AudioMessages//Audio_f9374dc0-2db6-4a50-abeb-d3ffe4441551.m4a`

`W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Documents/AudioMessages/Audio_f9374dc0-2db6-4a50-abeb-d3ffe4441551.m4a: open failed: ENOENT (No such file or directory)`

Recording to has one extra '/'. 

Changing line 32 in AudioRecorder.java fixes the issue. 
from
`String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).getAbsolutePath() + File.separator + AudioMessageDirectory + File.separator;`
to
`String path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).getAbsolutePath() + AudioMessageDirectory + File.separator;`

**Comment by bensmiley** [comment]
Fixed and will be available in release 4.0.9.
