### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by Swapnildhamale92** [chat-sdk/chat-sdk-android#222]
I did all procedure as mentioned in doc also started push module by calling 
        FirebasePushModule.activateForFirebase();
in main activity but notifications not coming to receiver and sender have below error on logcat -

V/FirebasePushHandler: Push response: Response{protocol=h2, code=401, message=, url=https://fcm.googleapis.com/fcm/send}

Please help me to sort out notification thing.

**Comment by dreimanis** [comment]
https://github.com/chat-sdk/chat-sdk-android/issues/189

To fix it I added the key manually @ Configuration.java line 39 public String firebaseCloudMessagingServerKey = "MY KEY";

**Comment by bensmiley** [comment]
The documentation has now been updated. See [revised version](https://github.com/chat-sdk/chat-sdk-android#push-notifications).

**Comment by tobimichigan** [comment]
@bensmiley , the link you gave for the notifications is referring to an obsolete or deprecated "compile" index.

Push Notifications
Add the following to your build.gradle
Add the library 
Gradle 
compile 'co.chatsdk.chatsdk:chat-sdk-firebase-push:4.4.8'
Manual Import
compile project(path: ':chat-sdk-firebase-push')
Enable the module
In your main class onCreate method add:
FirebasePushModule.activate(); (This I have done but the message notifications are still not showing up.)

 and @paakjis , the reference code you made there on line 39 is missing from the new repo as of December, 2018.

So how do I get the notifications to work?
