### ISSUE TITLE
Chat SDK activities not going on the backstack properly

### ISSUE THREAD

**Issue by cireficc** [chat-sdk/chat-sdk-android#228]
I am starting the `co.chatsdk.ui.main.MainActivity` intent from a menu item click:

```
public boolean onOptionsItemSelected(MenuItem item) {
        
    Intent intent = null;

    switch (item.getItemId()) {
        ...
        case R.id.action_chat:
            //InterfaceManager.shared().a.startMainActivity(this); // same issue as below
            intent = new Intent(HomeActivity.this, co.chatsdk.ui.main.MainActivity.class);
            break;
    }

    if (intent != null) startActivity(intent);
    return super.onOptionsItemSelected(item);
}
```

It starts up just fine, no issue there. However, I would assume that pressing the system *back* button would take me to my previous activity (`HomeActivity`). However, the first click presents the toast **"click back again to exit"**, and the second click simply exits the app instead of returning to `HomeActivity`.

It looks like it's caused by the [`CloseApp`](https://github.com/chat-sdk/chat-sdk-android/blob/4c76459b33cca3a26090542b9cd6634b2190116a/chat-sdk-ui/src/main/java/co/chatsdk/ui/helpers/ExitHelper.java#L80) code. If I understand it right, it's supposed to restart with my app's main activity, which is defined as this:

```
<activity
    android:name=".Activities.HomeActivity"
    android:label="@string/app_name"
    android:launchMode="singleInstance"
    android:screenOrientation="portrait">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.HOME"/>
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>
```

Instead, it exits the app completely. I now have two options:

1. Click on my app icon
2. Use the task manager to reopen the app

If I do #1, I arrive at my home screen. If I do #2, I'm back to the Chat SDK `MainActivity`.

I don't think this behavior is normal. Am I missing something in my code? I think that the intended behavior is that `MainActivity` is `finish()`-ed, and my `HomeActivity` is launched.

**Comment by cireficc** [comment]
After some experimentation, I can come closer to the desired behavior by manually specifying Chat SDK's parent activity in the manifest:

```
<activity
    android:name="co.chatsdk.ui.main.MainActivity"
    android:label="@string/action_chat"
    android:parentActivityName=".Activities.HomeActivity"
    >
</activity>
```

This workaround provides a "back button" in the ActionBar itself, which works to take me back to the previous activity. However, the system back button still forces an app exit, which seems wrong, especially when the rest of my app relies on the system back button. Having users use the ActionBar just for the chat activity seems weird.

Though it still seems that Chat SDK is doing too much with the backstack and it's causing some weird issues... within Chat SDK itself, the system back button works fine. But switching between app activities and Chat SDK activities is buggy.

**Comment by cireficc** [comment]
PS - this problem exists even when started from an activity where `android:launchMode` is not `"single_instance"`. Using the system back button always causes the app to exit completely.

**Comment by bensmiley** [comment]
The `ExitHelper` was a deprecated class which has now been removed. This will be available in 4.0.9.

**Comment by myeduapp** [comment]
@bensmiley how to handle this scenario?

**Comment by guitorioadar** [comment]
This scenario must have a good solution... please share with us....

**Comment by bensmiley** [comment]
@guitorioadar This issue is from 2018, are you sure it's still relevant?
