### ISSUE TITLE
Trying to fetch a user.

### ISSUE THREAD

**Issue by jebran0103** [chat-sdk/chat-sdk-android#229]
When I enter the username of the user I'd like to chat with, it just says "Fetching" for a really long time and doesn't come up with anything.

**Comment by victor-m-1994** [comment]
I'm having the same issue... what was the solution?

**Comment by jebran0103** [comment]
Ok so basically the way chat SDK works is once a user has registered, the username is not his email. A new username is created which is normally in the format of "ChatSdk1223". Now say you're searching for that user then you'd have to type in the exact USERNAME i.e "ChatSdk1223". You can change the username in the profile tab. Hope this helped :)
