### ISSUE TITLE
Play Services and AppCompat versions?

### ISSUE THREAD

**Issue by rnstewart** [chat-sdk/chat-sdk-android#230]
Hi, and thanks for creating this project. It looks really awesome, and I'd love to play around with it.

Unfortunately, I ran into some version conflicts when I tried to import it into my project. I am using version 11.8.0 of Play Services, and version 26.1.0 of the AppCompat libraries. But when I imported the Chat SDK libraries, Gradle complained about version conflicts; it looks like your project is using v11.4.0 of Play Services and v25.3.1 of AppCompat.

I could try downgrading my versions for compatibility, but I'm not sure what other problems that might cause. Is there a chance you could update your versions soon?

Thanks again, and I appreciate all of your hard work.

**Comment by bensmiley** [comment]
We try to update the dependencies regularly. Today there will be a new build with bug fixes which will move to the latest versions of the build tools and google services:

```
GOOGLE_SERVICES_VERSION = 11.8.0
ANDROID_SUPPORT_VERSION = 27.0.3
```

Check out version 4.0.9 which will be released later today.

**Comment by rnstewart** [comment]
Hey, Ben. Thanks for the quick response on this.

I updated to v4.0.9 and re-synced, and most of the problems went away. Unfortunately, I'm still getting one Gradle error referring to com.android.support:mediarouter-v7:25.5.0. Here's a screenshot:

![screenshot 2018-02-07 13 10 41](https://user-images.githubusercontent.com/12358053/35939222-ba94b480-0c08-11e8-9514-5c8a1acd90c0.png)

**Comment by rnstewart** [comment]
Never mind. It looks like it's building without any errors, so whatever this error is it looks like it's a false alarm.
