### ISSUE TITLE
Error on runtime

### ISSUE THREAD

**Issue by DivyeshKevadiya** [chat-sdk/chat-sdk-android#231]
When i am going to add chat dependencies in my app then i am facing this bellowed error on run time.
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
please help me.
thanks in advanced.
![sw](https://user-images.githubusercontent.com/8266501/35956940-b1f33d4a-0cbe-11e8-861a-66346ad82eca.PNG)

**Comment by bensmiley** [comment]
Hi @DivyeshKevadiya 

I'd recommend trying some of the solutions in this [thread](https://stackoverflow.com/questions/46267621/unable-to-merge-dex).

1. Update to the latest version `4.0.9`
2. Make sure that you are using these versions of google services and support libraries:

```
GOOGLE_SERVICES_VERSION = 11.8.0
ANDROID_SUPPORT_VERSION = 27.0.2
ANDROID_BUILD_TOOLS_VERSION = 27.0.3
``` 

3. Make sure multi-dex is enabled:

```
android {
    defaultConfig {
       multiDexEnabled true
    }
}
```

**Comment by DivyeshKevadiya** [comment]
Thanks bensmiley fixed now the issue and i am very happy after many days to see success implementations.

**Comment by pcegarra** [comment]
Im using 
`    implementation 'co.chatsdk.chatsdk:chat-sdk-core:4.0.9'
    implementation 'co.chatsdk.chatsdk:chat-sdk-ui:4.0.9'
    implementation 'co.chatsdk.chatsdk:chat-sdk-firebase-adapter:4.0.9'
    implementation 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.0.9'`

And getting the same error, using support 27.0.2 and buildToolsVersion 27.0.3,multiDexEnabled,jumboMode and javaMaxHeapSize activated
