### ISSUE TITLE
Questions about using this with an existing Firebase database

### ISSUE THREAD

**Issue by rnstewart** [chat-sdk/chat-sdk-android#232]
I am working on an app that already makes extensive use of Firebase, and I'm evaluating this library as a means to add chat capabilities for our users.

My main concern is to make sure that I don't accidentally do anything with this code that will alter or delete our existing Firebase nodes. When I call `firebaseRootPath()` on the Configuration Builder, how does that work with my existing database nodes? I.e., if I have an existing database that looks like:

mycompany
- users
- organizations
- groups
- stuff
etc.

And I call `firebaseRootPath('chat')` on the Builder, will that create a new `chat` node underneath the `mycompany` node, without affecting any of the other nodes?

Thanks for your help!

**Comment by bensmiley** [comment]
Hi @rnstewart,

The root path is essentially a namespace for the Chat SDK data. Here's an example from a real database:

![screen shot 2018-02-09 at 8 17 21 pm](https://user-images.githubusercontent.com/5514010/36045514-45be11e0-0dd6-11e8-8eec-59a59cf21c04.png)

You can see each root path has it's own chat instance. This means that if you set the root path to `chat` the Chat SDK library wouldn't make any changes to any path outside `root/chat`.

**Comment by rnstewart** [comment]
OK, perfect. That's what I thought, but thank you for clarifying.
