### ISSUE TITLE
Get user's online status

### ISSUE THREAD

**Issue by cireficc** [chat-sdk/chat-sdk-android#234]
I have the following simple code:

```
UserWrapper wrapper = UserWrapper.initWithEntityId(firebaseId);
wrapper.metaOn();
wrapper.onlineOn();
wrapper.goOnline();
User user = wrapper.getModel();
```

Now I have access to the user's data (e.g. *name*, *status*, etc.). However, one key that is not included in the `User` core object, nor metadata, is `online` status. I assumed that I could use `user.metaStringForKey(Keys.Online)`, or that there would be a getter like `user.isOnline()`, but the `online` key in Firebase (shown below) is not accessible anywhere in the `User` object.

Is this intended behavior? I could always use some ridiculous `Date` hacks on `user.getLastOnline()` and `new Date()`, but this seems to defeat the purpose of storing `online` in Firebase at all...

<img width="395" alt="screen shot 2018-02-12 at 2 59 42 pm" src="https://user-images.githubusercontent.com/6238699/36100283-039b003e-1006-11e8-89e6-9f6016ad0159.png">

**Comment by bensmiley** [comment]
Hi @cireficc,

The online key isn't included in the meta data. You need to look at their availability:

```
model.getAvailability().equals(Availability.Available); // Online
model.getAvailability().equals(Availability.Unavailable); // Offline
```

**Comment by cireficc** [comment]
@bensmiley thanks for the quick response. I do see how *availability* is processed after looking at `ProfileFragment` and `AvailabilityHelper`. However, I want to know when the user is *actively using Chat SDK* - that is, when the launch a ChatSDK-related activity, the `online` key appears in Firebase. I really prefer to have *that* data rather than availability.

Is it possible to access that data at all (maybe a feature request)? Or do I have to rely only on `getAvailability()`?

**Comment by bensmiley** [comment]
If you want to do this yourself, you could add the key to [metadata](https://github.com/chat-sdk/docs#users). Just add a parameter when the chat opens and remove it when the chat closes. You could also use the [onDisconnect](https://firebase.google.com/docs/reference/android/com/google/firebase/database/OnDisconnect) method to undo this value when the user closes the app.

**Comment by cireficc** [comment]
@bensmiley That seems like a reasonable solution. Thanks for your help!

**Comment by cireficc** [comment]
@bensmiley Sorry but one last question. Is there a handler for when the chat opens/closes (i.e. `LoginActivity` or `MainActivity` are started/stopped)?

**Comment by bensmiley** [comment]
Currently there isn't but you could add one. You would need to fork the framework and add code like this:

```
NM.hook().executeHook(BaseHookHandler.ChatMainActivityStarted, null);
NM.hook().executeHook(BaseHookHandler.ChatMainActivityStopped, null);
```

You could then listen for the notification using:

```
        Hook authHook = new Hook(new Hook.Executor() {
            @Override
            public void execute(HashMap<String, Object> data) {
            }
        });

    NM.hook().addHook(authHook, BaseHookHandler.ChatMainActivityStarted);
```

Once that's done you could submit a pull request. If you did that today, I could probably have the framework updated by tomorrow.

**Comment by cireficc** [comment]
@bensmiley I actually just hooked into application lifecycle events and checked to see if the user was authenticated with Firebase, then updated the metadata appropriately with:

```
NM.currentUser().setMetaString(Keys.Online, CHAT_STATUS_ONLINE);
NM.core().pushUser().subscribe();
```

which actually works better for my case, because I indeed wanted to track online *in the app* and not just *inside a Chat SDK activity*. Thank you for all of your advice and help!
