### ISSUE TITLE
Private group chat

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#235]
I want to create a private group, in which only the owner of group can add the members or owner can approve the member request for that group. Is it possible to do this. 
If its not possible give me some tips to implement it.

**Comment by bensmiley** [comment]
It is possible to do this but the process is a bit involved. You would need a good understanding of how threads work at the moment and how Firebase works. You would need to do the following:

1. Modify the security rules so only owners can modify the thread user list
2. Check that this doesn't cause any crashes and fix any crashes that occur - handle the permission denied error received when a non-owner tries to add a user. 
3. Add an extra list to the thread called pending-users. The admin should listen to this list from the `threadOn` method in the [thread wrapper](https://github.com/chat-sdk/chat-sdk-android/blob/master/chat-sdk-firebase-adapter/src/main/java/co/chatsdk/firebase/wrappers/ThreadWrapper.java).
4. When a new pending user is found, the admin would be able to decide whether to add this user to the thread or not. 
5. After that, the user should be removed from the pending list.
