### ISSUE TITLE
Login using existing Facebook session

### ISSUE THREAD

**Issue by cireficc** [chat-sdk/chat-sdk-android#237]
Sorry to create yet another issue, but this one I think is pretty simple. I already have Facebook login active using the Facebook SDK. I have access to the Facebook authentication token which I can use to authenticate with Firebase directly. Long story short - can I authenticate Chat SDK using an existing Facebook `AccessToken` without the user starting Chat SDK's `LoginActivity`?

I can authenticate with Firebase directly, no problem:

```
FirebaseAuth firebaseAuth = FirebaseAuth.getInstance();
AccessToken facebookToken = AccessToken.getCurrentAccessToken();
AuthCredential credential = FacebookAuthProvider.getCredential(facebookToken.getToken());
        
firebaseAuth.signInWithCredential(credential)
    .addOnCompleteListener(new OnCompleteListener<AuthResult>() {
        @Override
        public void onComplete(@NonNull Task<AuthResult> task) {
            if (task.isSuccessful()) {
                // This works
                FirebaseUser user = firebaseAuth.getCurrentUser();
            } else {
                // Not important for this GH issue
            }
        }
    });
```

It creates the account in Firebase **authentication** section. However, I *also* want to create the account in the **database**. The only way I have found to do this is to start the Chat SDK `LoginActivity`. But, I want to create this account *without the user having to start that activity*. I tried looking through `LoginActivity` and found this code:

```
NM.socialLogin().loginWithFacebook(this).doOnError(error)
    .observeOn(AndroidSchedulers.mainThread())
    .doFinally(doFinally)
    .subscribe(completion, error);
```

But it seems this can't be used outside Chat SDK (I tried...). Is there any solution to this? I just want to perform the account setup step in the background, since the user is already authenticated with Facebook.

**Comment by bensmiley** [comment]
You definitely can do this and your code is 90% correct. After you've authenticated with Firebase you should call:

```
        NM.auth().authenticateWithCachedToken().subscribe(new Action() {
            @Override
            public void run() throws Exception {

            }
        }, new Consumer<Throwable>() {
            @Override
            public void accept(Throwable throwable) throws Exception {

            }
        });
```

This will then setup the Chat SDK using your existing Firebase session. After that, you can present any Chat SDK activities and everything should work correctly.

**Comment by cireficc** [comment]
@bensmiley You are an amazing guy! Thank you so much for your help getting through all of my issues :)

**Comment by cireficc** [comment]
Last thing I promise! There was an issue loading/syncing messages after implementing this, because `observeOn()` was not called. The full code should be:

```
NM.auth()
    .authenticateWithCachedToken()
    .observeOn(AndroidSchedulers.mainThread()) // you need this :)
    .subscribe(new Action() {
        @Override
        public void run() throws Exception {
        }
    }, new Consumer<Throwable>() {
        @Override
        public void accept(Throwable throwable) throws Exception {
        }
    });
```
