### ISSUE TITLE
Show all contacts 

### ISSUE THREAD

**Issue by hilmanzu** [chat-sdk/chat-sdk-android#239]
Hey Ben... I want to show contacts without using search index...

**Comment by bensmiley** [comment]
Hi @hilmanzu If you don't want to use the search index, where would the contacts be displayed from?

**Comment by hilmanzu** [comment]
thanks ben already reply to my message ,,, finally i've found a way to
display all contacts without using search index ...


Pada tanggal 23 Feb 2018 8.14 PM, "Ben Smiley" <notifications@github.com>
menulis:

**Comment by hilmanzu** [comment]
Oke ben

Pada tanggal 23 Feb 2018 8.25 PM, "Ben Smiley" <notifications@github.com>
menulis:
