### ISSUE TITLE
The wiki point to the wrong repository

### ISSUE THREAD

**Issue by Kryze** [chat-sdk/chat-sdk-android#24]
The section Wiki point to https://github.com/chat-sdk/chat-sdk-ios/wiki

**Comment by kykrueger** [comment]
Hi Kryze,

Thanks for pointing this out. Where is this broken link? 

-- Kyle

**Comment by Kryze** [comment]
Hi,
On the Wiki category of the Readme, it redirects to the IOS repository

**Comment by kykrueger** [comment]
Ok, 

I patched this in the master branch. 

Thanks again,

-- Kyle
