### ISSUE TITLE
Error:Failed to open zip file.

### ISSUE THREAD

**Issue by alihusnainarshad** [chat-sdk/chat-sdk-android#240]
Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>

**Comment by bensmiley** [comment]
To me this seems like it could be that Android Studio is having problems connecting to the network. You should check that it's not being blocked by your firewall or virus scanner.
