### ISSUE TITLE
Push Multiple Devices

### ISSUE THREAD

**Issue by Mithrandir21** [chat-sdk/chat-sdk-android#245]
Because the DB only contains a single field for user "pushToken", messages can only be delivered to a single device.
If the user has multiple devices signed in, like a Mobile and a Tablet, only the device that signed in last will get the Push notification.

This can easily be remedied by having multiple PushTokens for each signing and sending push notifications to all. (PushTokens can contain a timestamp and old PushTokens can be removed.)

**Comment by snipe717** [comment]
This would be extremely helpful for my use case. Please could you advise me when this has been implemented and which code I need to update to benefit.

**Comment by snipe717** [comment]
Assuming that this would be appropriate to the iOS side of things, too??

**Comment by bensmiley** [comment]
This is fixed as of the latest version.
