### ISSUE TITLE
Push Notifications do not contain Extras

### ISSUE THREAD

**Issue by Mithrandir21** [chat-sdk/chat-sdk-android#247]
I am trying to receive the Push notifications in another activity in the application.

When the app is in the background, I receive Push Notification with the correct visual data.
But when I open click on it and open the app, I am missing the necessary data to be able to redirect with the help of the ```OpenFromPushChecker```.
Specifically, the extra in the intent does not contain ```BaseInterfaceAdapter.THREAD_ENTITY_ID, Defines.FROM_PUSH, Defines.MSG_TIMESTAMP```. Therefore the open from push checker fails.

I believe it might have something to do with the work done in the ```MessagingService```.

**Comment by Mithrandir21** [comment]
I believe I have found the cause of the issue. Somewhat surprising.

It looks like the notification is create in the  ```private Completable pushToChannel(...)``` in the ```FirebasePushHandler```. But as the source code shows, the fields checked for in the ```OpenFromPushChecker``` are not added to the ```data```. Therefore the check will fail.

Is this a mistake in the FirebasePushHandler? Is this a mistake in the OpenFromPushChecker? Am I seeing it wrong?

**Comment by KAPLANDROID** [comment]
is this solved?
