### ISSUE TITLE
Group chats gets create for new users too

### ISSUE THREAD

**Issue by iamuseless** [chat-sdk/chat-sdk-android#25]
Hi there,
I have logged in as a new user but whatever group chats I have done from different account was created for the new users also.

**Comment by kykrueger** [comment]
Hello,

Please check if the chats you had created were private or public chats. If they were made in the second tab of the demo app they will be public chats ( available to all users, new and old; these are supposed to be like chat rooms ).

-- Kyle

**Comment by iamuseless** [comment]
@kykrueger Hey thanks and if I want to remove a user from private or public chat then how should I do it?

**Comment by kykrueger** [comment]
The current version of the SDK does not support removing users from a chat. However, removing uses from a private chat is being implemented on a coming version. As for removing users from a public chat, this is not something we plan on making possible. The public chats are inherently open to all users.

If you would like to implement removing a user from a chat, I would recommend adding a new click mode to [ChatSDKAbstractContactsFragment](https://github.com/chat-sdk/chat-sdk-android/blob/master/sdk/src/main/java/com/braunster/chatsdk/fragments/abstracted/ChatSDKAbstractContactsFragment.java). In this click mode I would try adding a new dialog to ask the user if they want to delete the user. You could even do this on a long press if it suits your taste better.

To delete a user from a thread, the method you should then call is ```removeUsersFromThread(BThread thread, List<BUser> users);``` from the networkAdapter. 

Then, update click mode that is set before opening this fragment in [thread details activity](https://github.com/chat-sdk/chat-sdk-android/blob/master/sdk/src/main/java/com/braunster/chatsdk/activities/ChatSDKThreadDetailsActivity.java).

-- Kyle

**Comment by iamuseless** [comment]
Hey thanks, I'm new to android studio but I'll try.

**Comment by kykrueger** [comment]
Working on a project that has been developed by various developers can be priceless learning experience. If you encounter things that don't make sense in the back-end feel free to re-open this issue to clarify. 

Also, I would recommend finding some good blogs for android development (quite a few posts [here](https://medium.com/tag/android)), and doing some tutorials. However, keep in mind that there are many different ways of doing things when it comes to development, and there are often conflicting ideas in the community. So keep an open mind.

All the best! 
-- Kyle
