### ISSUE TITLE
UI changes is getting lost after update

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#256]
Hi @bensmiley,  I added the chat sdk as module but after updating the module with latest stable version of sdk all  old UI changes were gone. is there a way to update the module without loosing UI changes ?

**Comment by bensmiley** [comment]
Hi @rahulsharmagbpec, to get around this you need to make sure that you don't modify any of the Chat SDK library code. To do that you can follow [this guide](https://github.com/chat-sdk/docs#customizing-the-user-interface). Essentially, you should subclass activities that you want to customize so the changes can persist even after updating the Chat SDK.
