### ISSUE TITLE
Private group not available after clone

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#257]
@bensmiley I cloned the git repo but couldn't able to find the Private Group message tab as you mentioned in the doc.

 @bensmiley @alexsdi @itzikBraun Any update ? 
3/4/2018 @bensmiley @itzikBraun @pepebecker @alexsdi Any update ?
5/4/2018 @bensmiley @itzikBraun @pepebecker @alexsdi Any update regarding private group chat?
6/4/2018 @bensmiley @itzikBraun @pepebecker @alexsdi Any update regarding private group chat?

**Comment by bensmiley** [comment]
Could you post a screenshot of what you mean? There should be the tabs - private messages, public chats, contacts, profile.

**Comment by rahulsharmagbpec** [comment]
Am not talking about private messages am talking about Private group(group with limited members).

**Comment by bensmiley** [comment]
Private groups appear in the same place as private 1-to-1 conversations. You can create one by creating a new conversation and adding multiple people.

**Comment by bensmiley** [comment]
1. First make sure that you have more than one contact
2. Click contacts -> + -> Search for contacts
3. Select and add the contacts
4. Click conversations -> + -> Pick friends
5. Select multiple people
6. Click start chat.

**Comment by rahulsharmagbpec** [comment]
yeah got it thanks,
