### ISSUE TITLE
Changing profile picture does not work.

### ISSUE THREAD

**Issue by dreimanis** [chat-sdk/chat-sdk-android#261]
Changing profile picture does not work.
It updated the wrong link on firebase. 
pictureURL is "file:///storage/emulated/0/Android/data/co.chats.." It saves the local adress for the image, it changes the image only for me, others can't see it.
![image](https://user-images.githubusercontent.com/1484602/38491729-65f123d8-3bf5-11e8-9a26-fcf831817f59.png)
It should be something like this, like it works from iOS. 
pictureURL: "https://firebasestorage.googleapis.com/v0/b/chem..."
![image](https://user-images.githubusercontent.com/1484602/38491774-8465c62a-3bf5-11e8-8d42-a9c698d5c2f4.png)

**Comment by dreimanis** [comment]
In EditProfileActivity there is a TODO,   // TODO: Add this in for Firebase maybe move this to push user...
I guess it has never been finished.

**Comment by bensmiley** [comment]
Fixed in 4.0.10.
