### ISSUE TITLE
created my own MyChatActivity but how to update layout and list design

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#264]
Hello @bensmiley , i have issue while adding new custom layout
1. I made a clone of chat-sdk
2. Created my new Project and added android chat-sdk modules.
3. Createed my own "MyBaseInterface which is extending BaseInterfaceAdapter
    and returning my custom activity like
     @Override
    public Class getChatActivity() {
        return MyChatActivity.class;
    }
4.  now the problem is i want to pass my own layout to chat activity with my own colors and images 
    same thing i wants to do with list. that am not getting how to do
5. wants to update chat_sdk_row_message_me.xml, chat_sdk_row_message_reply.xml without interfering the chat-sdk-project... from my project i want to do something... so that i can merge the latest code to chat-sdk-project whenever the update will come.

**Comment by rahulsharmagbpec** [comment]
@alexsdi @bensmiley @itzikBraun @pepebecker Can some one help me please

**Comment by bensmiley** [comment]
@rahulsharmagbpec The best way to do this is to copy any of the xml layout files you want to modify into your main project. For example - copy the `chat_sdk_row_message_me.xml` file and rename it `your_project_row_message_me.xml`. Then you will need to override the class that uses this file. In your case, first subclass the `ChatActivity` then subclass the `MessageListAdapter`. In your subclass of the `ChatActivity` use your `MessageListAdapter` subclass.  Then in the `MessageListAdapter` subclass override the `onCreaetViewHolder` method and make it use your own XML file. Using this technique you can modify any class or layout in the framework.
