### ISSUE TITLE
how to integrate with a prebuit firebase auth and create private reusable thread ?

### ISSUE THREAD

**Issue by aymenhs** [chat-sdk/chat-sdk-android#265]
Very interesting and robust modules ,but using separately is not obvious.
We read the documentation, and didn't find how to make the next scenario (commonone).
 Can you explain please? thanks

scenario:
We want to make group chats(different topics) triggred from a click on an entry list within our application. For example: Sports=> click to access group chat about sport, photography=> another one ... Each topic has an owner who select users for each thread.
We use firebase authentification (https://firebase.google.com/docs/auth/android/firebaseui ) and not the chat-sdk-ui interface.

questions:
1- We didn't found how to pass to chat SDK the token/ email received when authenticating with firebase pre built interface. The chat sdk allows only to pass username/password ,or custom token.  Is it possible to do such integration with a third party firebase auth system ?Should we just use Firebase UI ?
There're in the doc the following:
```
AccountDetails details = username("some.email@domain.com", "some password");
NM.auth().authenticate(details).subscribe();
```
and we didn't find something like this: 
`AccountDetails details = firebasetoken("token we got from firebase after authentication");
`

2-After being authenticated, we didn't found how to reuse already created private threads (sports,walking) and reuse them with selected users.
`There're: NM.thread().createThread("sports", user1, user2, user3...)`
and did not find something like this :
`NM.thread().LaunchThread("sports")`

We really wants to integrate chat sdk to our app but lack how to do such simple integration (our authentication with firebase, and just create reused threads)

thanks a lot

**Comment by bensmiley** [comment]
@aymenhs If you want a predefined list of threads that will be available to all users, you can do this using the following method:

```
NM.publicThread().createPublicThreadWithName("Name", "Thread ID").subscribe(...;
```

This will create a new thread with a given entity ID. For example, in your app you could have a predefined list of topics and when the client starts, you would create these threads. 

I would recommend using public threads for this kind of situation but if you want to use private threads you can use the following:

```
NM.thread().createThread("Name", users, ThreadType.PrivateGroup, "Thread Unique ID");
```

The main difference is that anyone can join a public thread whereas, for a private thread, only members who have their ID stored in the thread's user list can participate. To use the method above, you will also need to update to version 4.0.15.

Can you explain what you mean when you say you want to authenticate with a third party auth system? If you have already authenticated with Firebase elsewhere in your app, you can just call:

```
NM.auth().authenticateWithCachedToken().subscribe();
```

Thanks,

Ben

**Comment by aymenhs** [comment]
hello,
thank you Ben , I succeeded to make it work ! I'm sure those information will be useful to many others.
I used 
NM.thread().createThread("Optional Name", users, ThreadType.PrivateGroup)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(new Consumer<Thread>() ;
