### ISSUE TITLE
Issue with notification sound

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-android#273]
Not sure if this is an isolated issue resulting from my setup, but trying to confirm notification sound seems to stop the notifications coming, silent ones work. iOS to iOS plays the sound on the iOS recipient, but those sent from android come through to iOS silently.

**Comment by thecmart** [comment]
@snipe717 There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.
