### ISSUE TITLE
URGENT, tapping the notification to enter the app does not update thread

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-android#275]
Opening the app via a tap on the notification, opens the app but does not refresh the chat.

**Comment by agustinsivoplas** [comment]
I have a similar problem. The refresh occurs but take at least 5 or 6 seconds. @himanshubhaisare

**Comment by thecmart** [comment]
@snipe717 @agustinsivoplas There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.
