### ISSUE TITLE
getting error with latest version of library 4.0.20

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#276]
Getting error after updating to to the latest version 
![image](https://user-images.githubusercontent.com/32955380/39405996-43ee54e4-4bcd-11e8-8206-fbd6992d0f64.png)

**Comment by ggcarmi** [comment]
i got the same error
do you found a solution?

**Comment by myeduapp** [comment]
@ggcarmi No I am still getting same error.

**Comment by bensmiley** [comment]
Could you try updating to 4.0.26?

**Comment by thecmart** [comment]
@myeduapp We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.
