### ISSUE TITLE
Tap to type not auto capitalising and adding punctuation

### ISSUE THREAD

**Issue by snipe717** [chat-sdk/chat-sdk-android#277]
I’ve been informed that using swipe works fine, but whilst tap typing, auto capitalisation and punctuation is not working as it does in other apps. I find this strange as that ought to be down to the individual keyboard not the app? Am I correct? Just thought I’d mention it as it was feedback I received.

**Comment by thecmart** [comment]
@snipe717 We could not reproduce this problem in the newest version of Chat SDK, so we will close this issue. If the issue persists, please re-open it.
