### ISSUE TITLE
DisablePrivateThread from configuration builder

### ISSUE THREAD

**Issue by mdmiko** [chat-sdk/chat-sdk-android#278]
I done some subclasses to disable private messaging.
Override this "public List<Tab> defaultTabs()" in "BaseInterfaceAdapter"
And doing a custom mainActivity
It need to be disabled from user profile layout

this could be a future configuration?

**Comment by thecmart** [comment]
@mdmiko There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.
