### ISSUE TITLE
set meta value to thread

### ISSUE THREAD

**Issue by vcanovas** [chat-sdk/chat-sdk-android#284]
Hello everyone,
I'm trying to set meta data to a thread and sync with firebase bbdd:

`thread.setMetaValue("url-image", "https://es.freelogodesign.org/img/logo-ex-7.png");
ThreadWrapper threadWrapper = new ThreadWrapper(thread);

threadWrapper.pushMeta();`

In my internal bbdd, the metadata exist, but not in the firebase cloud

**Comment by bensmiley** [comment]
HI @vcanovas I think you need to call this:
```
threadWrapper.pushMeta().subscribe();
```
Otherwise the function will never be executed.

**Comment by vcanovas** [comment]
thank you so much ben, it's correct!!!
