### ISSUE TITLE
Multiple thread created with a same user

### ISSUE THREAD

**Issue by avinath321** [chat-sdk/chat-sdk-android#287]
On slow network connection multiple threads are created for the same user
![device-2018-06-01-183638](https://user-images.githubusercontent.com/33277954/40842299-0ede85a4-65cb-11e8-9d1f-ac58dd117fdb.png)

**Comment by akashnits** [comment]
@bensmiley Hi Ben, I'm facing the same issue on slower network. On creating private thread, users (added to this private thread) are not inserted properly in UserThreadLink table which results in creation of multiple threads (new private thread is created everytime instead returning a private thread)

**Comment by thecmart** [comment]
@avinath321 There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.
