### ISSUE TITLE
Firebase root path

### ISSUE THREAD

**Issue by nowantednameisavailabel** [chat-sdk/chat-sdk-android#29]
During testing you could set the root path to test and then when you go live, you could change it to live.
Can you please explain this point? What should i set my root path? @kykrueger  @bensmiley  @simonsmiley64

**Comment by simonsmiley64** [comment]
Hi,

The root path is used to split your database up into different parts. Setting a two different root paths creates two different branches of information.

You can see from the screenshot below what I mean. This is a screenshot from a single Firebase database: https://chat-sdk-v4.firebaseio.com/

If you add the `firebase_v4_local` root path you will be able to access the first database. `firebase_v4_local_test` will allow you to access the second one. Hopefully you can see that both sides of the database are completely separate. A user from one can't talk to a user in another.

![screen shot 2017-03-03 at 09 39 37](https://cloud.githubusercontent.com/assets/8721425/23530340/5d725688-fff5-11e6-9834-0c533be79c26.png)

This is very important while testing. If you want to test new features you don't want to be using your live database. 

+ Don't want lots of fake users appearing in your app
+ Don't want bugs to appear in your live database
+ Want to be able to change database attributes without affecting your current service.

Using the example above we could use one of the root paths for the live project and one for new features being tested. We could clone the data from the live one to the test one and then perform tests and this wouldn't have any impact on the live data.

This is what we mean by setting `live` and `test`. Using it you can create a new area of the database to try new things. The screenshot below gives you an example of this, on our test firebase paths we create a new root path for each new project meaning we can only have a single app but can reuse it for lots of individual projects:

![screen shot 2017-03-03 at 09 45 12](https://cloud.githubusercontent.com/assets/8721425/23530527/22d62738-fff6-11e6-9623-1168db22d089.png)
