### ISSUE TITLE
Error: Failed to resolve country-picker-android

### ISSUE THREAD

**Issue by rajatmurdeshwar** [chat-sdk/chat-sdk-android#290]
After adding 'co.chatsdk.chatsdk:chat-sdk-ui:4.0.26' to dependecy I'm getting "Error:Failed to resolve: com.github.mukeshsolanki:country-picker-android:1.1.9 "

**Comment by bhatiaravi** [comment]
Make sure in your root level build.gradle you have added the following additional repositories:
**allprojects** {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        **// Additonal entries required for Chat SDK
        maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
        maven { url "https://jitpack.io" }**
    }
.....
}
