### ISSUE TITLE
Failed to resolve dependencies

### ISSUE THREAD

**Issue by carloscj6** [chat-sdk/chat-sdk-android#291]
I get an error of failed to resolve all the depedencies below. help me out pls. I have correctly done all the other procedures. 
_I am using the Latest version of android studio_
`dependencies {
   
    implementation 'com.github.mukeshsolanki:country-picker-android:1.1.9'
    implementation 'com.google.firebase:firebase-messaging:10.2.1'
    implementation 'com.google.android.gms:play-services:4.0.1'
    implementation 'com.google.android.gms:play-services:4.0.1'
    implementation 'com.google.firebase:firebase-storage:4.0.1'
    implementation 'com.google.android.gms:play-services:4.0.1'
}`

**Comment by thecmart** [comment]
@carloscj6 There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue. The Chat SDK internal Implementations have all been updated. For those that are not, you can move your mouse over the individual implementations and see if they need to be updated. If some of the non Chat SDK native implementations are a problem, you would need to consult the owners of those projects with regards to the implementations not working.
