### ISSUE TITLE
Private & Public Thread List Empty for the First Time using Firebase Module

### ISSUE THREAD

**Issue by Thamizhan** [chat-sdk/chat-sdk-android#292]
I setup the project with one of my application, I have not made any changes in the functionality of the SDK Just changed the UI little bit. 

I have an issues. 

When I uninstall the app completely and re install again, earlier chat list in both Private and Public threads are not syncing. I was even thinking that the threads are syncing and waited for few mins, but the list not yet updated.

I extracted the database file inside the app folder and opened with DB editor. All tables are empty no data is synced.

However when I close the app completely then reopen all earlier threads are appeared and database is updated.

I checked with all my of testing devices, this happens in all devices.  Below are the details of my application

`
minSdkVersion 23
targetSdkVersion 27
multiDexEnabled true
`

I initiated ChatSDK in onCreate method of Application class
`
// Create a new configuration
        Configuration.Builder builder = new Configuration.Builder(context);

        // Perform any configuration steps (optional)
        builder.firebaseRootPath(getString(R.string.firebase_root_path));

        builder.firebaseStorageURL(getString(R.string.firebase_storage_url));
        builder.googleMaps(getString(R.string.google_places_api_key));

        // Initialize the Chat SDK
        ChatSDK.initialize(builder.build());
        UserInterfaceModule.activate(context);

        // Activate the Firebase module
        FirebaseModule.activate();

        FirebasePushModule.activateForFirebase();
        builder.firebase(getString(R.string.firebase_root_path), getString(R.string.firebase_cloud_messaging_server_key));

        // File storage is needed for profile image upload and image messages
        FirebaseFileStorageModule.activate();
`

And to open the chat SDK screen

`
AppBackgroundMonitor.shared().setEnabled(true);
        InterfaceManager.shared().a.startMainActivity(this);
`

**Comment by thecmart** [comment]
@Thamizhan There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.

**Comment by anonym24** [comment]
@thecmart this issue still happens in 5.0.16 https://github.com/chat-sdk/chat-sdk-android/issues/666
