### ISSUE TITLE
Location Picker Not Opening Sometimes

### ISSUE THREAD

**Issue by Thamizhan** [chat-sdk/chat-sdk-android#293]
Google Places Location Picker activity is not opening sometimes.  It happens after few times sending location per launch.

I also checked and debugged the code `startChooseLocationActivity` method in `LocationSelector` is executing without any error or exception when Location picker not showing up.

I also setup the Google API keys correctly in Manifest file and Configuration builder, it cannot be the problem because after every launch of the app it woks for few time after that only Picker not showing up.

I checked with all my of testing devices, this happens in all devices.  Below are the details of my application

`
minSdkVersion 23
targetSdkVersion 27
multiDexEnabled true
`

I initiated ChatSDK in onCreate method of Application class
`
// Create a new configuration
        Configuration.Builder builder = new Configuration.Builder(context);

        // Perform any configuration steps (optional)
        builder.firebaseRootPath(getString(R.string.firebase_root_path));

        builder.firebaseStorageURL(getString(R.string.firebase_storage_url));
        builder.googleMaps(getString(R.string.google_places_api_key));

        // Initialize the Chat SDK
        ChatSDK.initialize(builder.build());
        UserInterfaceModule.activate(context);

        // Activate the Firebase module
        FirebaseModule.activate();

        FirebasePushModule.activateForFirebase();
        builder.firebase(getString(R.string.firebase_root_path), getString(R.string.firebase_cloud_messaging_server_key));

        // File storage is needed for profile image upload and image messages
        FirebaseFileStorageModule.activate();
`

And to open the chat SDK screen

`
AppBackgroundMonitor.shared().setEnabled(true);
        InterfaceManager.shared().a.startMainActivity(this);
`

**Comment by bensmiley** [comment]
This happens when the Google Places API hasn't been enabled from the Google Places dashboard.
