### ISSUE TITLE
onResume getting called two times in ChatActivity

### ISSUE THREAD

**Issue by anbarasu-seven** [chat-sdk/chat-sdk-android#296]
Hi, I have added chat sdk as module in one of the project that i have currently working on, when I click on thread it is going to ChatActivity, there we listed all  the conversation between diff profile. At first am getting ConcurrentModificationException in thread.update() method in ChatActivity. After i noticed this is because of onResume() getting called 2 times. Is this the sdk issue or android sdk itself having issue with onResume() method. can anyone help me to fix this issue.

**Comment by thecmart** [comment]
@anbarasu-seven There have been many modifications made to the app over the past few months. If this problem still persists in the newest version of Chat SDK, please re-open this issue.
