### ISSUE TITLE
Confused on User.deleteContact 

### ISSUE THREAD

**Issue by CHXAIOGE** [chat-sdk/chat-sdk-android#301]
Hi, I'm reviewing code and notice function "deleteContact " in User.java 
I'm confused on the code .
  
    public void deleteContact (User user, ConnectionType type) {
        // For some reason the default ContactLinks do not persist, have to find in DB
        Property [] properties = {
                ContactLinkDao.Properties.LinkOwnerUserDaoId,
                ContactLinkDao.Properties.Type
        };

        List<ContactLink> contactLinks = DaoCore.fetchEntitiesWithProperties(ContactLink.class,
                properties, this.getId(), type.ordinal());

        for(ContactLink link : contactLinks) {
            if(link.getUser().equals(user)) {
                DaoCore.deleteEntity(link);
            }
        }
        daoSession.update(this);
    }

Can any one tells me why do I have to getUser() and call equals? 
What is that used for, stash user entity for any usage? 
Can I just look up into database with properties below?
       
        Property [] properties = {
                ContactLinkDao.Properties.LinkOwnerUserDaoId,
                ContactLinkDao.Properties.UserId,
                ContactLinkDao.Properties.Type
        };

        List<ContactLink> contactLinks = DaoCore.fetchEntitiesWithProperties(ContactLink.class,
                properties, this.getId(), user.getId(), type.ordinal());

and just call "DaoCore.deleteEntity(link);" for better performance?

        for(ContactLink link : contactLinks) {
                DaoCore.deleteEntity(link);
        }

**Comment by bensmiley** [comment]
@CHXAIOGE There is no reason why we couldn't use that code and yes, it is more efficient. I've updated the core project and I'll release it today v4.0.21. If you see similar fixes in the future feel free to submit a pull request.
