### ISSUE TITLE
Redundant rule

### ISSUE THREAD

**Issue by Yrlec** [chat-sdk/chat-sdk-android#305]
Thanks for creating a great chat library!

I found a line the Firebase rules that looks incorrect:

` ".read": "data.child(auth.uid).exists() || !data.child(auth.uid).exists()", `

That line will always be true so I'm assuming something is wrong with it. What should it be instead?

**Comment by thecmart** [comment]
@Yrlec This is not an actual bug. I am not currently sure if this rule was written for a specific reason or not, given the many changes that our staff have made to the Program over the past few months. If it seems redundant then you can delete it in your Firebase account and run the App as you see fit. If the line creates a specific problem for you then please re-open the issue.
