### ISSUE TITLE
How add contact

### ISSUE THREAD

**Issue by davisoqt** [chat-sdk/chat-sdk-android#307]
Hi, i have compiled the sample chat app and integrate it with my firebase project. But i can add or find any contact. always return "no match found". any suggestion...

**Comment by bensmiley** [comment]
Hi, @davisoqt There are a number of possible reasons for this:
1. Can you make sure you've added the Firebase security rules
2. After your user has logged in, are you running `NM.auth().authenticateWithCachedToken().subscribe()`
3. Can you check that users are being created in Firebase
4. The search is case sensitive so you need to write the user's exact name
If none of these work, please let me know.

**Comment by BendiRKO** [comment]
Hi @bensmiley I can confirm that it doesn't work for me too, and none of those reasons don't work

**Comment by bensmiley** [comment]
@BendiRKO Are you saying that you are calling the code in line 2 and that no data is being added to Firebase? 

Are there any error messages? Have you performed the necessary Chat SDK setup and configuration steps in the application start method?

**Comment by BendiRKO** [comment]
Yes, there are no error messages or anything
