### ISSUE TITLE
What does the "lastUpdated" mean in User Table?

### ISSUE THREAD

**Issue by CHXAIOGE** [chat-sdk/chat-sdk-android#309]
Hi, 
I'm reading the code and find a column named "lastUpdated" in User table. But I don't know what does it really means. So , I'm a litte bit confused at it.
Can anyone tells me how it works and what it used for? thanks!

**Comment by bensmiley** [comment]
@CHXAIOGE This is a legacy field which isn't needed anymore. It has been removed as of version 4.2.3.
