### ISSUE TITLE
How to add Modules?

### ISSUE THREAD

**Issue by LNMayank** [chat-sdk/chat-sdk-android#31]
How to access below Modules? Is it below module possible with fire base?

Typing indicator
Read receipts
Location based chat
Audio messages
Video messages
Push notifications

**Comment by simonsmiley64** [comment]
All of those modules are possible. 

Push notifications come ready set up for the Android project.

The other modules are available but need to be purchased. These modules are all available on both iOS and Android. You can check out further details for them [here](http://chatsdk.co/modules-2/) on our website.
