### ISSUE TITLE
V. 4.1.0 old apis - Build failed

### ISSUE THREAD

**Issue by eakteam** [chat-sdk/chat-sdk-android#311]
```
Failed to notify dependency resolution listener.
The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[15.0.2,15.0.2], [16.0.0,16.0.0]], but resolves to 16.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```
`The library com.google.firebase:firebase-iid is being requested by various other libraries at [[16.2.0,16.2.0]], but resolves to 16.0.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.`

**Comment by eakteam** [comment]
I think that gradle.properties should be removed and use static version lib for every build.gradle modules ...
For example : 
In sdk-core

```
api 'com.google.android.gms:play-services-auth:' + project.GOOGLE_SERVICES_VERSION
api 'com.google.android.gms:play-services-maps:' + project.GOOGLE_SERVICES_VERSION
```

TO : 

```
api 'com.google.android.gms:play-services-auth:15.0.1'
api 'com.google.android.gms:play-services-maps:15.0.1'
```

In chat-sdk-ui : 
From 

`api "com.google.android.gms:play-services-places:" + project.GOOGLE_SERVICES_VERSION`

TO : 

`api "com.google.android.gms:play-services-places:15.0.1"`

firebase-adapter : 

```
firebase-core:16.0.0
firebase-auth:16.0.1
```

to 

```
firebase-core:16.0.1
firebase-auth:16.0.2

```

Remove `buildToolsVersion project.ANDROID_BUILD_TOOLS_VERSION` from all build.gradle modules it is not anymore required

**Comment by bensmiley** [comment]
@eakteam all of your suggestions have been implemented. Check out build 4.1.1.

**Comment by mohyazji** [comment]
I get the same error on v.4.3.6 and this should be update 

In sdk-core :
api 'com.google.android.gms:play-services-auth:16.0.1'
api 'com.google.android.gms:play-services-maps:16.0.0'

chat-sdk-ui : 
api 'com.google.android.gms:play-services-places:16.0.0'

@bensmiley
