### ISSUE TITLE
In the latest version 4.1.2 some classes and methods are missing

### ISSUE THREAD

**Issue by eakteam** [chat-sdk/chat-sdk-android#313]
Cannot import this class : 
`import co.chatsdk.firebase.wrappers.ThreadWrapper;`

and in `FirebaseThreadHandler` this method doesn't exist too : 

`ChatSDK.config().pushNotificationsForPublicChatRoomsEnabled)`

**Comment by bensmiley** [comment]
@eakteam I'm having a bit of trouble understanding this issue. When you say you can't import the thread wrapper? Have you added a dependency to the Firebase Adapter module? If you have, it should be available. It is available in my project. 

Also, the method `pushNotificationsForPublicChatRoomsEnabled` is not available yet. It is in a pull request that will be merged this week.

**Comment by eakteam** [comment]
Thank you.
