### ISSUE TITLE
How to open same thread between 2 users programatically

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#314]

**Comment by myeduapp** [comment]
@bensmiley Please help me on this.

**Comment by bensmiley** [comment]
@myeduapp You could use this guide: [https://github.com/chat-sdk/docs#creating-a-private-thread]( https://github.com/chat-sdk/docs#creating-a-private-thread). I hope that helps.

**Comment by myeduapp** [comment]
@bensmiley The link only shows how to create a thread. I want to open chat between 2 users. If there is already communication between 2 users then it should open the particular chat otherwise create new chat. It seems that fetchuserswithentityid method is having some issues as it is returning null value even if user is present in firebase console
Please help me on these issues.

**Comment by myeduapp** [comment]
@bensmiley Could you please explain it in detail?
