### ISSUE TITLE
Possibility to manipulate text before send

### ISSUE THREAD

**Issue by eakteam** [chat-sdk/chat-sdk-android#316]
Hello there, i wonder if can write a listener or broadcast receiver to get the text message before sent to firebase, manipulate it (e.x encrypt) and after that send it encrypted...
It's better to make something like this than to modify the library ourself
Best Regards

**Comment by bensmiley** [comment]
Yes, when you send the message you can check the status:

```
        Disposable d = ChatSDK.thread().sendMessageWithText(message, thread).subscribe(messageSendProgress -> {

        }, throwable -> {

        });
```

Then use `message.getMessageStatus()`. You could intercept it at the `Sending` status. To listen for when a message is received you could use:

```
        ChatSDK.hook().addHook(new Hook(data -> Completable.create(emitter -> {
            Message message = (Message) data.get(HookEvent.Message);
            emitter.onComplete();
        })), HookEvent.MessageReceived);
```

If you want a global even for message sending, you could add a new hook call and submit a pull request and we will merge it with the core library.
