### ISSUE TITLE
Authentication from firebase taking too much time

### ISSUE THREAD

**Issue by ajay32** [chat-sdk/chat-sdk-android#319]

**Comment by HasnainAD** [comment]
I am facing same issue. Credentials are stored in firebase and are showing in authentication users in firebase console but response doesn't appear to work in code.

**Comment by bensmiley** [comment]
@HasnainAD Could you try checking out the default version of the project and testing it. Does this still happen? Also, where are you based geographically? And how is your internet connection?

**Comment by HasnainAD** [comment]
@bensmiley I am located in Pakistan and my Internet connection is fine. This happens for both register and login. When registering, the account is created in Firebase but the disposable never ends, nor does it gives any error. Then I tried registering and logging in using vanilla Firebase as mentioned [here](https://firebase.google.com/docs/auth/android/custom-auth) and its working fine.
Following code in authenticateWithDetails (AccountDetails details) is not working.

`ChatSDK.auth().authenticate(details)
                .observeOn(AndroidSchedulers.mainThread())
                .doFinally(() -> {//not runnning
                    log("doFinally()");
                   
                    authenticating = false;
                    dismissProgressDialog();
                })
                .subscribe(this::afterLogin, e -> {
                    log("subscribe(this::afterLogin)"); //not running

                    toastErrorMessage(e, false);
                    ChatSDK.logError(e);
                });`

Is it possible that we implement custom registration and login to Firebase?

**Comment by bensmiley** [comment]
Ok, it would be helpful if you downloaded the [demo version](https://i.diawi.com/VKRnbm) of the project onto your phone using this link and test the signup. If it works fine then we would know that this is a setup issue in your project. Otherwise, we would know it was something to do with Firebase.

**Comment by HasnainAD** [comment]
Okay I will let you know what happens with it.

**Comment by HasnainAD** [comment]
The demo app is working. I am using modules manually and changing nothing except some logs in LoginActivity. I am correctly following the docs.

**Comment by bensmiley** [comment]
Ok, that means that it's probably an issue with the app's configuration. Have you enabled email/password login from the dashboard? Can you confirm that you've correctly setup the Google Services.JSON and the Firebase rules? Also the file upload module and enabled Firebase Storage?

**Comment by bensmiley** [comment]
That's strange. Which locality have you chosen for the Firebase realtime database?

**Comment by HasnainAD** [comment]
I am haven't initialized Firebase realtime database yet. But I started the project itself using US locality..

**Comment by shahawi** [comment]
Sir the realtime database stores user information you have to initialize it and set security rules

**Comment by HasnainAD** [comment]
@shahawi Would it be possible for  you to post a snippet of database initialization code?
