### ISSUE TITLE
Uploading chat apk to Google play

### ISSUE THREAD

**Issue by Roboconsole** [chat-sdk/chat-sdk-android#32]
Hello, i've made my chat apk, signed it and all but when i put the app on google play it says i violate the term of policy  because of WebViewClient.onReceivedSslError and sais vurnable categories com.backendless.SocialAsyncCallback$1 :/ Hope you help :) Tnx for the nice sdk btw :D

**Comment by kykrueger** [comment]
Hello @Roboconsole ,

This vulnerable class is part of the libraries we use for our push notifications. If you are not using the push notifications, you can remove Backendless from the project. After doing that it should be safe to submit to google play. 

If you are using Backendless, stay tuned. I am updating our the version of their SDK that we use to the latest. Hopefully that resolves the issue. 

-- Kyle

**Comment by kykrueger** [comment]
Or, you can download the latest [Backendless SDK for Android](https://backendless.com/downloads/) if you are in a hurry.

**Comment by kykrueger** [comment]
The issue should have been fixed in #38 . Closing the thread.

It was a [known problem ](http://support.backendless.com/topic/app-has-received-warning-about-onreceivedsslerror)and had been patched by Backendless.
