### ISSUE TITLE
Not able to receive any message using xmpp adapter in  android

### ISSUE THREAD

**Issue by developer20atmoderni** [chat-sdk/chat-sdk-android#321]
I have integrated the xmpp adapter in my existing project. I have opened the private thread of two users which are online. they are sending the messages, but not receiving any messages . Am I missing something in this case? I am not able to see any incoming message in the following code

`Disposable d = NM.events().sourceOnMain()
        .filter(NetworkEvent.filterType(EventType.MessageAdded))
        .subscribe(new Consumer<NetworkEvent>() {
            @Override
            public void accept(NetworkEvent networkEvent) throws Exception {
                Message message = networkEvent.message;
            }
        });`

**Comment by bensmiley** [comment]
Please update to 4.7.1. This issue should be resolved.
