### ISSUE TITLE
Chat SDK + Firebase Messaging

### ISSUE THREAD

**Issue by anitoledo** [chat-sdk/chat-sdk-android#322]
I'm using firebase messaging for suscribe/unsusbscribe topics on my appand send push notifications. I want to add Chat SDK to my project but I'm getting this error after adding the dependencies 
    ```
compile 'co.chatsdk.chatsdk:chat-sdk-core:4.1.7'
    compile 'co.chatsdk.chatsdk:chat-sdk-ui:4.1.7'
    compile 'co.chatsdk.chatsdk:chat-sdk-firebase-adapter:4.1.7'
    compile 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.1.7'
```

`Error:(21, 1) Class 'MyFirebaseMessagingService' is not abstract and does not implement abstract base class member public abstract fun zzd(p0: Intent!): Unit defined in com.google.firebase.messaging.FirebaseMessagingService`

If I delete the dependencies then it works. I tried to change the google services version and the firbase version but I'm always getting that error.

**Comment by bensmiley** [comment]
Can you post details of your `MyFirebaseMessagingService` class?

**Comment by gajicm93** [comment]
Hi, what happened to this? I'm not having a specific issue, I'm still evaluating the usability of this library for integration with existing project, but I'm wondering how does Chat SDK work with existing FirebaseMessagingService that I'm already using in a project?

I believe this to be a common use case. Thanks. @bensmiley @thecmart

**Comment by bensmiley** [comment]
Hi @gajicm93,

The project has a dependency on FirebaseMessaging so as long as there isn't a conflict between the versions of the Gradle versions I think there wouldn't be any problem. 

The best thing to do would be to just add the Chat SDK dependency to your project and see if you have an issue.
