### ISSUE TITLE
Audio message not compatible with Android?

### ISSUE THREAD

**Issue by SimplisticApps** [chat-sdk/chat-sdk-android#33]
So I've just spent over £80 for the Audio Message module but i can even use it with android despite saying i can? Is there something I'm missing or do you not actually support the module for android yet?

**Comment by bensmiley** [comment]
Hi, currently the Android upgrade isn't automatic. I'll be able to send you the source code for the audio message module tomorrow morning.

Thanks,

Ben

**Comment by SimplisticApps** [comment]
Ah brilliant! Thank you.

**Comment by simonsmiley64** [comment]
Hi @SimplisticApps,

I have sent you an email containing a download link for the Chat SDK containing audio messages. 

If you have any issues you can either create an issue here or email me directly.

Simon
