### ISSUE TITLE
No method to get user by email

### ISSUE THREAD

**Issue by AAPBD** [chat-sdk/chat-sdk-android#331]
Hi, 

I have added ChatSDK into our project. But didn't get any method to retrieve the user from the firebase using email address.

User can be retrieved using entityID.

Is it possible to provide any method to get user by email id?

**Comment by bensmiley** [comment]
@AAPBD To do this you would need to use the Search API. If the user has set their email (because they can delete it on their user profile) you can get the user like this:

```
ChatSDK.search().usersForIndex("test@email.com", "email").subscribe(user -> {
    // Handle User
}, throwable -> {
    // Handle Error
});
```

**Comment by AAPBD** [comment]
No, this solution isn't effective. Look at following code. It's returning two objects while Email is Unique.

08-30 23:34:23.453 7447-7447/com.zwenex.emyanMR E/firebasesearchhandler: value 4doctor@z-waka.com index email
08-30 23:34:23.454 7447-7447/com.zwenex.emyanMR E/Disposable at search: 0
08-30 23:34:24.090 7447-7447/com.zwenex.emyanMR E/AppConstant: onNext at search
08-30 23:34:24.091 7447-7447/com.zwenex.emyanMR E/AppConstant search: User, id: 25 meta: {pictureURL=http://api.z-waka.com/images/uploads/profile/33bf3ea8-729a-4f54-bbdd-52dda472592e.JPG, name=Hla Hla Win, email=4doctor@z-waka.com}
08-30 23:34:24.394 7447-7447/com.zwenex.emyanMR E/AppConstant: onNext at search
08-30 23:34:24.394 7447-7447/com.zwenex.emyanMR E/AppConstant search: User, id: 23 meta: {pictureURL=http://api.z-waka.com/images/uploads/profile/149a64dd-b38c-4697-baf7-5c8eb0515fc1.jpg, name=Khin Khin, email=54doctor@z-waka.com}
08-30 23:34:24.396 7447-7447/com.zwenex.emyanMR E/AppConstant search: onComplete

**Comment by bensmiley** [comment]
@AAPBD Could you check with the latest version? You could then use the API: 

```
ChatSDK.search().usersForIndex("test@email.com", 1, "email").subscribe(user -> {
    // Handle User
}, throwable -> {
    // Handle Error
});
```

**Comment by MuhammadSulaiman001** [comment]
@bensmiley Would you please check this code snippet.. it never gets into onSuccess neither onError, it goes immediately into onComplete.. whats wrong here?

```
val d = ChatSDK.search().usersForIndex(email, 1, Keys.Email)
              .observeOn(AndroidSchedulers.mainThread())
              .subscribe({ user -> 
                  
              }, {  throwable ->
                  
              }, {
                 // log no users found
              })
dm.add(d)
```
