### ISSUE TITLE
Modules not Importing

### ISSUE THREAD

**Issue by Ankit7791** [chat-sdk/chat-sdk-android#348]
Project with path ':chat-sdk-core' could not be found in project ':chat-sdk-firebase-file-storage'.

**Comment by HasnainAD** [comment]
Do this in your settings.gradle 
include ':app', ':chat-sdk-core', ':chat-sdk-firebase-file-storage',
        ':chat-sdk-firebase-adapter', ':chat-sdk-firebase-ui',
         ':chat-sdk-ui'

If the issue continues, try "Invalidate Cache/Restart" from file menu.
