### ISSUE TITLE
Failed to resolve: com.github.mukeshsolanki:country-picker-android:1.2.4

### ISSUE THREAD

**Issue by Ankit7791** [chat-sdk/chat-sdk-android#349]
Failed to resolve: com.github.mukeshsolanki:country-picker-android:1.2.4
Failed to resolve: com.github.chrisbanes:PhotoView:2.1.4

**Comment by HasnainAD** [comment]
Go to root gradle file and include these files  
```
        maven { url "https://jitpack.io" }
        maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
        maven { url "https://maven.google.com" }
```
in allprojects->repositories not buildscript -> repositories
