### ISSUE TITLE
How to disable Notification

### ISSUE THREAD

**Issue by KAPLANDROID** [chat-sdk/chat-sdk-android#350]
Hi,

I have a custom chat activity which i replace sdk's ChatActivity.java. When an other user sends message push notification appears at top. Also when user kills application and an other user sends message SDK side does not show push notification in notification bar until user opens application. When application open waiting push messages shown in notification bar.

Thanks

**Comment by bensmiley** [comment]
This seems to be an issue with push notifications not setup correctly.
