### ISSUE TITLE
private group with no message not visible in list

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#356]
@bensmiley @itzikBraun @pepebecker @Mithrandir21 I created a new Private group with some member and in ChatActivity i pressed back, now this group name is not visible in chatList what to do to resolve this ?

**Comment by rahulsharmagbpec** [comment]
@bensmiley @itzikBraun @pepebecker @Mithrandir21 @himanshubhaisare 
Any update ??

**Comment by rahulsharmagbpec** [comment]
@bensmiley @itzikBraun @pepebecker @Mithrandir21 @himanshubhaisare 
Any update ??

**Comment by bensmiley** [comment]
This has been resolved.
