### ISSUE TITLE
Failed to resolve: com.github.shrikanth7698:Custom-Navigation-Drawer:v0.0.1

### ISSUE THREAD

**Issue by shubhamtunwal97** [chat-sdk/chat-sdk-android#357]
After adding it to the gradle (app) and 

`        maven { url 'https://jitpack.io' }
`
to grade(project) this is coming

Failed to resolve: com.github.shrikanth7698:Custom-Navigation-Drawer:v0.0.1
Show in File
Show in Project Structure dialog

**Comment by thecmart** [comment]
@shubhamtunwal97 We have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.

**Comment by buntygoswami** [comment]
ERROR: Failed to resolve: com.github.shrikanth7698:ChatView:v0.1.2
Show in Project Structure dialog
Affected Modules: app
