### ISSUE TITLE
Help handling Push received when app is killed

### ISSUE THREAD

**Issue by chriswoolfe** [chat-sdk/chat-sdk-android#362]
First of all, great work on the Chat SDK. I am very impressed!

Push notifications work as expected if the app is in the foreground or background. When the app is killed, I notice that the DefaultBroadcastReceiver will send an Intent for ChatSDK.ui().getLoginActivity().

I would like to replace that LoginActivity with my own. What would you suggest as the best way to do this? Manifest Merge? Overriding getLoginActivity()? Some config? I could also implement my own BroadcastReceiver. 

Thanks for your attention!

**Comment by bensmiley** [comment]
Hi @chriswoolfe the easiest way to replace the login activity would be to follow [this guide](https://github.com/chat-sdk/docs#using-the-interface-manager). You can override the interface adapter and return a custom class by overriding this method:

```
    @Override
    public Class getProfileActivity() {
        return ProfileActivity.class;
    }

```

**Comment by ominfowave** [comment]
When app is swiped out or killed then come back again didn't receive any push notification.
