### ISSUE TITLE
How could i get recent chat list with group chat?

### ISSUE THREAD

**Issue by biswajitAqb** [chat-sdk/chat-sdk-android#367]
I did a try with calling 

> List<Thread> threads = NM.thread().getThreads(ThreadType.Private);

 this method, from thread i am able to find users. But did not working all the time as expected. Sometimes I got the response and some time not, don't know why?

Can you please share any suggesitons or snippers to figure out this issue.

Thank you.

**Comment by thecmart** [comment]
@biswajitAqb We have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
