### ISSUE TITLE
Missing informations to start a project

### ISSUE THREAD

**Issue by SamSnow** [chat-sdk/chat-sdk-android#371]
The quickstart has an important blank for the demo project : 

> The next step is to setup the Chat SDK using your Firebase and Social Accounts. To do that you need to do the following.

And then nothing ?! I found some explanations ( https://github.com/chat-sdk/chat-sdk-android/wiki/Chat-SDK-Android:-Firebase-Configuration ) but there is no BDefines.java so it's probably for an old version. 

It's to bad because I tried the demo with your firebase account but the doc is really tight for beginners.

PS : There is another line missing fail : 

> There are three main branches in the project:

> 
> master - the latest stable release version of the code
> v3_final - the legacy version of the project (no longer maintained)

**Comment by bensmiley** [comment]
Fixed now.
