### ISSUE TITLE
App crashes on Signout then closing the app with latest build

### ISSUE THREAD

**Issue by myeduapp** [chat-sdk/chat-sdk-android#376]
PFA screenshot of crash. Firebase json rules are also latest.
SDK code used to logout session is ChatSDK.auth().logout();
![screenshot_2018-09-22-21-21-19-669_com miui bugreport](https://user-images.githubusercontent.com/32955380/45920305-b3d65800-bebf-11e8-9f89-bf3175a1a594.png)

**Comment by myeduapp** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=9727025131&attid=0.1&permmsgid=msg-f:1612323917593357362&th=1660200f8304ac32&view=fimg&realattid=1660200b38bb018185b1&disp=thd&attbid=ANGjdJ8-TS1DOQYIG4htDsqLVzEk_M-liVY2GuZ9LJ6N8nNwsmYPDL5MqsCTWnNWrOsolrlFRsf_bri96atg1pteA3t1yJc8jyq1y2YhOZtyYvEx_JFsR35mkzJrfUg&ats=2524608000000&sz=w1367-h572

**Comment by myeduapp** [comment]
![screenshot_2018-09-22-21-27-59-393_com miui bugreport](https://user-images.githubusercontent.com/32955380/45920323-06b00f80-bec0-11e8-8f58-1fea2fdb725f.png)

**Comment by bensmiley** [comment]
Could you post the stack trace? This doesn't happen on the Github version which means that it's being caused by an interaction between the new version and some custom code you've written. If you can give me a full stack trace - especially, the line that's causing the crash, I can try to fix it.

**Comment by myeduapp** [comment]
@bensmiley Request your support on urgent basis

**Comment by bensmiley** [comment]
The first thing to do would be to actually implement the error block when you call logout. For example:

```
ChatSDK.auth().logout().subscribe(() -> {
            // Success
        }, throwable -> {
            // Error
        });
```

Then you can add a breakpoint and see what the error is caused by. But I would expect that you are trying to perform some kind of write or read in Firebase as you log out. As soon as you log out, this write or read fails because the user is no longer authenticated and causes the crash. It's likely that this is happening in some custom code you've added. It also looks like it's coming from the user wrapper is involved but I would need to see the whole stacktrace to confirm exactly what's going on.

**Comment by myeduapp** [comment]
It is still happening.

**Comment by myeduapp** [comment]
My custom is not called on the page where error is triggered on closing the app.

**Comment by myeduapp** [comment]
```
ChatSDK.auth().authenticateWithCachedToken().observeOn(AndroidSchedulers.mainThread()).subscribe(()->{
                                                Map<String,Object> taskMap = new HashMap<>();
                                                taskMap.put("pictureURL",profile.getProfileImage());
                                                FirebaseDatabase.getInstance().getReference("prodchat/users/"+fireUser.getUid()+"/meta").updateChildren(taskMap, new DatabaseReference.CompletionListener() {
                                                    @Override
                                                    public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
                                                        Intent i=new Intent(getBaseContext(),MainActivity.class);
                                                        startActivity(i);
                                                        finish();
                                                    }
                                                });
                                            });
```
Having this code in SignIn page but app is crashing on Sign up page where no custom code is present.

Also I am using below code to signout user 
FirebaseAuth.getInstance().signOut();

@bensmiley  Please suggest.

**Comment by bensmiley** [comment]
I think it's because you need to handle the error condition:

```
        ChatSDK.auth().authenticateWithCachedToken().observeOn(AndroidSchedulers.mainThread()).subscribe(() -> {
            Map<String, Object> taskMap = new HashMap<>();
            taskMap.put("pictureURL", profile.getProfileImage());
            FirebaseDatabase.getInstance().getReference("prodchat/users/" + fireUser.getUid() + "/meta").updateChildren(taskMap, new DatabaseReference.CompletionListener() {
                @Override
                public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
                    Intent i = new Intent(getBaseContext(), MainActivity.class);
                    startActivity(i);
                    finish();
                }
            });
        }, throwable -> {
            
        });
```

**Comment by myeduapp** [comment]
But this code is not getting called in crash as it is present in different activity(Signin activity). Btw is it fine if I just call FirebaseAuth.getInstance().signOut(); to signout as I am using Firebase for other app functionalities also.
App is crashing only when user logs out and opens signup page.

**Comment by myeduapp** [comment]
@bensmiley please suggest the proper way

**Comment by myeduapp** [comment]
@bensmiley Please help

**Comment by myeduapp** [comment]
@bensmiley please help

**Comment by SiWi88** [comment]
@bensmiley also having the same issue. Think the cause is coming from the UserWrapper class in the firebase-adapter module. When you minimise or close the app after logging out, it is trying to update the user, but in our app we not pushing the user after logout.

  public Completable push() {
        return Completable.create(e -> {

            final DatabaseReference ref = ref();

            updateFirebaseUser().subscribe(new CrashReportingCompletableObserver());

            ref.updateChildren(serialize(), (firebaseError, firebase) -> {
                if (firebaseError == null) {
                    // index should be updated whenever the user is pushed
                    FirebaseEntity.pushUserMetaUpdated(model.getEntityID()).subscribe(new CrashReportingCompletableObserver());
                    e.onComplete();
                }
                else {
                    e.onError(firebaseError.toException());
                }
            });
        }).subscribeOn(Schedulers.single()).andThen(updateIndex());
    }
