### ISSUE TITLE
Disable Push Notifications Completely

### ISSUE THREAD

**Issue by hjames2** [chat-sdk/chat-sdk-android#377]
I am working on implementing ChatSDK into my android application and would like to completely disable push notifications.  We do not have them on the iOS app, so for the sake of consistency, we would like them disabled on Android.  What is the best way to do this?

**Comment by o9simon** [comment]
Not activating FirebasePushModule should do the trick.

**Comment by hjames2** [comment]
I thought so too, but that does not seem to be the case.  I am NOT activating the FirebasePushModule and it is still sending push notifications.

**Comment by o9simon** [comment]
Maybe you're experiencing local notifications? You can disable those from your config using setShowLocalNotifications(false).

**Comment by hjames2** [comment]
That seems to have done the trick.  Thank you for the help!
