### ISSUE TITLE
Failed to resolve: com.github.mukeshsolanki:country-picker-android:1.2.4

### ISSUE THREAD

**Issue by 8991hnim** [chat-sdk/chat-sdk-android#382]
hello!
i'm doing the first step: import things. 
```
repositories {
    maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
    maven { url "https://maven.google.com" }
    maven { url "https://jitpack.io" }
}
compile 'co.chatsdk.chatsdk:chat-sdk-core:4.1.36'
compile 'co.chatsdk.chatsdk:chat-sdk-ui:4.1.36'
compile 'co.chatsdk.chatsdk:chat-sdk-firebase-adapter:4.1.36'
compile 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.1.36'
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.google.gms:google-services:3.1.1'
    }
}
apply plugin: 'com.google.gms.google-services'

i'm importing these, when sync it show me error : 
Failed to resolve: com.github.mukeshsolanki:country-picker-android:1.2.4
Failed to resolve: com.github.chrisbanes:PhotoView:2.1.4
```

**Comment by bensmiley** [comment]
@8991hnim Could you have a look at the [video tutorial](https://www.youtube.com/channel/UCQ_2hk0SOwoca0cfa5aDedA) and see if it solves your issue? I expect that you aren't including the JitPack repository location in the correct place. See these [docs](https://github.com/mukeshsolanki/country-picker-android/wiki/Getting-Started).

**Comment by thewijaysharma** [comment]
I am also having the same issue:

Failed to resolve: com.github.mukeshsolanki:country-picker-android:2.0.0
Failed to resolve: com.github.chrisbanes:PhotoView:2.2.0

Shall I use version 4.1.35 ?

**Comment by bensmiley** [comment]
You should update to the latest version `4.6.0`.

**Comment by thewijaysharma** [comment]
@bensmiley Issue still exists whenever I add the dependency - "co.chatsdk.chatsdk:chat-sdk-ui:4.6.0"

**Comment by bensmiley** [comment]
I've just double checked this and I can't replicate this issue. That means that there is probably an issue with your Gradle setup or your environment in general. Could you post a screenshot of the error message and also post your project level and app level `build.gradle` files?
