### ISSUE TITLE
switching tabs is not smooth

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#385]
cause of OnTabSelectedListener and below code, switching tabs is not smooth

           viewPager.setCurrentItem(tab.getPosition());
           InterfaceManager.shared().a.setShowLocalNotifications(showLocalNotificationsForTab(tab));
           for (int i = 0; i < tabs.size(); i++) {
                    ((BaseFragment) tabs.get(i).fragment).setTabVisibility(i == tab.getPosition());
           }

**Comment by bensmiley** [comment]
I can't replicate this as of 4.7.1
