### ISSUE TITLE
startLoginActivity and startMainActivity does not start as child activity

### ISSUE THREAD

**Issue by zishanj** [chat-sdk/chat-sdk-android#390]
I am manually starting the `login` activity from button, like this:

`ChatSDK.ui().startLoginActivity(context, true);`

but it does not start the activity as child activity so I can let the user go back to home screen using simple back button. Same is the case when MainActivity is launched after successful login.

**Comment by bensmiley** [comment]
If you want to start the activity as a child activity you should do it manually using a new intent. You can get the login activity using:

```
ChatSDK.ui().getLoginActivity();
```
