### ISSUE TITLE
Last message of thread not update after delete particular message. 

### ISSUE THREAD

**Issue by DipakSharmaAgile** [chat-sdk/chat-sdk-android#391]
There is one bug which I found on sender side in Conversations tab, 
When I trying to delete particular message than. the message will be deleted from the both side, but the last message of thread which is displayed in the conversations tab is not get update.
![screenshot_1538978365](https://user-images.githubusercontent.com/43946705/46593937-72fc5700-caed-11e8-9c58-d40b31cb8267.png)
![screenshot_1538978363](https://user-images.githubusercontent.com/43946705/46593938-7394ed80-caed-11e8-8b29-712f0a349bee.png)

**Comment by bensmiley** [comment]
Fixed in 4.6.0.
