### ISSUE TITLE
chat read receipt not working sometime

### ISSUE THREAD

**Issue by rahulsharmagbpec** [chat-sdk/chat-sdk-android#392]
Read receipt module is not working fine, whenever i gives my app for testing they come with an issues that read receipt is not working. Screen shot is attached.

<img width="635" alt="screen shot 2018-10-05 at 4 39 09 pm" src="https://user-images.githubusercontent.com/12457008/46595226-fb322a80-caf4-11e8-8619-5cbc0552bfcd.png">

**Comment by bensmiley** [comment]
Fixed in 4.6.0.
