### ISSUE TITLE
Can't view user online to chat with after proper configuration

### ISSUE THREAD

**Issue by sodiqOladeni** [chat-sdk/chat-sdk-android#398]
Chat is not showing up and also people that are using the app and logged in are not showing after all configuration is done, is there a special way of using the app, kindly assist on how to get started with the chat and group chat, have been able to log into the app on two different phone and two difference account but can't still communicate with each other. @bensmiley  kindly assist

**Comment by sodiqOladeni** [comment]
Have gone through the docs multiple times, someone should kindly help @bensmiley

**Comment by bensmiley** [comment]
@sodiqOladeni When you say - people are not showing up? Do you mean that they can't be found in the user search? Have you looked at our [tutorial videos](https://www.youtube.com/channel/UCQ_2hk0SOwoca0cfa5aDedA)? If you have a specific question I can try to help, it since I don't know what you've done for the integration, I can't really say what's gone wrong! If you need extra support, you could consider purchasing an hour of [priority support](https://chatsdk.co/downloads/priority-support-block/) so we can look over your project in more detail.

**Comment by alishouman** [comment]
@bensmiley 
Same here, I followed the docs and tutorial videos in integrating the app. I have 2 users logged in but I cant seem to find the other user when searching for contacts

**Comment by bensmiley** [comment]
@alishouman could you download the standard version of the app and see if search is working? Also, what are you using to search? The user's name or email or phone number?

**Comment by alishouman** [comment]
@bensmiley 
My bad! I thought all of the users would be listed under contacts to choose from without having to specifically search for their names. Thanks for getting back to me.

**Comment by sodiqOladeni** [comment]
@bensmiley I actually thought the same thing with @alishouman  but when is now search for the registered user i'm still getting a toast saying "No match found", please can be the cause of that ? @alishouman were you able to add users

**Comment by bensmiley** [comment]
@sodiqOladeni Have you added the security rules? Can you look at your Firebase database and look at the users/[user id]/meta path and verify that the string you are searching for does exist?

**Comment by sodiqOladeni** [comment]
@bensmiley thanks for your time, i added the security rules, but on checking firebase database there is no tree users/[user id]/meta, my database is missing the "user id" part, kindly check the image below for the structure of my database for more understanding.
![image](https://user-images.githubusercontent.com/25503978/47027386-42589500-d15f-11e8-9955-b8f93922b61b.png)

**Comment by sodiqOladeni** [comment]
@bensmiley how can i make it work, have been searching for the email that is present in the database but is still giving error "No match found"
