### ISSUE TITLE
Username should be unique

### ISSUE THREAD

**Issue by ganeshub** [chat-sdk/chat-sdk-android#40]
Hi,

Username, Email, Phone Number should be a unique field. FB rules also need the update.

**Comment by kykrueger** [comment]
Hi,

Firebase already manages if users are unique or not. Furthermore, uniqueness of username, email, and phone number are not enforced to keep the SDK flexible. If unique names, numbers, and emails are a requirement of your implementation, we could discuss a quote to add that functionality. 

Lastly, what do you mean when you say FB rules need the update? Could that be split off as a separate issue?

-- Kyle

**Comment by bensmiley** [comment]
As Kyle said, there is no requirement for the name to be unique - since it is the user's name rather than their username. Authentication happens with an email (which must be unique) or via social login.
