### ISSUE TITLE
Forgot password support

### ISSUE THREAD

**Issue by ganeshub** [chat-sdk/chat-sdk-android#41]
Is Forgot password supported ?

**Comment by SimplisticApps** [comment]
For that you will need to use the this:  `BNetworkManager.sharedManager().getNetworkAdapter().sendPasswordResetMail());`

I use it on the login page so people send a request to their email then they reset it using the automatically generated email and link

**Comment by kykrueger** [comment]
@ganeshub Have you gotten forgot password working? I am closing this issue since the question was answered.

**Comment by ganeshub** [comment]
@SimplisticApps Thanks
@kykrueger It works
