### ISSUE TITLE
com.android.support:appcompat-v7:28.0.0 conflict & Compile to "Implementation

### ISSUE THREAD

**Issue by tobimichigan** [chat-sdk/chat-sdk-android#413]
1. **Is the bug present in the demo Chat SDK project?** Not exactly but complains of  com.android.support:appcompat-v7 conflict

2. **What modifications have you made to the Chat SDK?** I started a new android project and targeted the newest android build tools  version 28.0.0, and complied targeting the newest android sdk. However, there seems to be com.android.support:appcompat-v7: 28.0.0= conflict

3. **Android Version:**= 8.1

4. **Steps taken to reproduce the problem:** target buildtools 28.0.0

5. **Expected result:** conflict in the app build gradle file

6. **Actual result:** same as above

7. **Comments:** I updated the android repository to 47.0 yet the problem persits

Your build variables says:
MIN_SDK = 16
ANDROID_BUILD_TARGET_SDK_VERSION = 25
ANDROID_COMPILE_SDK_VERSION = 27
ANDROID_SUPPORT_VERSION = 27.1.1

What about the app compact version?
What steps is being taken to change "compile" to "implementation" or "api"???

**Comment by mohyazji** [comment]
you need to update the google play serves 

I get the same error on v.4.3.6 and this should be update

In sdk-core :
api 'com.google.android.gms:play-services-auth:16.0.1'
api 'com.google.android.gms:play-services-maps:16.0.0'

chat-sdk-ui :
api 'com.google.android.gms:play-services-places:16.0.0'

**Comment by ezet** [comment]
You need to update ANDROID_SUPPORT_VERSION = 27.1.1 to 28.x.x if you are using build tools version 28. But in general you should not specify builds tools version explicitly anymore, gradle will determine the correct version to use if you don't specify it.

**Comment by tobimichigan** [comment]
@mohyazji , thanks for your response and please my apologies for the delay. You stated, "In sdk-core :
api 'com.google.android.gms:play-services-auth:16.0.1'
api 'com.google.android.gms:play-services-maps:16.0.0'

chat-sdk-ui :
api 'com.google.android.gms:play-services-places:16.0.0'"

I am yet to test this but soon as I do, I will post the result here.

and 

@ezet. thanks for your response too, but you seem to be talking in theory unlike mohyazji  who seems to understand what I am talking about better.

I have cloned this chat sdk which seems to be quite interesting to me and I would love to be an active contributor for further development. Bugs can't be avoided completely but at least should be found and fixed quickly.
I also observe though that "compile" is still being used in the chat sdk which is expiring by the end of 2018. I think we should start looking at this too. I will be in touch.

**Comment by tobimichigan** [comment]
1st Image indicating where the red line is.
![chat-sdk-app_level bug](https://user-images.githubusercontent.com/5084987/48299085-5b3b3880-e4c8-11e8-8afd-c8660e848e77.png)

2nd image indicating the other two areas where the bug is when targeting build-tools 28.0.0
![chat-sdk-aui](https://user-images.githubusercontent.com/5084987/48299107-a2c1c480-e4c8-11e8-9bc9-6a531875fb34.png)

Ok guys here's my algorithm for the latest build tools:

1. Top level build file:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.google.gms:google-services:3.1.1'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
        maven { url "https://maven.google.com" }
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}



2. Module Level Algorithm

apply plugin: 'com.android.application'

android {
    signingConfigs {
        config {
            
        }
    }
    compileSdkVersion 28
    defaultConfig {
        applicationId "package.name"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildToolsVersion '28.0.3'//this is android latest buildtools
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    api 'com.android.support.constraint:constraint-layout:1.1.3'
    api 'co.chatsdk.chatsdk:chat-sdk-core:4.3.4'
    api 'co.chatsdk.chatsdk:chat-sdk-ui:4.3.4'
    api 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.3.4'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'//Trouble spot, mysterious red underlining
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    api 'com.android.support:support-annotations:28.0.0'
    api 'com.android.support:support-v4:28.0.0'
    api  'com.android.support:appcompat-v7:28.0.0'


    api fileTree(include: ['*.jar'], dir: 'libs')
    api 'com.android.support:multidex:1.0.3'
    //api project(path: ':chat-sdk-core')
    api project(path: ':chat-sdk-ui')
    api project(path: ':chat-sdk-firebase-adapter')
    api project(path: ':chat-sdk-firebase-push')
    api project(path: ':chat-sdk-firebase-file-storage')
    api project(path: ':chat-sdk-firebase-ui')
}

apply plugin: 'com.google.gms.google-services'


3.chat-sdk-core module

apply plugin: 'com.android.library'

buildscript {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }

    dependencies {
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}


apply plugin: 'org.greenrobot.greendao'

android {

    //compileSdkVersion //Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)
compileSdkVersion 28
    defaultConfig {
         minSdkVersion 21
        targetSdkVersion 28   
}

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

greendao {
    schemaVersion 4
    targetGenDir "src/main/java"
    daoPackage "co.chatsdk.core.dao"
}

dependencies {

//    api fileTree(include: ['*.jar'], dir: 'libs')

    api 'org.greenrobot:greendao:3.2.2'
    api 'joda-time:joda-time:2.10'
    api 'com.jakewharton.timber:timber:4.7.1'
    api 'com.google.code.gson:gson:2.8.5'
    api 'io.reactivex.rxjava2:rxandroid:2.0.2'
    api 'io.reactivex.rxjava2:rxjava:2.1.16'
    api 'org.apache.commons:commons-lang3:3.7'
    api 'com.google.android.gms:play-services-auth:16.0.1'
    api 'com.google.android.gms:play-services-maps:16.0.0'

    api 'id.zelory:compressor:2.1.0'
    api 'android.arch.lifecycle:extensions:1.1.1'
    api 'com.facebook.fresco:fresco:1.9.0'

    api 'com.android.support:support-v4:' //+ //project.ANDROID_SUPPORT_VERSION

}

// Bintray upload properties
Properties properties = new Properties()
File localProperties = project.rootProject.file('local.properties')
if(localProperties.exists()) {
    properties.load(localProperties.newDataInputStream())
    if(properties.getProperty('bintray.enabled') != null) {

        group = CHAT_SDK_GROUP
        version = CHAT_SDK_VERSION

        ext {
            bintrayRepo = BINTRAY_REPO
            bintrayName = 'chat-sdk-core'
            bintrayUserOrg = BINTRAY_USER_ORG

            publishedGroupId = CHAT_SDK_GROUP
            libraryName = 'ChatSDKCore'
            artifact = 'chat-sdk-core'

            libraryDescription = 'Chat SDK Core'

            siteUrl = SITE_URL
            gitUrl = GIT_URL

            libraryVersion = CHAT_SDK_VERSION

            developerId = DEVELOPER_ID
            developerName = DEVELOPER_NAME
            developerEmail = DEVELOPER_EMAIL

            licenseName = LICENSE_NAME
            licenseUrl = LICENSE_URL
            allLicenses = ['GPL-3.0']
        }

        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/installv1.gradle'
        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/bintrayv1.gradle'
    }
}


4.chat-sdk-firebase-adapter module
apply plugin: 'com.android.library'

buildscript {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }

    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}

apply plugin: 'com.jfrog.bintray'

android {

  	compileSdkVersion 28
//Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)

    defaultConfig {
         minSdkVersion 21
        targetSdkVersion 28
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')

    // The latest versions aren't used because of Firebase UI - see: https://github.com/firebase/FirebaseUI-Android/releases
    api 'com.google.firebase:firebase-core:16.0.1'
    api 'com.google.firebase:firebase-database:16.0.1'
    api 'com.google.firebase:firebase-storage:16.0.1'
    api 'com.google.firebase:firebase-auth:16.0.2'

    api project(':chat-sdk-core')
}

// Bintray upload properties
Properties properties = new Properties()
File localProperties = project.rootProject.file('local.properties')
if(localProperties.exists()) {
    properties.load(localProperties.newDataInputStream())
    if(properties.getProperty('bintray.enabled') != null) {

        group = CHAT_SDK_GROUP
        version = CHAT_SDK_VERSION

        ext {
            bintrayRepo = BINTRAY_REPO
            bintrayName = 'chat-sdk-firebase-adapter'
            bintrayUserOrg = BINTRAY_USER_ORG

            publishedGroupId = CHAT_SDK_GROUP
            libraryName = 'ChatSDKFirebaseAdapter'
            artifact = 'chat-sdk-firebase-adapter'

            libraryDescription = 'Chat SDK Firebase Adapter'

            siteUrl = SITE_URL
            gitUrl = GIT_URL

            libraryVersion = CHAT_SDK_VERSION

            developerId = DEVELOPER_ID
            developerName = DEVELOPER_NAME
            developerEmail = DEVELOPER_EMAIL

            licenseName = LICENSE_NAME
            licenseUrl = LICENSE_URL
            allLicenses = ['GPL-3.0']
        }

        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/installv1.gradle'
        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/bintrayv1.gradle'
    }
}

5. chat-sdk-firebase-storage
apply plugin: 'com.android.library'

buildscript {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }

    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}

apply plugin: 'com.jfrog.bintray'

android {

    compileSdkVersion 28
//Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)

    defaultConfig {
         minSdkVersion 21
        targetSdkVersion 28    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api project(':chat-sdk-core')
    api 'com.google.firebase:firebase-storage:16.0.1'
}

// Bintray upload properties
Properties properties = new Properties()
File localProperties = project.rootProject.file('local.properties')
if(localProperties.exists()) {
    properties.load(localProperties.newDataInputStream())
    if(properties.getProperty('bintray.enabled') != null) {

        group = CHAT_SDK_GROUP
        version = CHAT_SDK_VERSION

        ext {
            bintrayRepo = BINTRAY_REPO
            bintrayName = 'chat-sdk-firebase-file-storage'
            bintrayUserOrg = BINTRAY_USER_ORG

            publishedGroupId = CHAT_SDK_GROUP
            libraryName = 'ChatSDKFirebaseFileStorage'
            artifact = 'chat-sdk-firebase-file-storage'

            libraryDescription = 'Chat SDK Firebase File Storage'

            siteUrl = SITE_URL
            gitUrl = GIT_URL

            libraryVersion = CHAT_SDK_VERSION

            developerId = DEVELOPER_ID
            developerName = DEVELOPER_NAME
            developerEmail = DEVELOPER_EMAIL

            licenseName = LICENSE_NAME
            licenseUrl = LICENSE_URL
            allLicenses = ['GPL-3.0']
        }

        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/installv1.gradle'
        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/bintrayv1.gradle'
    }
}


//apply from: rootProject.file('bintray.gradle')


6.chat-sdk=firebase-push
apply plugin: 'com.android.library'

buildscript {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }

    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}

apply plugin: 'com.jfrog.bintray'

android {

    compileSdkVersion 28
//Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)

    defaultConfig {
         minSdkVersion 21
        targetSdkVersion 28
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])
    api project(':chat-sdk-core')
    api project(':chat-sdk-ui')

    // The latest versions aren't used because of Firebase UI - see: https://github.com/firebase/FirebaseUI-Android/releases
    api 'com.google.firebase:firebase-messaging:17.0.0'
    api 'com.squareup.okhttp3:okhttp:3.11.0'
}

// Bintray upload properties
Properties properties = new Properties()
File localProperties = project.rootProject.file('local.properties')
if(localProperties.exists()) {
    properties.load(localProperties.newDataInputStream())
    if(properties.getProperty('bintray.enabled') != null) {

        group = CHAT_SDK_GROUP
        version = CHAT_SDK_VERSION

        ext {
            bintrayRepo = BINTRAY_REPO
            bintrayName = 'chat-sdk-firebase-push'
            bintrayUserOrg = BINTRAY_USER_ORG

            publishedGroupId = CHAT_SDK_GROUP
            libraryName = 'ChatSDKFirebasePush'
            artifact = 'chat-sdk-firebase-push'

            libraryDescription = 'Chat SDK Firebase Push'

            siteUrl = SITE_URL
            gitUrl = GIT_URL

            libraryVersion = CHAT_SDK_VERSION

            developerId = DEVELOPER_ID
            developerName = DEVELOPER_NAME
            developerEmail = DEVELOPER_EMAIL

            licenseName = LICENSE_NAME
            licenseUrl = LICENSE_URL
            allLicenses = ['GPL-3.0']
        }

        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/installv1.gradle'
        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/bintrayv1.gradle'
    }
}



7.chat-sdk-firebase-ui
apply plugin: 'com.android.library'

buildscript {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }

    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}

apply plugin: 'com.jfrog.bintray'

android {

    compileSdkVersion 28
//Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)

    defaultConfig {
         minSdkVersion 21
        targetSdkVersion 28    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])

    api project(':chat-sdk-core')
    api project(':chat-sdk-ui')
    api project(':chat-sdk-firebase-adapter')

    api 'com.firebaseui:firebase-ui-auth:4.1.0'
    api 'com.android.support:customtabs:' //+ //project.ANDROID_SUPPORT_VERSION

}

// Bintray upload properties
Properties properties = new Properties()
File localProperties = project.rootProject.file('local.properties')
if(localProperties.exists()) {
    properties.load(localProperties.newDataInputStream())
    if(properties.getProperty('bintray.enabled') != null) {

        group = CHAT_SDK_GROUP
        version = CHAT_SDK_VERSION

        ext {
            bintrayRepo = BINTRAY_REPO
            bintrayName = 'chat-sdk-firebase-ui'
            bintrayUserOrg = BINTRAY_USER_ORG

            publishedGroupId = CHAT_SDK_GROUP
            libraryName = 'ChatSDKFirebaseUI'
            artifact = 'chat-sdk-firebase-ui'

            libraryDescription = 'Chat SDK Firebase UI'

            siteUrl = SITE_URL
            gitUrl = GIT_URL

            libraryVersion = CHAT_SDK_VERSION

            developerId = DEVELOPER_ID
            developerName = DEVELOPER_NAME
            developerEmail = DEVELOPER_EMAIL

            licenseName = LICENSE_NAME
            licenseUrl = LICENSE_URL
            allLicenses = ['GPL-3.0']
        }

        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/installv1.gradle'
        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/bintrayv1.gradle'
    }
}

8.chat-sdk-ui module

apply plugin: 'com.android.library'

buildscript {
    repositories {
        google()
        maven { url "https://jitpack.io" }
        jcenter()
    }

    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.4'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
    }
}

apply plugin: 'com.jfrog.bintray'

android {

    compileSdkVersion 28
//Integer.parseInt(project.ANDROID_COMPILE_SDK_VERSION)

    defaultConfig {
	 minSdkVersion 21
        targetSdkVersion 28

    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-fresco.pro'
        }
        debug {
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')

    api 'com.android.support:appcompat-v7:28.0.0'// + project.ANDROID_SUPPORT_VERSION //Trouble spot, conflict com android support libraries
    api 'com.android.support:support-core-utils:28.0.0'// + project.ANDROID_SUPPORT_VERSION
    api 'com.android.support:design:28.0.0' //+ project.ANDROID_SUPPORT_VERSION
    api 'com.android.support:recyclerview-v7:28.0.0' //+ project.ANDROID_SUPPORT_VERSION
    api "com.android.support:support-v13:28.0.0" //+ project.ANDROID_SUPPORT_VERSION
    api "com.android.support:cardview-v7:28.0.0" //+ project.ANDROID_SUPPORT_VERSION
    api "com.android.support:design:28.0.0" //+ project.ANDROID_SUPPORT_VERSION
    api "com.google.android.gms:play-services-places:16.0.0"

    api 'com.android.support.constraint:constraint-layout:1.1.3'
    api 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'

    api 'com.github.mukeshsolanki:country-picker-android:1.2.4'
    implementation 'com.github.chrisbanes:PhotoView:2.1.4'
    api 'com.theartofdev.edmodo:android-image-cropper:2.7.0'

    api project(':chat-sdk-core')
}

// Bintray upload properties
Properties properties = new Properties()
File localProperties = project.rootProject.file('local.properties')
if(localProperties.exists()) {
    properties.load(localProperties.newDataInputStream())
    if(properties.getProperty('bintray.enabled') != null) {

        group = CHAT_SDK_GROUP
        version = CHAT_SDK_VERSION

        ext {
            bintrayRepo = BINTRAY_REPO
            bintrayName = 'chat-sdk-ui'
            bintrayUserOrg = BINTRAY_USER_ORG

            publishedGroupId = CHAT_SDK_GROUP
            libraryName = 'ChatSDKUI'
            artifact = 'chat-sdk-ui'

            libraryDescription = 'Chat SDK UI'

            siteUrl = SITE_URL
            gitUrl = GIT_URL

            libraryVersion = CHAT_SDK_VERSION

            developerId = DEVELOPER_ID
            developerName = DEVELOPER_NAME
            developerEmail = DEVELOPER_EMAIL

            licenseName = LICENSE_NAME
            licenseUrl = LICENSE_URL
            allLicenses = ['GPL-3.0']
        }

        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/installv1.gradle'
        apply from: 'https://raw.githubusercontent.com/chat-sdk/JCenter/master/bintrayv1.gradle'
    }
}


SUMMARY OF BUGS


2. Module Level Algorithm (under dependencies)


    androidTestImplementation 'com.android.support.test:runner:1.0.1'//Trouble spot, mysterious red underlining, conflict com android support libraries

8.chat-sdk-ui module (under dependencies)

   api 'com.android.support:appcompat-v7:28.0.0'// + project.ANDROID_SUPPORT_VERSION //Trouble spot, conflict com android support libraries

Like I indicated earlier, I created a new android project and imported the chat-sdk-android modules into my existing project targetting 28.0.0.
Finally, "Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'" is still popping up which clearly indicates that one of the chat-sdk-android is still having the deprecated "compile" on its way out by the end of 2018.  Or am I missing something?

**Comment by bensmiley** [comment]
This should be resolved in 4.6.0. We have now moved to use AndroidX.
