### ISSUE TITLE
Push notification null pointer exception (when app is closed)

### ISSUE THREAD

**Issue by nnkemail** [chat-sdk/chat-sdk-android#414]
Hi, first thank you for your project. Great work.
Issue:
When app is closed (when you swipe it to the right) and send message to it - instead push notification it gives me following exception:

> 
    java.lang.RuntimeException: Unable to start receiver co.chatsdk.firebase.push.DefaultBroadcastReceiver: java.lang.NullPointerException: Attempt to read from field 'boolean co.chatsdk.core.session.Configuration.inboundPushHandlingEnabled' on a null object reference
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2712)
        at android.app.ActivityThread.access$1700(ActivityThread.java:162)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5421)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean co.chatsdk.core.session.Configuration.inboundPushHandlingEnabled' on a null object reference
        at co.chatsdk.firebase.push.DefaultBroadcastReceiver.onReceive(DefaultBroadcastReceiver.java:24)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2700)

It is this code that throws an exception (DefaultBroadcastReceiver.java):

`        if(!ChatSDK.config().inboundPushHandlingEnabled) {
            return;
        }`

It looks like when app is closed ChatSDK.config() returns null.

Thanks in advance for any help.

**Comment by vhadi** [comment]
Got the same problem.

Had to add initializing on the OnCreate (DefaultBroadcastReceiver.java)

`Configuration.Builder builder = new Configuration.Builder(context);
        builder.firebaseRootPath("testdb");
        try {
            ChatSDK.initialize(builder.build(), new BaseInterfaceAdapter(context), new FirebaseNetworkAdapter());
        }
        catch (ChatSDKException e) {
        }
`

before this line :

`if(!ChatSDK.config().inboundPushHandlingEnabled) { return; }`

**Comment by bensmiley** [comment]
I can confirm that the project doesn't compile when minify is enabled.

**Comment by bensmiley** [comment]
Currently quick reply isn't supported by the SDK. I've added this as a feature request.

**Comment by GDMobileTeam** [comment]
ChatSDK implementation: 'sdk.chat:firebase-app:5.0.0rc21'
The above error still occures to me:
```
Fatal Exception: java.lang.RuntimeException
Unable to start receiver sdk.chat.core.push.DefaultBroadcastReceiver: java.lang.IllegalArgumentException: the bind value at index 1 is null

Caused by java.lang.IllegalArgumentException
the bind value at index 1 is null
android.database.sqlite.SQLiteProgram.bindString (SQLiteProgram.java:183)
android.database.sqlite.SQLiteDatabase.rawQuery (SQLiteDatabase.java:1906)
**org.greenrobot.greendao.database.StandardDatabase.rawQuery (StandardDatabase.java:32)**
```

Any way to fix this?

**Comment by bensmiley** [comment]
Can you update to the latest version 5.1.1 and tell me if it still happens? We don't support old versions.

**Comment by GDMobileTeam** [comment]
Yeah sure, I didn't see any newer version on your github page
It will take me some time to test it out
But one more thing, after updating to sdk.chat:firebase-app:5.1.1
I am no longer able to look into your library files
Getting this message: decompiled .class file bytecode version 52.0 (java 8)
And when I try to download sources i get the following error:
```
* What went wrong:
Execution failed for task ':app:DownloadSources'.
> Could not resolve all files for configuration ':app:downloadSources_e8d9daa6-8f02-445c-88b5-637a14d4af98'.
   > Could not find sdk.chat:core:5.1.1@aar.
     Required by:
         project :app
```

Doo you have any suggestions on how to solve this? Everything I tried failed.

**Comment by GDMobileTeam** [comment]
Hi, @bensmiley 
Just to get back to you, after extensive testing I can say that upgrading to the newer version of the library did fix the problem, thanks!
