### ISSUE TITLE
Proguard errors, missing referenced class org.joda.convert.*

### ISSUE THREAD

**Issue by ezet** [chat-sdk/chat-sdk-android#417]
1. **Is the bug present in the demo Chat SDK project?**
No idea.

2. **What modifications have you made to the Chat SDK?**
None that are relevant.

3. **Android Version:**
All.

4. **Steps taken to reproduce the problem:**
Minify project with ProGuard

5. **Expected result:**
Successful build.

6. **Actual result:**
Build error.
Warning: org.joda.time.DateMidnight: can't find referenced class org.joda.convert.FromString
And 36 other, similar warnings.

7. **Comments:**
ChatSDK has joda-time as a dependency, which uses annotations that apparently are not included in the library. You should either add joda-converter as an explicit dependency, or add instructions for how to configure proguard to avoid this error.
e.g. 
`-dontwarn org.joda.convert.**`

**Comment by ezet** [comment]
More info here https://stackoverflow.com/questions/17753988/android-proguard-didnt-compile-with-joda-time-jar-file

**Comment by bensmiley** [comment]
I can confirm that the project won't compile when minification is enabled. Even when the joda line is added to proguard.

**Comment by thecmart** [comment]
@ezet We have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
