### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by farhanfarooq01** [chat-sdk/chat-sdk-android#42]
I can't understand this( make sure you set the  pakagr  name with.....com.braunster.androidchatsdk.firebaseplugin) where i use it ?? also i am configuring my Own app with my project name...can i edit it

**Comment by simonsmiley64** [comment]
Hi @farhanfarooq01,

When you are configuring the Firebase Android project you need to make sure to add in your Firebase dashboard. This allows the project to work properly. 

I would recommend watching this video: https://www.youtube.com/watch?v=sMSlD_fftr0&t=2s

It goes through the complete process of adding the Chat SDK. It will also show you when and where you need to add your package name and when you need to add the above package name. 

Watch this and if you need more help let us know

Simon
