### ISSUE TITLE
Cannot build for prects using androidx

### ISSUE THREAD

**Issue by eakteam** [chat-sdk/chat-sdk-android#421]
1. **Is the bug present in the demo Chat SDK project?**  YES

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:** API 28

4. **Steps taken to reproduce the problem:** Just sync with gradle

5. **Expected result:** Failed to sync

6. **Actual result:**

7. **Comments:**

Can you port to androidx libraries ?

**Comment by bensmiley** [comment]
We've now updated the library to use Android X.
