### ISSUE TITLE
Device Push Token missing in FireBase database

### ISSUE THREAD

**Issue by itimmisriis** [chat-sdk/chat-sdk-android#426]
1. **Is the bug present in the demo Chat SDK project?**
Yes

2. **What modifications have you made to the Chat SDK?**
No modifications were made on chat sdk source code. We installed ChatSDK along with Blocking and push notification modules

3. **Android Version:**
7,8,9

4. **Steps taken to reproduce the problem:**
Create an account on ChatSDK with android SDK and the account does not have a generated Push Token for device listed in the FireBase database

5. **Expected result:**
Users created with ChatSDK have a Push Token attached in the FireBase database.

6. **Actual result:**
Push Token is missing from FireBase for android users

7. **Comments:**
iOS ChatSDK seems to do this fine.

**Comment by bensmiley** [comment]
The device token is no longer pushed to the Firebase database because now push notifications are handled by Firebase Cloud Code. See [guide here](https://github.com/chat-sdk/chat-sdk-android#setup-firebase-cloud-functions).
