### ISSUE TITLE
Chat app

### ISSUE THREAD

**Issue by farhanfarooq01** [chat-sdk/chat-sdk-android#43]
Nice app ..but i don't want to import....i want to build whole app by myself. .......plxxx help me.....plxxx

**Comment by kykrueger** [comment]
Hello Farhan,

If you are looking to use the backend from the SDK with your own app. There are two ways of getting started. The first being to modify the demo app directly, or use it as an example while building your own with the backend classes such as the firebase plugin and the abstract network adapter. 
Depending on your needs we do also offer [priority support packages](http://chatsdk.co/downloads/priority-support-block/), and [custom integrations](http://chatsdk.co/pricing/) of the SDK.

What are you looking to change from the demo app, or to implement from the SDK?

**Comment by farhanfarooq01** [comment]
i am looking for the change in demo but full steps plzz??

**Comment by bensmiley** [comment]
You will need to be more specific about what you're looking for. We can provide basic support and bug fixes for free but you require help that's specific to your app, then you would need to take out an integration service or some priority support hours.
