### ISSUE TITLE
NullPointerException getReadStatus

### ISSUE THREAD

**Issue by nnkemail** [chat-sdk/chat-sdk-android#438]
Hi, during chat app sometimes throw following exception:

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
co.chatsdk.core.dao.Message.getReadStatus (Message.java:383)
co.chatsdk.ui.chat.MessagesListAdapter.updateReadStatus (MessagesListAdapter.java:355)
co.chatsdk.ui.chat.MessagesListAdapter.onBindViewHolder (MessagesListAdapter.java:335)
co.chatsdk.ui.chat.MessagesListAdapter.onBindViewHolder (MessagesListAdapter.java:51)

I fetch contacts for current user from my server, some of these users haven't log into chat yet.
Any suggestions what can be possible cause of this exception? Also, it shows more often during group chat.

Thanks in advance for any help.

**Comment by bensmiley** [comment]
Can't reproduce as of 4.6.0. If this issue persists please reopen the issue.
