### ISSUE TITLE
Missing messages

### ISSUE THREAD

**Issue by nnkemail** [chat-sdk/chat-sdk-android#439]
1. **Is the bug present in the demo Chat SDK project?**
This bug is present in official demo apk.

2. **What modifications have you made to the Chat SDK?**
none

3. **Android Version:**
5.1.1

4. **Steps taken to reproduce the problem:**
I wrote numbers from 1 to 100 yesterday and today in the morning (crash happend in the morning) and then some numbers from yesterday were missing (7 to 21 from yesterday but i think today in the morning other were missing too, now only 7 to 21 are missing). I wrote this on EPL leaders public room.

5. **Expected result:**
No gaps in messages

6. **Actual result:**
1-100  then 1 to 6 then 22 to 121 is visible

**Comment by thecmart** [comment]
This bug has been fixed, the numbers now appear in the chat.
