### ISSUE TITLE
Firebase 和 PubNub相比较怎么样？

### ISSUE THREAD

**Issue by sjdlfajdlfe** [chat-sdk/chat-sdk-android#441]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
https://chatsdk.co/mobile-messaging-service-price-comparison/
