### ISSUE TITLE
Push Notification not working

### ISSUE THREAD

**Issue by vansh1sh** [chat-sdk/chat-sdk-android#444]
1. **Is the bug present in the demo Chat SDK project?**
Yes

2. **What modifications have you made to the Chat SDK?**
None

3. **Android Version:**
8

Push notifications doesn't seem to work.
Error:

10:36:36.000 PM | warning | pushListener | Error: data must only contain string values     at FirebaseMessagingError.Error (native)     at FirebaseMessagingError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)     at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)     at new FirebaseMessagingError (/user_code/node_modules/firebase-admin/lib/utils/error.js:241:16)     at /user_code/node_modules/firebase-admin/lib/messaging/messaging.js:95:19     at Array.forEach (native)     at validateStringMap (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:93:22)     at validateMessage (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:322:5)     at Messaging.send (/user_code/node_modules/firebase-admin/lib/messaging/messaging.js:461:9)     at getUserIds.then (/user_code/index.js:224:39)
-- | -- | -- | --

![image](https://user-images.githubusercontent.com/16793070/49688630-1fcd7180-fb3b-11e8-8d84-a2ec287cd4e9.png)

**Comment by muhammadsr** [comment]
I do get this too 
<img width="1257" alt="screen shot 2018-12-22 at 6 44 24 pm" src="https://user-images.githubusercontent.com/1937488/50380350-a98c3d00-0619-11e9-8c1d-ed3aa802084f.png">

**Comment by muhammadsr** [comment]
I just realized the issue for me was related to the APNS setup. I started using a new BundleId and I forgot to upload the certificate in Firebase console
<img width="645" alt="screen shot 2018-12-22 at 7 05 15 pm" src="https://user-images.githubusercontent.com/1937488/50380451-8d3dcf80-061c-11e9-967b-59b8ad937ea5.png">

**Comment by bensmiley** [comment]
This has been resolved as of 4.6.0.
