### ISSUE TITLE
App receives Push notification from blocked user.

### ISSUE THREAD

**Issue by itimmisriis** [chat-sdk/chat-sdk-android#446]
1. **Is the bug present in the demo Chat SDK project?**
N/A

2. **What modifications have you made to the Chat SDK?**
N/A

3. **Android Version:**
Android 8

4. **Steps taken to reproduce the problem:**
Create 2 users. User A blocks user B. User B sends User A a message

5. **Expected result:**
User A should not receive push notification

6. **Actual result:**
User A should receives push notification

7. **Comments:**
This happens with iOS SDK as well.

**Comment by bensmiley** [comment]
I've confirmed this issue. Looking for a solution now.

**Comment by thecmart** [comment]
@itimmisriis We have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
