### ISSUE TITLE
Enable Push notification for public groups

### ISSUE THREAD

**Issue by karan1213** [chat-sdk/chat-sdk-android#449]
I have created public group and deployed Firebase functions and they are working fine for private group.
I noticed that there is a flag maintained inside ChatActivity.Java which makes user to be removed from thread when leaving from chat screen.

I overrides onStop() method and prevented user from getting removed from chat group which is working fine and user is linked to the thread even if user left the chat screen and user can receive push notification triggered from Firebase function.

But I also noticed that when user kills the app or system kills the process after user leaves from the app, the user gets removed from thread's member list and due to this they are not able to receive push notifications.

I tried to find the cause of this case. May b you guys have done this intentionally but I would like to bypass this case so I could achieve my requirement.

Can anybody please guide me where exactly this user removal code is written and in which case this is being executed.

*Please accept my apology if I wrote this in wrong place :)

**Comment by tobimichigan** [comment]
perhaps you should check the config file

**Comment by bensmiley** [comment]
This can be enabled using config flag `config.pushNotificationsForPublicChatRoomsEnabled = true` during Chat SDK setup.
