### ISSUE TITLE
[v.4.4.8] Empty message displayed when sending numbers only message

### ISSUE THREAD

**Issue by zaramma** [chat-sdk/chat-sdk-android#450]
1. **Is the bug present in the demo Chat SDK project?**
yes

2. **What modifications have you made to the Chat SDK?**
no modification

3. **Android Version:**
8
4. **Steps taken to reproduce the problem:**
sending any number in chat activity "123" "2018" will be displayed as ""
5. **Expected result:**
Seems to be co.shatsdk.core.dao.Message:stringForKey() need to be reverted to previous code.
The change you made is converting "123" into integer 123, and filter anything isn't String object. That is why the function always returns empty string.

Conrad Here; this is what my debugger gives me when I type in only numbers:

D/MessagesListAdapter: Delivered
D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
D/ChatActivity: Message Status: Sending
D/MessagesListAdapter: Add Message Item: 
D/ChatActivity: Message Status: Sending
D/MessagesListAdapter: Delivered
E/RecyclerView: Passed over target position while smooth scrolling.
D/ChatActivity: Message Status: Sent

**Comment by thecmart** [comment]
This bug has been fixed, the numbers now appear in the chat.
