### ISSUE TITLE
Unable to start activity ...LoginActivity

### ISSUE THREAD

**Issue by Whatsrap** [chat-sdk/chat-sdk-android#451]
1. **Is the bug present in the demo Chat SDK project?**
No it is not present
2. **What modifications have you made to the Chat SDK?**
No modifications yet
3. **Android Version:**
8.1
4. **Steps taken to reproduce the problem:**
Just followed the steps given in the Android Quickstart here: [(https://chatsdk.co/docs/android-quickstart/)]
5. **Expected result:**
It should start a short app right?
6. **Actual result:**
App crashes during start with errormessage:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{de.********.chatsdktry/co.chatsdk.ui.login.LoginActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean co.chatsdk.core.session.Configuration.resetPasswordEnabled' on a null object reference`
7. **Comments:**
I completely followed the given steps and made no changes.
I implemented no extra modules.

**Comment by tobimichigan** [comment]
What version of Android Studio are you using?

**Comment by Whatsrap** [comment]
Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by tobimichigan** [comment]
Please kindly update your Jre/JDK. Win10 is quite demanding than Win 8.0, then maybe consider uninstall and reinstalling Studio. Your version in Android Studio is ok as stated above.

Re-clone the repo and re-run in the updated Jre/JDK environment.

**Comment by tobimichigan** [comment]
@AllysonYuShiong , it is always advisable to upgrade platforms carefully. Even Google advises to create a two different platforms say, an immediate former and new platform to run in parallel and compare executions.

Recommendation: 
1. Revert to Android studio 3.2, and run the repo on it
2. Create a separate  directory for  Android 3.3 and test unit by unit.

This is a norm in Software Engineering design and testing.

**Comment by bensmiley** [comment]
Tested and can't reproduce in 4.6.0. If it still persists please reopen the issue.
