### ISSUE TITLE
Push notifications are showing the recipients name rather than the sender's name

### ISSUE THREAD

**Issue by muhammadsr** [chat-sdk/chat-sdk-android#454]
1. **Is the bug present in the demo Chat SDK project?**
Yes.

2. **What modifications have you made to the Chat SDK?**
None

3. **Android Version:**
NA

4. **Steps taken to reproduce the problem:**
Send a message using iOS or Android

5. **Expected result:**
The sender's name should show in the Push Notification

6. **Actual result:**
![img_2644](https://user-images.githubusercontent.com/1937488/50380772-37225980-0627-11e9-932c-5c316dc0f6d9.PNG)

7. **Comments:**

**Comment by tobimichigan** [comment]
I stand to be corrected, @muhammadsr , I don't c how this  should be a problem. If the app can deliver "notification", I think the job is more than half way done.

**Comment by muhammadsr** [comment]
The notification message is built using the `index.js` file for the firebase cloud function. I guess it's up to you (the user) to modify it if you want to but I fixed it to reflect a proper message notification title with this PR https://github.com/chat-sdk/chat-sdk-android/pull/453/files

**Comment by tobimichigan** [comment]
Yes you are correct.
@muhammadsr , I'm testing this sdk on an alpha channel now. Please could you kindly summarize how you enabled push notifications for this framework?
 I already have FirebasePushModule.activate() on my AppObj class.

**Comment by thecmart** [comment]
@muhammadsr we have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
