### ISSUE TITLE
Manifest merger failed : Attribute application@appComponentFactory

### ISSUE THREAD

**Issue by chetan1011** [chat-sdk/chat-sdk-android#458]
1. **Manifest merger failed : Attribute application@appComponentFactory**

Adding Modules Manually with my project I got this error.
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:17:5-66:19 to override.

Please anyone help me on this issue.

**Comment by tobimichigan** [comment]
If you are having issues with manifest, I think you should recheck your codes, you must have tipped a line or two.

**Comment by bensmiley** [comment]
Looks like you're mixing Support libraries and Android X. See [migration guide](https://developer.android.com/jetpack/androidx/migrate).
