### ISSUE TITLE
Fatal Exception upon Clicking Toolbar in Main Activity

### ISSUE THREAD

**Issue by jmgabriel96** [chat-sdk/chat-sdk-android#460]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**
All I've done is successfully implement messaging.

3. **Android Version:**
Android 7.0

4. **Steps taken to reproduce the problem:**
Upon starting main activity from
  ChatSDK.ui().startMainActivity(getApplicationContext());
And selecting a toolbar option, a fatal exception will occur. Anything other than the toolbar is fine,
5. **Expected result:**
The toolbar option select should bring up another screen.
6. **Actual result:**

```
java.lang.IncompatibleClassChangeError: Class 'co.chatsdk.ui.main.MainActivity$1' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in /data/app/com.example.johnny.fetch-2/split_lib_dependencies_apk.apk)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:788)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1736)
        at
```

7. **Comments:**

Everything is working fine but upgrading to android x has caused several issues when integrating this SDK, but everything seems to have been fixed except for this problem. Any help would be appreciated. Thanks

**Comment by bensmiley** [comment]
This error seems to be related to your own custom code and not the Chat SDK so I'm closing this issue. If you would like us to help with this particular issue you could purchase some [priority support](https://chatsdk.co/downloads/priority-support-block/).
