### ISSUE TITLE
Testing with Admob & Comment on the new ChatSDK update

### ISSUE THREAD

**Issue by tobimichigan** [chat-sdk/chat-sdk-android#465]
1. **Is the bug present in the demo Chat SDK project?** No

2. **What modifications have you made to the Chat SDK?** Refactored

3. **Android Version:** 7.1, Studio 3.2

4. **Steps taken to reproduce the problem:** Tried implementing Admob 

5. **Expected result:** Crashes the App

6. **Actual result:** App crashs on run

7. **Comments:** I think the dependencies need to be updated

Firstly, please could you guys try testing with the Admob dependency? I tried it severally with the latest Admob version and the app keeps crashing wither with Interstitial or Banner ads. Ben Smiley. please could you kindly look into this?

Secondly, I recently tested the new repo and with one or two tweaks, ran well. I observe the AppObj now has the following code:

`if (BuildConfig.DEBUG && FlipperUtils.shouldEnableFlipper(this)) {
            final FlipperClient client = AndroidFlipperClient.getInstance(this);
            client.addPlugin(new InspectorFlipperPlugin(this, DescriptorMapping.withDefaults()));
            client.addPlugin(new NetworkFlipperPlugin());
            client.start();
        }`

It seems as if this code has multiple method entries like: 
BuildConifg
   androidx.multidex
   .co.chat.sdk,firebase,firebasepush,profilepictures,file storage
.facebookflipper

I had to debug 2ce before knowing the exact method it refers to. Its ok by the way, update is good to go!..WITH the exception of the app crashing when conversation is clicked.

**Comment by bensmiley** [comment]
@tobimichigan We are using Admob with one of our clients. 

```
        AdView mAdView = mainView.findViewById(R.id.adView);
        AdRequest adRequest = new AdRequest.Builder().build();
        mAdView.loadAd(adRequest);
```

Gradle:

```
    firebaseAddsVersion = "17.1.2"
    implementation "com.google.firebase:firebase-ads:$firebaseAddsVersion"
```

I hope this helps.
