### ISSUE TITLE
Facebook login issue : after Facebook login successfully load only authentication dialog

### ISSUE THREAD

**Issue by chetan1011** [chat-sdk/chat-sdk-android#466]
Facebook login issue : after Facebook login successfully load only authentication dialog
-> Some device it's work fine 

Work fine in Redmi note 5 , Redmi A5

not work well in Samsung Galaxy S8+

Samsung device also works fine India, but we face the issue in Germany country. 

after login screen just display progress dialog nothing do more

![1547728085930](https://user-images.githubusercontent.com/4546460/51324252-3fd44700-1a90-11e9-8609-fecb48ec6516.JPEG)

**Comment by tobimichigan** [comment]
see my response onissue: Can't execute two auth in parallel #467

**Comment by thecmart** [comment]
@chetan1011 @tobimichigan we have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
