### ISSUE TITLE
Can't execute two auth in parallel 

### ISSUE THREAD

**Issue by chetan1011** [chat-sdk/chat-sdk-android#467]
**Can't execute two auth in parallel**

Currently I am trying to login with facebook but i got error " Can't execute two auth in parallel" .

how can I solved this issue.

Please help me urgent.

**Comment by tobimichigan** [comment]
I think this repo  runs fluently on emails than other federated logins. The other federated ones facebook, phone, twitter are in the works, This is a personal opinion and does not reflect the developers mindset.

**Comment by thecmart** [comment]
@chetan1011 we have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
