### ISSUE TITLE
Request a valid modules download links

### ISSUE THREAD

**Issue by alhazmy13** [chat-sdk/chat-sdk-android#469]
So, we sent to you an email to give us the latest version for some modules that we already pay for it, the links under our profile in `chatsdk.com` is not working and there's no response from you, can you please reply to our email? 

Topic: `Request a valid modules download links`

Thanks

**Comment by tobimichigan** [comment]
Guess this can only be answered by the dev team

**Comment by bensmiley** [comment]
Module links are available here:

[https://chatsdk.co/your-account/](https://chatsdk.co/your-account/)

FYI, our website is chatsdk.co not .com.
