### ISSUE TITLE
Image upload is not working

### ISSUE THREAD

**Issue by omkar1707** [chat-sdk/chat-sdk-android#470]
I have installed the latest apk from the master code base. 
While sending the image to chat thread the app is crashing. Please find attached log.

![screenshot_2019-01-20-10-35-32-765_com miui bugreport](https://user-images.githubusercontent.com/26362645/51585663-3c154a00-1f00-11e9-9f66-e046e37fb494.png)

**Comment by tobimichigan** [comment]
Its just a little bug, if you retry again it will eventually upload.

**Comment by tobimichigan** [comment]
@omkar1707 , I think you are correct. @bensmiley , you should look into this too  ASAP.

**Comment by tobimichigan** [comment]
@omkar1707 , have you been able to resolve this? Or are you still experiencing this?

**Comment by omkar1707** [comment]
@tobimichigan I have not tried with latest commits if any. But with the code that I have, I am facing this issue.

**Comment by tobimichigan** [comment]
Ok, I have communicated this with @bensmiley . Try re-building and let me know what you experience.

**Comment by bensmiley** [comment]
I expect this is fixed in the latest build. If it still persists please reopen.
