### ISSUE TITLE
Unable to send image using sendMessageWithImage .

### ISSUE THREAD

**Issue by himaanshi** [chat-sdk/chat-sdk-android#484]
1. **Is the bug present in the demo Chat SDK project?**
No

2. **What modifications have you made to the Chat SDK?**
created a separate activity to send image . i am using my code to  get image from gallery , path is coming fine , but when i call sendMessageWithImage(filePath, thread) , call is going in throwable 
"Error message " :  java.lang.NullPointerException: Attempt to invoke interface method 'io.reactivex.Observable co.chatsdk.core.handlers.UploadHandler.uploadImage(android.graphics.Bitmap)' on a null object reference

3. **Android Version:**
23 moto device.

4. **Steps taken to reproduce the problem:**
select image from gallery 
Call ChatSDK.imageMessage().sendMessageWithImage(filePath, thread)

5. **Expected result:**
success message  in response of sendMessageWithImage.

6. **Actual result:**
Error : java.lang.NullPointerException: Attempt to invoke interface method 'io.reactivex.Observable co.chatsdk.core.handlers.UploadHandler.uploadImage(android.graphics.Bitmap)' on a null object reference

**Comment by bensmiley** [comment]
Where are you calling `sendMessageWithImage` ? Also, do you have the upload handler enabled?

**Comment by himaanshi** [comment]
In  my custom fragment after selecting image from gallery ,  and how we can  enable upload handler ? 
My code to initialize chatSDK in myApplication : 

        // Create a new configuration
        Context context = getApplicationContext();
        Configuration.Builder builder = new Configuration.Builder(context);

        builder.anonymousLoginEnabled(true);

        // Perform any configuration steps (optional)
        builder.firebaseRootPath("prod");
        // Initialize the Chat SDK
        try {
            ChatSDK.initialize(builder.build(), new FirebaseNetworkAdapter(), new BaseInterfaceAdapter(context));
        } catch (ChatSDKException e) {
            e.printStackTrace();
        }

        FirebasePushModule.activate();

**Comment by bensmiley** [comment]
It's in the [setup instructions](https://github.com/chat-sdk/chat-sdk-android/#initializing-the-chat-sdk).

```
FirebaseFileStorageModule.activate();
```

**Comment by himaanshi** [comment]
Thanx @bensmiley  .
