### ISSUE TITLE
Problem occurred while integrating the chatsdk with my own app

### ISSUE THREAD

**Issue by nirmalbaby1113** [chat-sdk/chat-sdk-android#485]
The problem occurred while integrating with my own app. The integration is done according to the steps which mentioned in chatsdk documentation. But it shows nullpiontererror, means the app crash soon after it opens and gave error (null pointer). I added all repositories and libraries which mentioned in the documentation

**Comment by bensmiley** [comment]
@nirmalbaby1113 can you provide a stack trace? And ideally fill out the issue template?

**Comment by thecmart** [comment]
@nirmalbaby1113 we have made a large number of changes to the App in the last few months. Please can you update to the newest version and check if the problem still persists. If it does then please re-open this issue.
