### ISSUE TITLE
Thread users are not reflected in the Firebase DB

### ISSUE THREAD

**Issue by MuhammedRefaat** [chat-sdk/chat-sdk-android#487]
1. **Is the bug present in the demo Chat SDK project?**
No
2. **What modifications have you made to the Chat SDK?**
Nothing
3. **Android Version:**
API 28
4. **Steps taken to reproduce the problem:**
Creating a new Thread with given users
5. **Expected result:**
The thread to be created in the Firebase db with the users listed there
6. **Actual result:**
The thread is being created successfully bu their are no users attached to it despite adding them to the Thread while creating it
7. **Comments:**
Here is how I create the Thread including my efforts to add users to it but no luck:

```
List<User> users = new ArrayList<>();
        users.add(ChatSDK.currentUser());
        users.add(user);
        Thread thread = fetchThreadWithUsers(users);
        if (thread == null) {
            disposableList.add(ChatSDK.thread().createThread(users)
                    .observeOn(AndroidSchedulers.mainThread())
                    .doFinally(this::hideProgressWheel)
                    .subscribe(thread -> {
                        thread.setMetaValue(SVPreferences.USER_ACTIVE_FOR_CHAT, SVPreferences.ChatActiveStatus.ACTIVE);
                        thread.addUsers(users);
                        ThreadWrapper threadWrapper = new ThreadWrapper(thread);
                        threadWrapper.metaOn();
                        threadWrapper.usersOn();
                        threadWrapper.pushMeta().subscribe();
                        threadWrapper.push().subscribe();
                        ChatSDK.thread().pushThreadMeta(thread);
                        ChatSDK.thread().addUsersToThread(thread, users);
                        ChatSDK.thread().pushThread(thread);
                        ChatSDK.ui().startChatActivityForID(getActivity().getApplicationContext(), thread.getEntityID());
                    }, throwable -> {
                        ToastHelper.show(getActivity().getApplicationContext(), throwable.getLocalizedMessage());
                    }));
        } 
```

**Comment by MuhammedRefaat** [comment]
@thecmart any advice?

**Comment by bensmiley** [comment]
Followed up by email:

Could you try doing the following:

1. Delete that thread from Firebase
2. Delete the app from your test devices
3. Try again

I expect that at some point the Firebase data got corrupted. Now when you run the code, it’s picking up the cached thread so it’s not updating the remote data.

**Comment by MuhammedRefaat** [comment]
Unfortunately still no luck, kindly note I have to exclude jetbrains.annotations and apache.commons from ChatSDK implementations as these libraries are already included earlier in the project and not excluding them causing the app to fail to build:
```
implementation('co.chatsdk.chatsdk:chat-sdk-core:4.6.0') {
        exclude group: 'org.jetbrains', module: 'annotations'
        exclude group: 'org.apache.commons'
    }
```

idk if that would cause this issues but has to mention that in case you think that would be the cause.

**Comment by MuhammedRefaat** [comment]
Something else I believe it my be related, when trying to start a new thread with a user for the first time, I'm always getting the user as null and I've to create a user even if the user is already there in the database, that's how I achieve that:

```
        User user = StorageManager.shared().fetchUserWithEntityID(contactId);
        if (user == null) {
            user = StorageManager.shared().fetchOrCreateEntityWithEntityID(User.class, contactId);
        }
        user.setName(name);
        user.setAvatarURL(imageUrl);
```

**Comment by bensmiley** [comment]
@MuhammedRefaat Is the user a valid contact? In general, to get a user from Firebase you should use the search API. For example:

```
        Disposable d = ChatSDK.search().usersForIndex(userID, 1).subscribe(user -> {

        }, throwable -> {
            
        });
```

**Comment by MuhammedRefaat** [comment]
@bensmiley when calling the method usersForIndex() I never get the callback, it just performs the call with no results in the subscribe or the throwable, and nothing special appears in the logs.

On the other hand, is getting/creating the user the way I'm doing is a valid one for a perfectly added users to the thread? or there is something I'm missing.

**Comment by MuhammedRefaat** [comment]
@bensmiley I found the cause, when connecting to the firebase using the command `builder.firebaseRootPath("");` we are using a path contains spaces (e.g. "Chat SDK path"), and this causes the firebase to create two different roots in the db, one is regular one with spaces and the other with spaces replaced by 20%, and what happens when creating a thread and assigning users to it, is that the thread is being created twice with all the entries in the regular path with spaces, and a thread with the same name is being created in the other path and contains only the users entry.

My suppose is that, while creating the thread you are providing the required unicode to the url, but when adding the users to this thread, you are not doing that which leads to the spaces to be converted to the equivalent char 20%.

I'm navigating through your code to try find the thread users assignment to firebase path but can't find.

**Comment by bensmiley** [comment]
@MuhammedRefaat could you try to use this code:

```
        User user = ChatSDK.db().fetchOrCreateEntityWithEntityID(User.class, entityID);
        Disposable d = ChatSDK.core().userOn(user).subscribe(() -> {
            // User object has now been populated and is ready to use

        }, throwable -> {

        });
```

You will need to verify that the user ID is correct because if it's not, currently nothing will happen (we have introduced a fix into the next version so if the user doesn't exist, this will return an error. 

As to your second point, the root path cannot have any spaces. I've added a check into the code which means that from the next version, it won't be possible to add spaces or special characters to the root path.

**Comment by MuhammedRefaat** [comment]
Noted, changed the user get/create to the method you mentioned, and will change the root path to a new one with no **Spaces**.
