### ISSUE TITLE
Location screen closes instantly after open

### ISSUE THREAD

**Issue by MuhammedRefaat** [chat-sdk/chat-sdk-android#489]
1. **Is the bug present in the demo Chat SDK project?**
No
2. **What modifications have you made to the Chat SDK?**
Nothing, and it's working perfectly there
3. **Android Version:**
8.0.0
4. **Steps taken to reproduce the problem:**
Using ChatSDK UI chat Activity, I'm trying to send the location, once click the + Button and choose 'Location', the location opens successfully but closes instantly once it is getting opened (it takes less than a sec), which not allows me to send the location.
5. **Expected result:**
To send the location successfully from the chat Activity screen
6. **Actual result:**
Location Closes instantly after opening the location screen
7. **Comments:**
I'm initiating the chatSDK like:

```
        Configuration.Builder builder = new Configuration.Builder(context);
        // setting the path
        builder.firebaseRootPath(SVPreferences.CHAT_DB_ROOT_PATH);
        builder.googleMaps(SVPreferences.GOOGLE_API_KEY);// enabling maps messaging
        builder.facebookLoginEnabled(false);
        builder.twitterLoginEnabled(false);
        builder.googleLoginEnabled(false);
        builder.defaultName(dbManager.getMyProfile().getName());
        builder.defaultUserAvatarUrl(dbManager.getMyProfile().getPhotoId());
        builder.setMessageTextColorMe(Utils.getColor(MainActivity.this, R.color.icons));
        builder.setMessageColorMe(Utils.getColor(MainActivity.this, R.color.schoolvoice_blue));
        builder.pushNotificationColor(Utils.getColor(MainActivity.this, R.color.schoolvoice_blue));
        builder.pushNotificationImageDefaultResourceId(R.mipmap.ic_push_logo);
        builder.build();
        // Initialize the Chat SDK
        try {
            ChatSDK.initialize(builder.build(), new FirebaseNetworkAdapter(), new BaseInterfaceAdapter(context));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // File storage is needed for profile image upload and image messages
        FirebaseFileStorageModule.activate();
        FirebaseModule.activate();
        FirebasePushModule.activate();
        UserInterfaceModule.activate(MainActivity.this);
        AppBackgroundMonitor.shared().setEnabled(true);

```

And opening the Chat UI Activity screen using:

`ChatSDK.ui().startChatActivityForID(getActivity().getApplicationContext(), thread.getEntityID());`

**Comment by bensmiley** [comment]
This is a problem with the Google Maps API keys. You need to make sure that you have enabled both Google Places and Google Static Maps APIs as per the [docs](https://github.com/chat-sdk/chat-sdk-android/#enabling-location-messages).

**Comment by tobimichigan** [comment]
@MuhammedRefaat , there is no problem with the Location screen. It is the absence of your SHA1 key on  your firebase cloud computing console that is responsible for your issue. Simply get your sha1 release key from google developer playstore console and add it to:
1. The firebase console project
2. The restriction area in the console.developer.google.com console area

Google now generates a new signing key that is different from your signing key when you release your apk.

You can 
1. put both SHA1 key from your keytool on your system and
2. put the SHA1 key generated by Google play store console 

on

1. Firebase console area
2. Google cloud computing console developer area
One this is done, this issue automatically disappears without further action.

**Comment by MuhammedRefaat** [comment]
@tobimichigan Thank you for your reply, actually I'm already including my app in firebase console, and I'm already using maps in a couple of places in the app and they are working perfectly, only when using the send Location functionality in ChatSDK I'm getting that issue, when debugging a fast return for onActivityResult is being done with an empty intent.

**Comment by MuhammedRefaat** [comment]
@tobimichigan Actually you was right regarding the console, the maps functionality was enabled but the places wasn't, so that's why it was behaving like that.
All I had to do is to add Google Places feature to the project dashboard, and getting the new key, then everything is not perfect, thank you.
