### ISSUE TITLE
Can't delete my own messages in version 4.6.0

### ISSUE THREAD

**Issue by mizukikk** [chat-sdk/chat-sdk-android#490]
1. **Is the bug present in the demo Chat SDK project?**
yes
2. **What modifications have you made to the Chat SDK?**
 Nothing
3. **Android Version:**
8.0.0
4. **Steps taken to reproduce the problem:**
long touch message to delete it
5. **Expected result:**
delete my own messages
6. **Actual result:**
only can delete other's messages

**Comment by bensmiley** [comment]
This has been fixed and will be available in 4.6.1.
