### ISSUE TITLE
Existing Project

### ISSUE THREAD

**Issue by farhanfarooq01** [chat-sdk/chat-sdk-android#50]
Everything is fine without any error...but I have a Question , Should I have to add something in activity.main.xml of my existing project or only write in main.java...as in README There is  code only for MainActivity.java, gradle,

**Comment by kykrueger** [comment]
Sorry, could you clarify. Is this issue about licensing?

**Comment by farhanfarooq01** [comment]
There is error in my mainactivity.xml (my existing project) what i should write there?????

**Comment by farhanfarooq01** [comment]
simple i have problem in launching chat sdk From my Existing project.....(If i skip launch on a button click will it Directly launch??)
