### ISSUE TITLE
MigrationV5 uses unsupported DROP COLUMN

### ISSUE THREAD

**Issue by alexfdz** [chat-sdk/chat-sdk-android#501]
1. **Is the bug present in the demo Chat SDK project?**
Yes

2. **What modifications have you made to the Chat SDK?**
Full customisation

3. **Android Version:**
22-28

4. **Steps taken to reproduce the problem:**
Application migration 

5. **Expected result:**
Schema migration

6. **Actual result:**
Crash

```
Caused by android.database.sqlite.SQLiteException
near "DROP": syntax error (code 1): , while compiling: ALTER TABLE MESSAGE DROP COLUMN TEXT
android.database.sqlite.SQLiteConnection.nativePrepareStatement (SQLiteConnection.java)
android.database.sqlite.SQLiteConnection.acquirePreparedStatement (SQLiteConnection.java:890)
android.database.sqlite.SQLiteConnection.prepare (SQLiteConnection.java:501)
android.database.sqlite.SQLiteSession.prepare (SQLiteSession.java:588)
android.database.sqlite.SQLiteProgram.<init> (SQLiteProgram.java:58)
android.database.sqlite.SQLiteStatement.<init> (SQLiteStatement.java:31)
android.database.sqlite.SQLiteDatabase.executeSql (SQLiteDatabase.java:1752)
android.database.sqlite.SQLiteDatabase.execSQL (SQLiteDatabase.java:1682)
org.greenrobot.greendao.database.StandardDatabase.execSQL (StandardDatabase.java:37)
co.chatsdk.core.dao.DatabaseUpgradeHelper$MigrationV5.runMigration (DatabaseUpgradeHelper.java:111)
co.chatsdk.core.dao.DatabaseUpgradeHelper.onUpgrade (DatabaseUpgradeHelper.java:31)
org.greenrobot.greendao.database.DatabaseOpenHelper.onUpgrade (DatabaseOpenHelper.java:94)
android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:338)
android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:238)
co.chatsdk.core.dao.DaoCore.openDB (DaoCore.java:87)
co.chatsdk.core.dao.DaoCore.init (DaoCore.java:65)
co.chatsdk.core.session.ChatSDK.initialize (ChatSDK.java:82)
...
```

7. **Comments:**

As the documentation specifies, SQLite does not support `DROP COLUMN`
https://www.sqlite.org/faq.html#q11

> SQLite has limited ALTER TABLE support that you can use to add a column to the end of a table or to change the name of a table. If you want to make more complex changes in the structure of a table, you will have to recreate the table. You can save existing data to a temporary table, drop the old table, create the new table, then copy the data back in from the temporary table.

What is the actual need of removing the column if is gonna be empty?

How this is/was working at any point?

**Comment by bensmiley** [comment]
@alexfdz do you find it still works if you comment out migration v5?

**Comment by alexfdz** [comment]
@bensmiley 	yes, #503 fixes this issue
