### ISSUE TITLE
Google Places API for Android deprecated?

### ISSUE THREAD

**Issue by JeffreyKrist** [chat-sdk/chat-sdk-android#507]
The share location functionality isn't working at this moment.

"Google Places API for Android" is deprecated and you can't select this API from Google's dashboard anymore. See https://developers.google.com/places/android-sdk/intro

```
2019-03-19 09:11:24.633 6811-7485/? E/Volley: [104] BasicNetwork.performRequest: Unexpected response code 403 for https://www.googleapis.com/placesandroid/v1/search?key=AIzaSyB7qeG5ntlYzvJbBf7R6H63F_XXXXXX
2019-03-19 09:11:24.644 6811-9650/? E/Places: Places API for Android does not seem to be enabled for your app. See https://developers.google.com/places/android/signup for more details.
```

We also tried the new API, https://cloud.google.com/maps-platform/?apis=maps,places, without any luck.

Can anybody confirm this, please?

**Comment by bensmiley** [comment]
@JeffreyKrist you can do it [here](https://cloud.google.com/maps-platform/places/?apis=places).

**Comment by JeffreyKrist** [comment]
@bensmiley I believe it is deprecated. See https://developers.google.com/places/android-sdk/placepicker, which references to documentation of classes used in https://github.com/chat-sdk/chat-sdk-android/blob/1c0ec4164f78ccd1bd5cf1e1d54fe075eccaf9e3/chat-sdk-ui/src/main/java/co/chatsdk/ui/chat/LocationSelector.java#L8. I can confirm I can't successfully get access to an newly created API: `Places SDK for Android has not been used in project <1234> before or it is disabled`

@bensmiley See https://developers.google.com/places/android-sdk/client-migration for upgrading instructions.

**Comment by MichielElshout91** [comment]
@bensmiley I'm experiencing this problem too. Are there any updates yet?
