### ISSUE TITLE
fetchOrCreateEntityWithEntityID

### ISSUE THREAD

**Issue by aymenhs** [chat-sdk/chat-sdk-android#511]
Hello,
Before the last release 4.6.5 :
- StorageManager.shared().fetchOrCreateEntityWithEntityID works fine to get an entity using it's entity ID (doc: https://github.com/chat-sdk/docs ) 
- It's the case as well for : InterfaceManager.shared().a.startChatActivityForID

Now no longer possible to use methods, please what are the alternatives for both? thanks

**Comment by bensmiley** [comment]
For the first case use:

```
ChatSDK.db().fetchEntityWithEntityID(...);
```

For the second case:

```
ChatSDK.ui().startChatActivityForID(...);
```

**Comment by aymenhs** [comment]
thank you Ben :) I'll try

**Comment by aymenhs** [comment]
Ben,

we discussed last year how to silently authenticate a user , I used :
NM.auth().authenticateWithCachedToken().subscribe() which works fine.

Now , it's deprecated and the  alternative ChatSDK.core() didn't have
any similar method, how can I proceed ? thanks
