### ISSUE TITLE
silently autenticate user

### ISSUE THREAD

**Issue by aymenhs** [chat-sdk/chat-sdk-android#517]
To silently authenticate a user , I used : NM.auth().authenticateWithCachedToken().subscribe() which works fine.
Now , it's deprecated and the  alternative ChatSDK.core() didn't have any similar method, how can I proceed ? thanks

**Comment by aymenhs** [comment]
guys any suggestion? thank you

**Comment by bensmiley** [comment]
You can just call:

```
ChatSDK.auth().authenticate().subscribe(...
```
