### ISSUE TITLE
Website is down ??

### ISSUE THREAD

**Issue by SajjadRaza72** [chat-sdk/chat-sdk-android#518]
Your website is down ? Could you please let me know from when it will be back? or what else?

**Comment by bensmiley** [comment]
Hi @SajjadRaza72 the website should be back online - [chatsdk.co](http://chatsdk.co) if you have a problem accessing it could you let me know?

**Comment by SajjadRaza72** [comment]
Actually i referred the SDK to some of my client, when client tried to buy the additional modules, site was down. We already started working with basic things but now ...... 
Any approximate time to be back online?

**Comment by bensmiley** [comment]
We have moved to a new host and the website is now fully back online.
