### ISSUE TITLE
Creating a one-time public thread to be shared by multiple users

### ISSUE THREAD

**Issue by aumarbello** [chat-sdk/chat-sdk-android#519]
1. **Is the bug present in the demo Chat SDK project?**
N/A
2. **What modifications have you made to the Chat SDK?**
N/A
3. **Android Version:**
N/A
4. **Steps taken to reproduce the problem:**
N/A
5. **Expected result:**
N/A
6. **Actual result:**
N/A
7. **Comments:**
Just like the title of the issue, I want to be able create a single thread to be share by multiple users(across multiple devices) without the thread being recreated. Currently I check the current threads available to the user/device with `ChatSDK.thread().getThreads(ThreadType.Public)` but on another device it will return empty. Is there a way to search public threads on firebase

**Comment by bensmiley** [comment]
The best way to do this is by predefining the thread ID. 

```
public Single<Thread> createPublicThreadWithName(final String name, final String entityID, HashMap<String, String> meta) {
```

If you define the entity ID in advance, you can call this multiple times and it won't overwrite anything. 

There isn't a way to search public threads on Firebase but the public threads will be synchronized when you log in. Then you could get the complete list using:

```
List<Thread> threads =  ChatSDK.thread().getThreads(ThreadType.Public);
```
