### ISSUE TITLE
InterfaceManager.shared().a.startSplashScreenActivity(context);

### ISSUE THREAD

**Issue by theappshed** [chat-sdk/chat-sdk-android#520]
1. **Is the bug present in the demo Chat SDK project?**
No

2. **What modifications have you made to the Chat SDK?**
None

3. **Android Version:**
Min-19, Target-28

4. **Steps taken to reproduce the problem:**
InterfaceManager.shared().a.startSplashScreenActivity(context);

I followed the "Add to existing project" information, and this line gives an issue as InterfaceManager is deprecated

5. **Expected result:**
Should segue through to Login activity

6. **Actual result:**
Deprecation causes failing code

7. **Comments:**
Does the "walk-through" need updating? Could do with instructions on how to segue through to Login page

**Comment by bensmiley** [comment]
Ok, you would need to add this to your manifest:

```
<activity android:name="co.chatsdk.ui.login.SplashScreenActivity">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
</activity>
```

That will launch the splash screen activity when the app starts up and if the user isn't logged in, it will automatically launch the login activity.

**Comment by bensmiley** [comment]
I'll update the walkthrough. The code should be:

```
ChatSDK.ui().startSplashScreenActivity(context);
```

**Comment by theappshed** [comment]
Hi Ben,

 

Thanks for the reply – however, this is being added to an existing app and the Chat section kicks in much further into the app. There’s already a Firebase login screen in place at the start of the app so a FBUser already exists before they get to the chat screen.

I literally just need to be able to segue to the actual chat screen – is that possible.

 

 

Also having a bit of a headache with iOS version too as the pods are use Swift 3, XCode 10.2 is bitching about needing to convert to Swift 4, but I need to revert to 10.1 by the looks of it ☹

 

 

Kind Regards,

Steve Tinkler

 

01325 978488

 

 

Confidentiality and Disclaimer: This E-Mail, and any attachments, contains information which is private and confidential. If you have received this E-Mail in error, please delete the message and notify the sender immediately on 01325 978488. If you are not the intended recipient, please note that you are not authorised to copy, use, disseminate, or take any action based on the contents of this E-Mail. Your attention is also drawn to our terms and conditions which can be found on our website.

**Comment by theappshed** [comment]
Hi Ben,

 

Spot on buddy – many thanks!

 

Kind Regards,

Steve Tinkler

 

01325 978488

 

 

Confidentiality and Disclaimer: This E-Mail, and any attachments, contains information which is private and confidential. If you have received this E-Mail in error, please delete the message and notify the sender immediately on 01325 978488. If you are not the intended recipient, please note that you are not authorised to copy, use, disseminate, or take any action based on the contents of this E-Mail. Your attention is also drawn to our terms and conditions which can be found on our website.
