### ISSUE TITLE
DialogFragment can not be attached to a container view

### ISSUE THREAD

**Issue by jro-j** [chat-sdk/chat-sdk-android#523]
1. **Is the bug present in the demo Chat SDK project?**
Yes

2. **What modifications have you made to the Chat SDK?**
https://www.youtube.com/watch?v=TldTOCoWLko

3. **Android Version:**
Android Studio: compileSdkVersion 28
My android: API 23

4. **Steps taken to reproduce the problem:**
I created a conversation.
and this conversation has been added to the list.
Until here, okay!

When you press backbutton the first time, the application is invoked again and the conversation list is empty.

When you press the backbutton the second time, the app displays the message "is not responding"

5. **Expected result:**
once the backbutton is pressed, the application is terminated

6. **Actual result:**
the application is invoked again and the conversation list is empty.
the app displays the message "is not responding"

7. **Comments:**

>DialogFragment can not be attached to a container view

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: br.com.romtec.testapplication1, PID: 14253
>     java.lang.IllegalStateException: DialogFragment can not be attached to a container view
>         at androidx.fragment.app.DialogFragment.onActivityCreated(DialogFragment.java:460)
>         at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2565)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:907)
>         at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1235)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1301)
>         at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:710)
>         at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2071)
>         at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1861)
>         at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1816)
>         at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1693)
>         at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:560)
>         at androidx.fragment.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:148)
>         at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244)
>         at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092)
>         at androidx.viewpager.widget.ViewPager.onMeasure(ViewPager.java:1622)
>         at android.view.View.measure(View.java:20151)
>         at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
>         at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
>         at android.view.View.measure(View.java:20151)
>         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
>         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
>         at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
>         at android.view.View.measure(View.java:20151)
>         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
>         at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:403)
>         at android.view.View.measure(View.java:20151)
>         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
>         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
>         at android.view.View.measure(View.java:20151)
>         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
>         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>         at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
>         at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
>         at android.view.View.measure(View.java:20151)
>         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
>         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
>         at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3158)
>         at android.view.View.measure(View.java:20151)
>         at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2594)
>         at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
>         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
>         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
>         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
>         at android.view.Choreographer.doCallbacks(Choreographer.java:695)
>         at android.view.Choreographer.doFrame(Choreographer.java:631)
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
>         at android.os.Handler.handleCallback(Handler.java:739)
>         at android.os.Handler.dispatchMessage(Handler.java:95)
>         at android.os.Looper.loop(Looper.java:158)
>         at android.app.ActivityThread.main(ActivityThread.java:7225)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

![Capturar](https://user-images.githubusercontent.com/1641290/56617752-f9ded000-65f6-11e9-9886-c14c0df576da.PNG)

**Comment by bensmiley** [comment]
This has been fixed in the latest version. The back button has been disabled on the main activity.
