### ISSUE TITLE
Firestore for database + Chat SDK for chat in my App

### ISSUE THREAD

**Issue by kanaksony** [chat-sdk/chat-sdk-android#530]
1. **Requirement** 
I have a requirement to integrate chat functionality in my android app. This app has firestore backend with several collections like - Users, cities, etc. 

2. **What I have done so far**
User Signup / login : 
I use firebase for Google login /signup and create user in Firestore database.

     For Chat : I have used following from examples - 

 ```
public void authenticateWithCurrentFirebaseLogin () {
        Disposable d = ChatSDK.auth().authenticate().subscribe(() -> {
            User currentUser = ChatSDK.currentUser();
            createThread("Test Chat",currentUser);
        }, throwable -> {
            Toast.makeText(this, "Error while authenticating with Chat SDK.",
                    Toast.LENGTH_SHORT).show();
        });
    }
```
This creates a User in Realtime database and starts a thread that results in opening a chat window. But, I think this is not the right way.

3. **Android Version:** 8.0.0

4. **Questions:**

How can I correctly execute chat screen between the current logged in user and selected user from list of Users(from firestore)? 
How do I load previous chat each time I come to the same user again?

Thanks,
Kanak

**Comment by bensmiley** [comment]
Hi @kanaksony,

What you have done so far looks to be correct. The only issue is that you should be passing in another user to the conversation. As it is, you are creating a chat with only one user which isn't valid. 

You will need a way to discover the other user's entity ID. The Chat SDK provides a method to do by searching for a user then adding them to your contacts. But you could also create your own way. Once you have the user ID, you can create a chat given that ID like this:

```
public Single<Thread> createPrivateChatWithUser (String userEntityID) {
        return ChatSDK.thread().createThread("", ChatSDK.db().fetchOrCreateEntityWithEntityID(User.class, userEntityID));
}
```

You can then open that thread like this:

    public Completable startPrivateChatActivityWithUser (Context context, String userEntityID) {
        return createPrivateChatWithUser(userEntityID).doOnSuccess(thread -> {
            // Start the chat activity
            ChatSDK.ui().startChatActivityForID(context, userEntityID);
        }).ignoreElement();
    }

**Comment by kanaksony** [comment]
@bensmiley This looks what I need. I will try it my morning and will update you. :)

**Comment by kanaksony** [comment]
Hi Ben, I used following functions -

For fetching the other User - 
```
    public void getUserWithEntityID(String entityID) {
        chatUser = ChatSDK.db().fetchOrCreateEntityWithEntityID(User.class, entityID);
    }
```

For creating chat thread with above User - 
   ```
    public Single<Thread> createPrivateChatWithUser () {
        return ChatSDK.thread().createThread(username, chatUser );
    }
```

Starting Private chat - 
```
  public Completable startPrivateChatActivityWithUser () {
        return createPrivateChatWithUser()
                .doOnSuccess(thread -> {
            **// This code never calls
            ChatSDK.ui().startChatActivityForID(BusinessProfileDetailActivity.this, user_id);**
        }).ignoreElement();
    }
```
Please correct me if I am doing something wrong above.

**Comment by bensmiley** [comment]
@kanaksony This will only work if the ID of the Firestore user is the same as the Entity ID used by the Chat SDK. If they are not the same, when a user logs in, you would need to save their Chat SDK Entity ID to Firestore, and then read this value.

**Comment by kanaksony** [comment]
Thanks @bensmiley this worked.

**Comment by bensmiley** [comment]
Great!
