### ISSUE TITLE
How can I listen for share Intent?

### ISSUE THREAD

**Issue by tefracky** [chat-sdk/chat-sdk-android#532]
Hello,

is it possible to listen to share Intens like "text/plane" or images to send over Chat-SDK?

**Comment by bensmiley** [comment]
At the moment that isn't possible. I can add it as a feature request. Or if you would be interested in adding the feature, I could merge review and merge it if you submit a pull request. If you needed any advice on how to implement it I could also provide support.

**Comment by MuhammedRefaat** [comment]
@bensmiley is it yet available or still not?
