### ISSUE TITLE
Updating from 4.7.x to 4.8.x

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#533]

**Comment by thecmart** [comment]
There is no description of any sort of problem here.

**Comment by zhiyong17** [comment]
error found in manual 4: 
** error above found in authenticateWithCachedToken() method
ChatSDK.auth().**authenticate()**.observeOn(AndroidSchedulers.mainThread())

Details of error:
error: method authenticate in interface AuthenticationHandler cannot be applied to given types;
required: AccountDetails
found: no arguments
reason: actual and formal argument lists differ in length
![error](https://user-images.githubusercontent.com/39132367/67421408-fefef500-f602-11e9-9611-1c7aad945e41.PNG)
