### ISSUE TITLE
Bug with reloading messages.

### ISSUE THREAD

**Issue by ghvvl** [chat-sdk/chat-sdk-android#534]
1. **Is the bug present in the demo Chat SDK project?**
I think no.
2. **What modifications have you made to the Chat SDK?**
No.
3. **Android Version:**
8.1
4. **Steps taken to reproduce the problem:**
Send any message.
Call loadMoreMessagesForThread().
5. **Expected result:**
one message was added.
6. **Actual result:**
2 same messages was added.
7. **Comments:**
I think error is in merge 2 lists - localMessages and removeMessages (need skip same messages).

**Comment by thecmart** [comment]
@ghvvl Hello, we have not been able to re-create the problem. Can you please check that you are running the latest version of Chat SDK 4.8.2a3. If so, please can you post the debugger data that you receive the next time that it happens. The line `loadMoreMessagesForThread` occurs in many places in the software, making it difficult to pinpoint a location in the code where the error may be occurring.

**Comment by ghvvl** [comment]
@bensmiley Why you closed my issue?

**Comment by ghvvl** [comment]
@thecmart Hi. I use Chat SDK without ui module. I call loadMoreMessagesForThread directly (for now i use workaround where I check date for equals Date(0)), without this workaround i have list with duplicate elements (I debugged this and  in FirebaseThreadHandler loadMoreMessagesForThread in list was added same elements .

**Comment by bensmiley** [comment]
@ghvvl have you tested this with the latest version of the code?

**Comment by ghvvl** [comment]
> @ghvvl have you tested this with the latest version of the code?

I use 4.8.2 version of ChatSDK in my project.

**Comment by bensmiley** [comment]
Can you how me how exactly you are using this code snippet?

**Comment by ghvvl** [comment]
@thecmart @bensmiley Hi. I use this method to loading messages for thread.

 ` fun loadMessages(
        thread: Thread,
        date: Date
    ): Single<List<Message>> =
            ChatSDK
                    .thread()
                    .loadMoreMessagesForThread(
                        date,
                        thread,
                        date != Date(0)
                    ) //We need to load from server when we load second or next pages.
                    .observeOn(AndroidSchedulers.mainThread())`
