### ISSUE TITLE
Do I need to create a new firebase project of my own if I want to use SDK,or all of the datas are in your project.

### ISSUE THREAD

**Issue by moo611** [chat-sdk/chat-sdk-android#536]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
You need to make your own Firebase project because we wipe down our project regularly. You can follow the setup instructions to setup your client to connect to your Firebase Database.
