### ISSUE TITLE
Message getting delay from receiver side at first time ?

### ISSUE THREAD

**Issue by kalanidhidev** [chat-sdk/chat-sdk-android#538]
I have fetched the user using  meta data and create a thread. I able to get the user object and create the thread. But first time when I send the message , receiver not able to receive at the moment later they got the message. Some time two thread created in single users  while listing user message list.
```

 CustomSearchHandler()
                .usersForIndex(userId.toString())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe({ user ->
                      disposableList.add(
                            ChatSDK.thread()
                                    .createThread("", user, ChatSDK.currentUser())
                                    .observeOn(AndroidSchedulers.mainThread())
                                    .subscribe(
                                            { thread ->
                                                ChatSDK.ui().startChatActivityForID(context, thread.entityID)
                                            },
                                            { throwable ->
                                                ToastHelper.show(context, throwable.localizedMessage)
                                            }
                                    ))

                }, {
                    Log.d("Error", Gson().toJson(it))
                })
```

**Comment by Harishiv** [comment]
ChatSDK Team, 

Do we have any update on the issue described above? We are looking forward to get this clarified and resolved asap for proceeding the integration with project.

**Comment by bensmiley** [comment]
Hi @Harishiv, the code you're using looks good. Could you describe the actual issue you're having in more detail? I'm not clear what the issue is. If you need to get in touch more directly, you can visit [slack.sdk.chat](http://slack.sdk.chat).
