### ISSUE TITLE
does this sdk require android x?

### ISSUE THREAD

**Issue by zaidzak9** [chat-sdk/chat-sdk-android#539]
Does your chat sdk require my android project to be migrated to ANDROID X??

**Comment by bensmiley** [comment]
Yes, the project uses Android X which means that you should migrate your project if you intend to use it. It is highly recommended to update to Android X anyway because the support libraries are deprecated. The process is usually quick and easy.

**Comment by zaidzak9** [comment]
Thankyou very much for the quick response.
