### ISSUE TITLE
Does ChatSDK XMPP support push notifications?

### ISSUE THREAD

**Issue by chriswoolfe** [chat-sdk/chat-sdk-android#540]
1. **Is the bug present in the demo Chat SDK project?**
Yes. 
2. **What modifications have you made to the Chat SDK?**
None
3. **Android Version:**
Yes
4. **Steps taken to reproduce the problem:**
I downloaded the XMPP demo app from https://i.diawi.com/mE5GkM I created an account. I did the same on another phone. I can text back-and-forth with the app open, but when the app goes to the background (phone screen is off, but the phone is on), no push notification is received when a message is sent from another phone. 

5. **Expected result:**
When another phone sends a message, the recipient phone will get a push notification

6. **Actual result:**
No push notification is received. 

7. **Comments:**
Looking at the website, it isn't clear if this is a bug or just not-included functionality.

**Comment by bensmiley** [comment]
Hi @chriswoolfe actually push notifications aren't currently enabled for the current demo app but they do work when setup. I'll set them up on the demo app in the next few days.

**Comment by chriswoolfe** [comment]
Ok thanks for that clarification!
