### ISSUE TITLE
How cutomize the chat screen and how to delete a paticular thread?

### ISSUE THREAD

**Issue by zaidzak9** [chat-sdk/chat-sdk-android#541]
Hi

Im finding it hard to customize the screen can some one tell me how to? and also how do i delete a particular thread?

Thanx in advance

**Comment by bensmiley** [comment]
Have you looked at these documents: [1](https://github.com/chat-sdk/docs/blob/master/Android%20Customize%20UI.md), [2](https://github.com/chat-sdk/docs#customizing-the-user-interface)?

**Comment by zaidzak9** [comment]
> Have you looked at these documents: [1](https://github.com/chat-sdk/docs/blob/master/Android%20Customize%20UI.md), [2](https://github.com/chat-sdk/docs#customizing-the-user-interface)?

Thankyou for the response :)
