### ISSUE TITLE
Auth without UI

### ISSUE THREAD

**Issue by azentner1** [chat-sdk/chat-sdk-android#544]
Is it possible to authenticate a user without invoking Firebase UI?

I have a custom UI for phone number registration - that works fine, but when i try to auth a user with ChatSDK i get `ChatError, Code: 106, CoreMessage: No auth bundle found, Tag: null`. 
Any thoughts?

**Comment by thecmart** [comment]
@azentner1 Hello Azentner, in order for us to find this error we are going to need more information about how it is caused. Can you please post your entire error report here, as well as any changes that you may have made to the Chat SDK code itself.
