### ISSUE TITLE
Issue after added a module

### ISSUE THREAD

**Issue by ajuarmia** [chat-sdk/chat-sdk-android#548]
Demo chat app working properly.But after added a new module chat sdk contact book, i am getting the error message     

```
java.lang.IllegalAccessError: Method 'void co.chatsdk.core.base.AbstractAuthenticationHandler.setAuthStateToIdle()' is inaccessible to class 'co.chatsdk.firebase.-$$Lambda$uGm_CejYsNazMka97kJYXdvzfK0' (declaration of 'co.chatsdk.firebase.-$$Lambda$uGm_CejYsNazMka97kJYXdvzfK0' appears in /data/app/co.chatsdk.android.app-z0YWwgn2uQdvInafQ-axsQ==/split_lib_slice_3_apk.apk)
```

Please support to solve this issue
![Screenshot from 2019-07-03 15-05-31](https://user-images.githubusercontent.com/52490196/60581521-9ca88d00-9da4-11e9-85c4-33fcf645a28f.png)

**Comment by bensmiley** [comment]
Hi @ajuarmia it's possible that this is caused by a Gradle flag being set to the wrong value. If you have checked out the Chat SDK project from Github then added the module, you would need to set:

```
useLocal=true
```

In `gradle.properties`
