### ISSUE TITLE
Actions UI that includes Location and image options

### ISSUE THREAD

**Issue by anabsys** [chat-sdk/chat-sdk-android#550]
I want to edit the ui of the actions that includes location, Take photo and chose photo when + button is clicked in chat but don't know how to because i don't know which layout to modify. Please guide me.

**Comment by bensmiley** [comment]
@anabsys how would you like to modify these actions? Could you give me a screenshot of the screen you are referring to?

**Comment by anabsys** [comment]
Currently I don't have, I was just thinking to..currently I need guidance on these topics:

1.)  I have enabled Login with firebase Ui, but after user is logged in, if he closes and opens the app, the first layout is seen is of Login button, but the button is not clicked, user is automatic logged in then, how to resolved this by adding something like progressbar, or like circular progressbar the one in splash screen, etc

2.) I have disabled chat room, but also want to remove that option from the action bar that includes conversation, chat rooms, contacts and profile

3.)How to change the logo for chatsdk, such that my logo is different but when I view this app in recent apps, chatsdk logo is showing

4.) How can I add admob

Please guide me
