### ISSUE TITLE
Need help on some topics

### ISSUE THREAD

**Issue by anabsys** [chat-sdk/chat-sdk-android#551]
1.) I have enabled Login with firebase Ui, but after user is logged in, if he closes and opens the app, the first layout is seen is of Login button, but the button is not clicked, user is automatic logged in then, how to resolved this by adding something like progressbar, or like circular progressbar the one in splash screen, etc

2.) I have disabled chat room, but also want to remove that option from the action bar that includes conversation, chat rooms, contacts and profile

3.)How to change the logo for chatsdk, such that my logo is different but when I view this app in recent apps, chatsdk logo is showing

4.) How can I add admob

Please guide me

**Comment by kanaksony** [comment]
I too am interested for #3.

**Comment by anabsys** [comment]
> I too am interested for #3.

Heyy can u please tell how to add admob.. as i am writing the implementation code, it is giving duplicate error..
