### ISSUE TITLE
Forward message with error "DatabaseError: Permission denied"

### ISSUE THREAD

**Issue by t146150** [chat-sdk/chat-sdk-android#552]
When I do forward message, it often shows DatabaseError: Permission denied, after that it was not allow me to do long click action.
I checked log, it show 
```W/RepoOperation: setValue at /develop/threads/-Lj0QBvWjtysy3vnCoxJ/messages/4e79349b-2cb6-4499-a317-dce4b91e13ab failed: DatabaseError: Permission denied```

**Comment by t146150** [comment]
I use newest sdk and newest rule but it show same error

**Comment by thecmart** [comment]
Hello @t146150, thank you for alerting us to this this is a problem. It is one that we have recently encountered in the newer versions. We are working on getting it fixed at the moment. We will let you know when we do.

**Comment by gitroshan** [comment]
Any update on this issue? We are still having this issue.
