### ISSUE TITLE
How to change color of ChatScreen to match my app color theme?

### ISSUE THREAD

**Issue by kanaksony** [chat-sdk/chat-sdk-android#559]
1. **Is the bug present in the demo Chat SDK project?**
No

2. **What modifications have you made to the Chat SDK?**
Nothing

3. **Android Version:**
9.0

Question: How can I change default color chat screen to my app's theme color? My app is having orange everywhere and chat screen opens with blue theme i.e. toolbar, add, back, send buttons all are blue.

How can I change these to orange?

Thanks,
Kanak

**Comment by kanaksony** [comment]
Any help?

**Comment by YAMexchange** [comment]
Hi - how do you change this setting - We are also having trouble finding where to do it.
Thanks- Stephen

**Comment by aymenhs** [comment]
did you try changing styles under chatsdk-ui ?

![chatsdktheme](https://user-images.githubusercontent.com/1870186/62299726-c2918200-b475-11e9-802b-014dfa5dbd07.png)

**Comment by kanaksony** [comment]
There should be some configuration for these changes.

**Comment by bensmiley** [comment]
@kanaksony to do this you will need to subclass the ChatActivity and register your subclass with the framework. You can then provide your own customized xml file. See [this guide](https://github.com/chat-sdk/docs/blob/master/Android%20Customize%20UI.md).
