### ISSUE TITLE
FetchEntityWithEntityID returns null

### ISSUE THREAD

**Issue by Perick95** [chat-sdk/chat-sdk-android#561]
Hi, 
I've integrated the ChatSDK in my application and what I want to do now is to open the ChatActivity from an activity on my application. In order to do that I execute this code:

```
Disposable d = ChatSDK.thread().createThread("", user, ChatSDK.currentUser())
                        .observeOn(AndroidSchedulers.mainThread())
                        .doFinally(() -> {
                            // Runs when process completed with error or success
                        })
                        .subscribe(thread -> {
                            // When the thread is created
                            ChatSDK.ui().startChatActivityForID(getContext(), thread.getEntityID());
                        }, throwable -> {
                            // If there is an error
                            Timber.e(throwable);
                        });
```

This call works well and create the thread if it does not exist or retrieve the thread if it already exists. My problem is how can I retrieve the variable user having its EntityId? I have tried with this method:

`User user = ChatSDK.db().fetchEntityWithEntityID(String.valueOf(baseUser.getEid()), User.class);`

But when the chat is not already created, the function return null even if the user exists on firebase. How can I resolve this issue?

Thanks.

**Comment by amitkvyas** [comment]
any update?

**Comment by bensmiley** [comment]
Here is the recommended way:

https://chat-sdk.gitbook.io/chat-sdk/guides/api-cheatsheet#examples

```
// Get a user and update their proifle from the server 
ChatSDK.core().getUserForEntityID("User Entity ID").subscribe(otherUser -> {

}, throwable -> {

});
```
