### ISSUE TITLE
Thread data lost after deleting app data

### ISSUE THREAD

**Issue by uszkaisandor** [chat-sdk/chat-sdk-android#564]
How can I prove that thread data is ALWAYS up-to-date with Firebase, when I start chat activity with the given thread ID?

1. **Is the bug present in the demo Chat SDK project?**
I am not able to test it
2. **What modifications have you made to the Chat SDK?**
Nothing what affects thread sync
3. **Android Version:**
9.0 (API 28)
4. **Steps taken to reproduce the problem:**
Write some messages to thread, delete app data, then reload app and start activity with thread
5. **Expected result:**
Sync data from firebase
6. **Actual result:**
ChatSDK loads data from local db which is empty
7. **Comments:**

**Comment by bensmiley** [comment]
@uszkaisandor it sounds like something with your setup is incorrect. This could be caused by using a root path with special characters or a failure to call the `ChatSDK.auth().authenticate` method each time the app starts.

**Comment by uszkaisandor** [comment]
@bensmiley 
I think that there isn't any authentication error. 
I am changing messages' meta for customize message data, but the GreenDao only saves the messages's data for the first time. I am able to modify the data with threadMetaChanged subscription, if I am currently in that particular thread, but I want to ensure that all of the messages in the DB synchronized with the Firebase.

Can I do this with the ChatSDK?
