### ISSUE TITLE
Bug report: FirebaseReferenceManager incorrectly store references for Firebase Query

### ISSUE THREAD

**Issue by beyondeye** [chat-sdk/chat-sdk-android#574]
1. **Is the bug present in the demo Chat SDK project?**
N/A
2. **What modifications have you made to the Chat SDK?**
N/A
3. **Android Version:**
N/A
4. **Steps taken to reproduce the problem:**
N/A
5. **Expected result:**
N/A
6. **Actual result:**
N/A
7. **Comments:**

I was debugging the code for FirebaseReferenceManager class and realized that if the
argument of the various methods of the class is an actual Firebase Query, and not a DatabaseRerefence (that inherits from Query) the toString() method is not defined, and the
reference stored is not the firebase path but instead the  result of the default Object.toString() method.
In order to fix this, it is necessary in ALL methods of FirebaseReferenceManager that take a query parameter, to do something like this:

```
    public void addRef (Query query, ChildEventListener l) {
        DatabaseReference ref=query.getRef();
        references.put(ref.toString(), new Value(ref, l));
    }
```

instead of the original code 
```
    public void addRef (Query ref, ChildEventListener l) {
        references.put(ref.toString(), new Value(ref, l));
    }
```

**Comment by bensmiley** [comment]
This has been fixed and will be released with the next version.
