### ISSUE TITLE
Messages are being pushed but notification won't show on either phone! (Android-To-Android)

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-android#58]
I know i closed this issue earlier but my notifications still aren't working! I know that when i first started my project, the notifications did indeed work but for some reason they now won't.

All my keys are setup correctly so it shouldn't be anything to do with that. I simply don't know what it can be

LogCat snips:  

     31081-31081/com.skintmedia.voice V/BBackendlessHandler: Message published to channel:useriwH7vE6f0ogXiONf65gTMok32Uw2

     03-28 18:31:44.761 31081-31081/com.skintmedia.voice V/BMessageWrapper: push message, onDone
     03-28 18:31:44.763 31081-31081/com.skintmedia.voice V/BFirebaseNetworkAdapter: pushForMessage

**Comment by RyanElliott94** [comment]
Sorry i had to close this one too! it turns out that i am a massive idiot and disable notifications for private threads haha

**Comment by Allansk2** [comment]
Hi, @RyanElliott94 
I just started to use the sdk, still looking details, but I got same issue, where can I enable notifications for private threads, thanks
