### ISSUE TITLE
Multiple firebase projects

### ISSUE THREAD

**Issue by Ashi803** [chat-sdk/chat-sdk-android#582]
Hi. I have an app which uses a primary firebase project for it's other functions. I would like to connect the chatsdk only to another firebase project. I don't think there is a way to do that.

` switch ( details.type ) {
                        case Username:
                            FirebaseAuth.getInstance().signInWithEmailAndPassword(details.username, details.password).addOnCompleteListener(resultHandler);
                            break;`

It would be great if we can change the getInstance() to something like getInstance("secondProject");

**Comment by bensmiley** [comment]
This has been added in v4.8.4 - see [update guide](https://github.com/chat-sdk/chat-sdk-android).
