### ISSUE TITLE
Unable to fetch the message after killing the app but able to send the message please provide the solution for it.

### ISSUE THREAD

**Issue by npaulConnvertex** [chat-sdk/chat-sdk-android#583]
I have actually installed the modules in my existing react native project
 I have just changed the ui look and feel of just the chatActivity

What i have done is pass a threadentityid from react native screen to ChatActivity using the NativeModules.

The ChatActivity opens up, the chat works for the first time perfectly, i.e chat messages are received and sent, but once the app is closed and opened for the second time, the chatActivity does not receive the messages however it is able to send messages over the thread.

To check once more i cleared data and cache of the app and opened it once again to see if meesages are received or not. It works but again if we close it and open same thing happens.

The listener does not get added on the second time .  I checked using console.

**Comment by bensmiley** [comment]
@npaulConnvertex can you please provide more details about this issue? You need to fill out the issue template otherwise it's not possible for us to help.

**Comment by npaulConnvertex** [comment]
Yes now the issues is solved. 

Previously i just Autheticated only if ChatSDK.currentuser()  gave a null value.. It worked but i think it had failed to initialize the listeners as you said.

So yes now calling ChatSDK.auth().authenticate() everytime and is getting the job done. 
Thank you @bensmiley
