### ISSUE TITLE
App hangs after authenticate completes

### ISSUE THREAD

**Issue by lbadias** [chat-sdk/chat-sdk-android#589]
This is a bug originally reported on the iOS version. But it is present on the android version too.

Using Firebase version.

1. Is the bug present in the demo Chat SDK project?
Yes

2. What modifications have you made to the Chat SDK?
Nothing

3. Android Version? Device or simulator?
Device (Samsung), Android 7.0

4. Steps taken to reproduce the problem:
call authenticate if user have large data in chat ( 200 Threads with 20+ messages , which isn't much)

5. Expected result:
app should work smoothly

6. Actual result:
app hangs after we authentication completes , it takes few mins to sync and in that time app hangs.

Comments:
Any support on this?, even if we have to pay for it

**Comment by bensmiley** [comment]
Hi @lbadias is there any chance you could provide me with your codebase and a login which presents this issue? I'd be happy to look at it to see where the bottleneck is happening.

**Comment by lbadias** [comment]
Hi @bensmiley, is there any way I could send to you privately? 

I have updated the demo (version 4.8.4) with an updated Firebase configuration, authenticating via Custom Token.

**Comment by mwaqassatti** [comment]
@bensmiley Any solution to this problem, i face the same issue.
When the app is launched and after initialing the chatsdk and if user have lot of chat history then on opening the threads list screen hangs it takes 20 sec to settle up. After that it works fine. I thing it's loading the chat history but this should be background thread.
Any clue to how to resolve this issue. Thanks
