### ISSUE TITLE
Gradle Sync Errors  - Android SDK

### ISSUE THREAD

**Issue by RajMobile** [chat-sdk/chat-sdk-android#592]
I downloaded Android Studio and created an empty project MyApplication.

1) Downloaded SDK for Android and Imported all available functions (firebase_plugin, facebook etc. were not there, instead Social etc.
2) Followed https://github.com/chat-sdk/chat-sdk-android/blob/master/README
3) Created Firebase and also Deployed 
4) Followed https://github.com/chat-sdk/chat-sdk-android/wiki/Chat-SDK-Android:-Adding-Chat-SDK-to-your-existing-project. 
5) Followed up to adding import braunster in the main activity.
Gradle sync fails 
1) Said firebase_plugin project not found, so I removed that compile statement
2) Now says minSDK used is 15 should be atleast 16. so I changed minSDKVersion=16 in 'mobile' application

It still gives same error, not sure where is it picking 15 from.
It suggests to add tools:overrideLibrary="com.google.android.libraries.places" , but not sure which manifest file to add it in.
thanks
Raj

**Comment by RajMobile** [comment]
Found it and the MINSDK issue is resolved. I set the value in gradle.properties.
One error: 
ERROR: Failed to resolve: co.chatsdk.chatsdk:chat-sdk-firebase-push:4.8.4.3

**Comment by RajMobile** [comment]
This is resolved too, !

**Comment by maironsoft** [comment]
> ERROR: Failed to resolve: co.chatsdk.chatsdk:chat-sdk-firebase-push:4.8.4.3

Hi @RajMobile. How did you solve this?

Thanks!
