### ISSUE TITLE
profile photo gets reverted (removed)

### ISSUE THREAD

**Issue by mshenawy22** [chat-sdk/chat-sdk-android#594]
1. **Is the bug present in the demo Chat SDK project?**
YES
2. **What modifications have you made to the Chat SDK?**
No

3. **Android Version:**
Android 9-8
4. **Steps taken to reproduce the problem:**
profile 
click on the profile avatar 
select image from the gallery , crop , press the tick (ok)
go to chats , go back to profile 
profile photo disappears

5. **Expected result:**
profile photo should presist 

6. **Actual result:**
profile photo disappears
7. **Comments:**

**Comment by devindercnw** [comment]
hello @mshenawy22  i am getting permission denied error. Can you help me?

**Comment by hristoyordanov** [comment]
I have the same problem - and all my users too. It's strange because I didn't have it in the beginning but suddenly it started happening without changing anything.
