### ISSUE TITLE
Firebase Database error: Permission Denied

### ISSUE THREAD

**Issue by devpranav2104** [chat-sdk/chat-sdk-android#595]
1. **Is the bug present in the demo Chat SDK project?**
No

2. **What modifications have you made to the Chat SDK?**
Not any
3. **Android Version:**
8

4. **Steps taken to reproduce the problem:**
When user1 wants to message to user 2. it doesn't open next screen with message box
5. **Expected result:**
 to send message to user 2
6. **Actual result:**
it shows toast message with Firebase Database error: Permission Denied
7. **Comments:**

**Comment by aymenhs** [comment]
you've to verify your database access rules
I used those ones :
https://github.com/chat-sdk/chat-sdk-firebase/blob/master/chat-sdk-rules.json
