### ISSUE TITLE
Import as Fragment

### ISSUE THREAD

**Issue by TheEnigmist** [chat-sdk/chat-sdk-android#60]
I find this framework really interesting, but what i'm looking for is a way to add it to my project. I've a Fragments based app, and i'm able to start ChatSDKLoginActiviy from one Fragment. Now i'm looking to start it "inside" that fragment, so i will have a fully integrated ChatSDK with my tabs and fragments. I see that ChatSDK is Activity based, so there is an easy way to chage it to works like a fragment?

**Comment by kykrueger** [comment]
Hello, 

The login activity could be adapted to a fragment with only a few changes. We would be happy to quote these as a customization, but if you would like to make the adaptation yourself, please see the following suggestions.

1. Make copies of [ChatSDKAbstractLoginAcitivity](https://github.com/chat-sdk/chat-sdk-android/blob/master/sdk/src/main/java/com/braunster/chatsdk/activities/abstracted/ChatSDKAbstractLoginActivity.java), and [ChatSDKLoginActivity](https://github.com/chat-sdk/chat-sdk-android/blob/master/sdk/src/main/java/com/braunster/chatsdk/activities/ChatSDKLoginActivity.java). 
1. Rename these copies to suit their function (ex. ChatSDKLoginFragment).
1. Change the parent class of ChatSDKAbstractLoginFragment from ChatSDKBaseActivity to ChatSDKBaseFragment.
1. Find and fix all of the code broken by making this change (starting with a new Layout resource for your login fragment).

As for other functionality within the SDK, our Threads, Contacts, and Profile views are already implemented as fragments. However, the remaining pages such as chats and userSearch are also activity based, and I would recommend leaving them as is.

If you are interested in a quote, you can reach us at our email support@chatsdk.co , and you can find some details on pricing for priority support [here](http://chatsdk.co/downloads/priority-support-block/).
-- Kyle

**Comment by amanzan** [comment]
@kykrueger Those activities do not exist anymore, how could I adapt the login to a Fragment with the current codebase?

**Comment by bensmiley** [comment]
It's just called [LoginActivity](https://github.com/chat-sdk/chat-sdk-android/tree/master/chat-sdk-ui/src/main/java/co/chatsdk/ui/login) now.
