### ISSUE TITLE
Doesn't work out-of-the-box and tutorial is out-dated

### ISSUE THREAD

**Issue by dutchplayers** [chat-sdk/chat-sdk-android#602]
1. **Is the bug present in the demo Chat SDK project?**
No
2. **What modifications have you made to the Chat SDK?**
I tried the tutorial twice and i tried to implement some things from the tutorial to the updated source code.
3. **Android Version:**
Not launched on a phone or emulator yet because it won't build.
4. **Steps taken to reproduce the problem:**
Out-of-the-box gradle build sync will work. Running the app will cause errors.
5. **Expected result:**
```
C:\DutchPlayers\DPChat\App1\chat-sdk-micro\src\main\java\sdk\chat\micro\message\Sendable.java:
uses unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.
```
6. **Actual result:**
With -Xlint:unchecked

> error: messageStream has protected access in AbstractChat

 FirestoreEventHandler.java line 24: 
```
Disposable d = MicroChatSDK.shared().messageStream.subscribe(message -> {
```
7. **Comments:**
Were do i need to start with out-dated tutorials?

**Comment by bensmiley** [comment]
I've just pushed a fix, can you try again now?

**Comment by dutchplayers** [comment]
I can run the app now, thank you
