### ISSUE TITLE
How to integrate chat functionality in my app :(

### ISSUE THREAD

**Issue by losocarrat** [chat-sdk/chat-sdk-android#603]
1. I don't want to create a chat app.
2. Nobody wants to create a chat app.
3. There are already many chat apps.
4. What everyone wants is to INCLUDE A BASIC CHAT FUNCTIONALITY in 
their own app. In an activity of your own existing app.
5. Why does nobody explain this?

I have already created my own app (kotlin). 
I have already integrated the sdk api into my app.
I just need a basic chat functionality in an activity of my app.
A brief guide, a summary, a charitable help, a clue where to start, something ...?

Thanks a lot!!

**Comment by bensmiley** [comment]
If you have a Firebase app, add the Chat SDK to your project using the documentation then just call 

```
ChatSDK.auth().authenticate().subscribe(() -> {
                
});
```

After your user has logged in and:

```
ChatSDK.auth().logout().subscribe();
```

When they log out. Then you can use the activities freely in your app:

```
ChatSDK.ui().getChatActivity();
```

For example.

**Comment by rikongha** [comment]
any luck with this? I am going down the same route and could use some assistance
