### ISSUE TITLE
Android Auto compatibility issue

### ISSUE THREAD

**Issue by o9simon** [chat-sdk/chat-sdk-android#607]
The commit made on Dec 19 2019 adds support for Android Auto. Problem is, the ChatSDK core manifest specifies that the app uses Android Auto and so, when uploading an app to the Play Store, it gets rejected since it's not compliant with the Android Auto standards which are very strict. Can we make this an option please? In the meantime, I'll use an older version.

**Comment by bensmiley** [comment]
Why was it rejected? Can you share some details?

**Comment by o9simon** [comment]
When I uploaded the build, it told me I need to opt in the Android Auto program. I didn't really think about it, just checked the option. Re-uploaded and sent my APK to the Play Store, it got rejected an hour later.

The message is:

At this time, we are only accepting apps within the Media or short form Messaging categories for Android Auto. Media apps that use TSS engine readout for content are not permitted at this time.

You can choose to exclude your app from Android Auto:
[...]
| 1. | Remove the Android Auto manifest entry from your APK code.
| 2. | Sign in to your Play Console and upload the new APK.
| 3. | Submit the update to your app.

So I thought that was odd, I didn't add anything about Android Auto to my manifest. What I found is that the only entry about Android Auto (so far as I know) is at https://github.com/chat-sdk/chat-sdk-android/blob/master/chat-sdk-core/src/main/AndroidManifest.xml at line 17.

**Comment by o9simon** [comment]
For those that have the same problem, I downgraded to 4.8.2, rebuilt the APK and resubmitted to the Play store.

**Comment by bensmiley** [comment]
@o9simon did you try adding this to your manifest:

```
<meta-data android:name="com.google.android.gms.car.application"
            android:resource="@xml/automotive_app_desc" tools:node="remove" />
```

**Comment by o9simon** [comment]
Thanks, I will try it the next time I update my app.

Would this have any effect on any code in ChatSDK that expect this to be set in the manifest?
