### ISSUE TITLE
Firebase rules file not available

### ISSUE THREAD

**Issue by Bendor** [chat-sdk/chat-sdk-android#609]
Hi! I have tried load firebase rules file from documentation:
https://github.com/thecmart/manuals/blob/master/Tutorials/Manual%203%20Integrating%20ChatSDK%20into%20the%20new%20project.md

But the rules file 'https://github.com/chat-sdk/chat-sdk-android/blob/master/firebase-rules.json' not found:
![image](https://user-images.githubusercontent.com/4973472/75063843-cc083780-54f6-11ea-8bae-ae51af773a08.png)

Could you please upload rules file again? Thanks

**Comment by rikongha** [comment]
you can get the file https://github.com/chat-sdk/chat-sdk-firebase/blob/master/firebase.json

**Comment by WlanWerner** [comment]
Referenced to #568
