### ISSUE TITLE
Google Play rejecting my app because of an SSL Error?

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-android#61]
So just as the title says, my app is being rejected of that error?

I tried removing `OnReceivedSslError` but that hasn't worked?

It is important that i get this sorted quickly!

Thanks

Ryan

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

Hopefully @kykrueger will know what is causing this error. 

I have done some searching online and have attached the links to a number of different possible solutions to try:

1. [here](http://stackoverflow.com/questions/24197777/google-play-and-openssl-warning-message)
2. [This](http://stackoverflow.com/questions/38187257/how-to-determine-which-dependency-causes-google-play-openssl-warning) might help you identify which dependancy is causing the issues.
3. [This](https://forum.starling-framework.org/topic/security-alert-you-are-using-a-highly-vulnerable-version-of-openssl-1) article seems to suggest checking that the OpenSSL version is up to date. The current stable version seems to be 1.1.0.

Hopefully this helps and we will do some testing on our end to see if we can get this issue fixed.

Simon

**Comment by kykrueger** [comment]
Hi @RyanElliott94 , 


We recently had issue #32 which showed the same problem you are describing. The cause was that our backendless library was out of date, and the issue has since been patched. Could you merge the recent master branch into your clone of the chat sdk? 

If this isn't possible due to customizations that you have made, please update the include in this [build.gradle](https://github.com/chat-sdk/chat-sdk-android/blob/master/sdk/build.gradle) file.

```
compile 'com.backendless:backendless:3.0.20'
```

Hope this helps!
-- Kyle

**Comment by RyanElliott94** [comment]
This reply is a little late but yeah it was because of that! i remembered seeing other issues people had on the backendless forum! So the app is released now

Please let me know if you want me to remove the link but here's the app! [https://play.google.com/store/apps/details?id=com.skintmedia.voice&hl=en_GB](url)

**Comment by kykrueger** [comment]
Right on!

Glad to see you got your app into the store. 
Hope to see you stick around and include our next major update when it is finished!

-- Kyle

**Comment by simonsmiley64** [comment]
@RyanElliott94,

The app looks great, we loving seeing what people are doing with the Chat SDK. 

Keep us updated on how the app goes: team@chatsdk.co

Simon

**Comment by bensmiley** [comment]
@RyanElliott94,

The app looks great. One thing I noticed is that the user names are defaulting to Chatcat.... You could change this to be VoiceUser.... 

Also, we like to showcase projects that are using Chat SDK. We can do this by adding it to the Chat SDK portfolio, by writing a quick blog post and by adding the project to the Github readme. This should also help to get your app a bit more traffic. Let me know if you're interested.
