### ISSUE TITLE
ChatSDK.db().fetchUserWithEntityID regression

### ISSUE THREAD

**Issue by aymenhs** [chat-sdk/chat-sdk-android#613]
1. **Is the bug present in the demo Chat SDK project?** not sure
2. **What modifications have you made to the Chat SDK?** nothing
3. **Android Version**: 9

4. **Steps taken to reproduce the problem:**
USER 1 creates a private thread , USER 2 sent an interest to join the thread
from USER1's session (and phone) I wanted to retrieve USER2 by UID and add it to the private thread
just calling :
```
User user2= ChatSDK.db().fetchUserWithEntityID(UidFirebaseUSER2);
```
5. **Expected result:** USER2 object
6. **Actual result:**  object null
7. **Comments:** It worked fine in 4.8.5a4 and now in 4.8.12 it didn't return anything

**Comment by bensmiley** [comment]
That means that no user exists in your local database with that entity ID. You can use something like this:

```
    public User fetchUserWithEntityID(String entityID) {
        User user = ChatSDK.db().fetchOrCreateEntityWithEntityID(User.class, entityID);
        ChatSDK.core().userOn(user).subscribe();
        return user;
    }
```

**Comment by aymenhs** [comment]
good it works fine ! I tested 4.8.12 on three devices simultaneously chatting within a private room:
works fine and I receive push
by the way Ben the push script contains a small error:
https://github.com/chat-sdk/chat-sdk-android/issues/610
