### ISSUE TITLE
Get Specific User Data from Threads

### ISSUE THREAD

**Issue by MOhsain** [chat-sdk/chat-sdk-android#614]
How can we get specific user data from threads like key value pairs in ThreadMetaData?

**Comment by bensmiley** [comment]
@MOhsain can you provide me with a clearer idea of what you need. I don't really understand.

**Comment by MOhsain** [comment]
Basically i want to read these data from users in threads, like
ThreadMetaData class provides all keys and values against threads so i want
a specific user data from thread?
hope so this screenshot will help you.
[image: image.png]

>

**Comment by bensmiley** [comment]
@MOhsain The screenshot didn't upload. The thread meta-data can be accessed like this:

```
thread.metaMap()
```

There is not one meta map per user, just one for the thread. If you wanted to store user-specific data you would need to add keyed data to the meta map like:

```
thread.setMetaValue("[user-id]/key", "value");
```

**Comment by MOhsain** [comment]
Dear Chat-Sdk/Chat-Sdk-Android,  it sent from my side and showing in my
sent mails although i'm sending again.

thread.setMetaValue("[user-id]/key", "value"); this line of code add
data in Threads Meta Child, not in User child

i attached again screenshot please check

[image: image.png]

**Comment by bensmiley** [comment]
@MOhsain, 

You need to check the actual issue on Github: 

https://github.com/chat-sdk/chat-sdk-android/issues/614

The image doesn't work. There is no API to set metadata for the user-thread link. If you wanted to do that you would need to do it manually using the Firebase library. You can do it like this:

```
DatabaseReference threadUsersRef = FirebasePaths.threadUsersRef(thread.getEntityID()).child(user.getEntityID()).child(Keys.Status);

threadUsersRef.setValue(new HashMap<String, String>() {{
     put("key", "value");
}});

threadUsersRef.addValueEventListener(new RealtimeEventListener().onValue((snapshot, hasValue) -> {

}));
```

But you don't need to do that, you can add it to the standard thread meta data as I said previously. Then you can just access it like:

```
thread.metaMap().get("[user-id]/key")
```

**Comment by MOhsain** [comment]
Basically my scenarios is when i delete a user from one to one chat then it
added delete key against that user. And now i want to fetch all the users
who's child does not contain delete key.

**Comment by bensmiley** [comment]
You mean all the users from the whole database?

**Comment by MOhsain** [comment]
No against the single thread.

**Comment by MOhsain** [comment]
if screenshot will load from you side then hope so you will get my problem
:(

**Comment by MOhsain** [comment]
![image](https://user-images.githubusercontent.com/22424925/79228901-a0ad2380-7e7b-11ea-9bf1-1405501b2545.png)

**Comment by bensmiley** [comment]
You can just do it like this:

```
DatabaseReference threadUsersRef = FirebasePaths.threadUsersRef(thread.getEntityID());

threadUsersRef.addValueEventListener(new RealtimeEventListener().onValue((snapshot, hasValue) -> {
    // You will get a hashmap here and you can filter locally
}));
```

**Comment by MOhsain** [comment]
Please check this
![image](https://user-images.githubusercontent.com/22424925/79229115-f255ae00-7e7b-11ea-90a1-c6240fda2a4d.png)
