### ISSUE TITLE
Update SDK , Got Errors of Deprecation

### ISSUE THREAD

**Issue by MOhsain** [chat-sdk/chat-sdk-android#617]
Error --> 
1- [deprecation] ProgressDialog in android.app has been deprecated
2- [deprecation] FirebaseErrors in co.chatsdk.firebase has been deprecated
3- [deprecation] TaskDescription(String,Bitmap,int) in TaskDescription has been deprecated
4- error: cannot find symbol class ChatOptionType
5- [deprecation] startPublicThreadEditDetailsActivity(Context,String) in InterfaceAdapter has been deprecated
6- [deprecation] DialogUtils in co.chatsdk.ui.helpers has been deprecated
7- [deprecation] locale in Configuration has been deprecated
8- [deprecation] getSeconds() in Date has been deprecated
9- [deprecation] BitmapDrawable() in BitmapDrawable has been deprecated
10- [deprecation] ProgressDialog in android.app has been deprecated
and So on, please any one can tell me how to resolve these, because all these errors in "chat-sdk-ui" module.

**Comment by bensmiley** [comment]
Are these issues causing a crash or a build time error or are they just producing warnings?

**Comment by MOhsain** [comment]
These are  build time errors when i want to run the app then they are
visible on Log and Android Studio stuck on these error and can't move
forward.

**Comment by bensmiley** [comment]
Which version of android are you using? Usually, a deprecated method doesn't cause a build error. Can you post a screenshot?

**Comment by MOhsain** [comment]
Errors--->
![image](https://user-images.githubusercontent.com/22424925/79758265-a05acf80-8336-11ea-8220-b8be21b36246.png)

Android Studio Verison --> 
![image](https://user-images.githubusercontent.com/22424925/79758365-bff1f800-8336-11ea-871d-90f4e62b15d9.png)

**Comment by bensmiley** [comment]
From the message we can see that the actual problem is "Cannot find ChatOptionType". The deprecation messages are just warnings. Which version of the Chat SDK are you using?

**Comment by MOhsain** [comment]
Basically i just want to update my "chat-sdk-ui" and "chat-sdk-core"
modules.For this, I downloaded your Latest ChatSDK project from github, get
and import these  "chat-sdk-ui" ,"chat-sdk-core" modules in my current
project and then i'm getting these error messages.

**Comment by bensmiley** [comment]
Are you including the Chat SDK by importing the modules? You need to double-check that you have not got mismatched versions. The error I see is related to `ChatOptionType` variable which was removed some time ago. You need to make sure that all of the Chat SDK modules you're using are of the same version. Then delete the build folders, clean the project and in Android Studio do "File -> Invalidate cache and restart".

**Comment by MOhsain** [comment]
Thanks
