### ISSUE TITLE
How to send Reply of the message?

### ISSUE THREAD

**Issue by MOhsain** [chat-sdk/chat-sdk-android#618]
How can i send reply of message like in Whatsap?

**Comment by bensmiley** [comment]
Long press the message in Chat SDK v5 then click reply.

**Comment by MOhsain** [comment]
Can you send me link of  "Chat SDK v5"?

**Comment by bensmiley** [comment]
https://github.com/chat-sdk/chat-sdk-android

**Comment by MOhsain** [comment]
For saving data to the database, are you using Firebase or Firestore?
