### ISSUE TITLE
ChatSDK MainActivity doesn't exit

### ISSUE THREAD

**Issue by Zacle** [chat-sdk/chat-sdk-android#620]
1. **Is the bug present in the demo Chat SDK project?** Perhaps

2. **What modifications have you made to the Chat SDK?** None

3. **Android Version:** 8.1

4. **Steps taken to reproduce the problem:**

`      
       
         public boolean onOptionsItemSelected(@NonNull MenuItem item) {
             switch (item.getItemId()) {
                case R.id.chats:
                    Intent intent = new Intent(this, ChatSDK.ui().getMainActivity());
                    startActivity(intent);
                    return true;
               default:
                   return super.onOptionsItemSelected(item);
        }
    }

`

5. **Expected result:** Return back to the parent activity after pressing the back button

6. **Actual result:** Pressing the back button has no effect

7. **Comments:**
I'm trying to start the chat activity from my MainActivity. It start the chat activity but I cannot retun to my MainActivity if I press the back button. Any help??

**Comment by Zacle** [comment]
@bensmiley @thecmart  Please reply I need your help. Also how can I get the list of users belonging to a specific thread???

**Comment by bensmiley** [comment]
Can you show me your Chat SDK setup code?

**Comment by Zacle** [comment]
Here's my ChatSDK  setup code
`
@Override
    

        public void onCreate() {
        super.onCreate();

        Context context = getApplicationContext();

        try {
            // Create a new configuration
            Configuration.Builder builder = new Configuration.Builder();

            // Perform any other configuration steps (optional)
            builder.firebaseRootPath("prod");

            // Enable location messages
            builder.googleMaps(getString(R.string.google_maps_key));

            // Rooms creations
            builder.publicRoomCreationEnabled(true);

            // Initialize the Chat SDK
            ChatSDK.initialize(context, builder.build(), FirebaseNetworkAdapter.class, BaseInterfaceAdapter.class);

            // File storage is needed for profile image upload and image messages
            FirebaseFileStorageModule.activate();

            // Push notification module
            FirebasePushModule.activate();

            // Activate any other modules you need.
            // ...

        } catch (Exception e) {
            // Handle any exceptions
            e.printStackTrace();
        }

        // Uncomment this to enable Firebase UI
        FirebaseUIModule.activate(EmailAuthProvider.PROVIDER_ID, 
        PhoneAuthProvider.PROVIDER_ID);
    }

`

Please tell me also how can I get the list of users belonging to a specific thread???

**Comment by Zacle** [comment]
@bensmiley it's my final year project. Please could you tell me how can I get the list of users belonging to a specific thread???

**Comment by bensmiley** [comment]
Did you try `thread.getUsers()`
