### ISSUE TITLE
Notification is not getting triggred when Chat from two devices android  followed all the steps as given in doc

### ISSUE THREAD

**Issue by ketanspryox** [chat-sdk/chat-sdk-android#621]
1. **Is the bug present in the demo Chat SDK project?**
: not present in demo chat there it is working fine

2. **What modifications have you made to the Chat SDK?**
No modification  did as it is
3. **Android Version:**
android version 8 oreo and android Q

4. **Steps taken to reproduce the problem:** 
followed all the steps as doc

5. **Expected result:**
Should receive Notification on Background and foreground  as well
6. **Actual result:**
No notification for any of the chat message not for background and foreground as well

7. **Comments:**

I am Using gradle version  :4.8.12

can us please help in the issue its too urgent

**Comment by bensmiley** [comment]
You should make sure that you have installed the cloud script:

https://github.com/chat-sdk/chat-sdk-firebase#setup-firebase-cloud-functions

And followed any necessary steps to enable Firebase Cloud Messaging. 

https://firebase.google.com/docs/cloud-messaging/android/client

If you have done this, could you check the Firebase Console Functions tab and see if there are any errors?
