### ISSUE TITLE
Getting Circular dependency error

### ISSUE THREAD

**Issue by anarayn** [chat-sdk/chat-sdk-android#625]
1. **Is the bug present in the demo Chat SDK project?**
Yes
2. **What modifications have you made to the Chat SDK?**
I imported modules and try to compile. 
3. **Android Version:**
    Android 9
4. **Steps taken to reproduce the problem:**
Import below modules to the existing project
`':chat-sdk-firebase-adapter', ':chat-sdk-core', ':chat-sdk-ui', ':chat-sdk-firebase-push',':chat-sdk-firebase-file-storage' `

5. **Expected result:**
It should have been  compiled and chat should have worked
6. **Actual result:**

```
Circular dependency between the following tasks:
:chat-sdk-core:compileDebugAidl
+--- :chat-sdk-core:compileDebugAidl (*)
+--- :chat-sdk-firebase-adapter:compileDebugAidl
|    \--- :chat-sdk-core:compileDebugAidl (*)
+--- :chat-sdk-firebase-file-storage:compileDebugAidl
|    +--- :chat-sdk-core:compileDebugAidl (*)
|    \--- :chat-sdk-firebase-adapter:compileDebugAidl (*)
\--- :chat-sdk-firebase-push:compileDebugAidl
     +--- :chat-sdk-core:compileDebugAidl (*)
     \--- :chat-sdk-firebase-adapter:compileDebugAidl (*)
(*) - details omitted (listed previously)
```

7. **Comments:**
Thanks for help

**Comment by bensmiley** [comment]
Can you show me exactly what you have in your grade file to import the modules?
