### ISSUE TITLE
After I added the chatsdk modules its shows null object reference

### ISSUE THREAD

**Issue by RahatSaqib** [chat-sdk/chat-sdk-android#627]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

After I added the chatsdk modules its shows null object reference in all material elements like this error java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.button.MaterialButton.setVisibility(int)' on a null object reference

**Comment by bensmiley** [comment]
@RahatSaqib can you please update the issue template?

**Comment by RahatSaqib** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.project.ramfolinee/co.chatsdk.ui.login.LoginActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.button.MaterialButton.setVisibility(int)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.button.MaterialButton.setVisibility(int)' on a null object reference
        at co.chatsdk.ui.login.LoginActivity.initViews(LoginActivity.java:98)
        at co.chatsdk.ui.login.LoginActivity.onCreate(LoginActivity.java:74)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by RahatSaqib** [comment]
This error occured when the activity runs

**Comment by bensmiley** [comment]
Can you post your Chat SDK initialization code?

**Comment by RahatSaqib** [comment]
Context context = getApplicationContext();

        try {
            // Create a new configuration
            Configuration.Builder builder = new Configuration.Builder();

            // Perform any other configuration steps (optional)
            builder.firebaseRootPath("prod");

            // Initialize the Chat SDK
            ChatSDK.initialize(context, builder.build(), FirebaseNetworkAdapter.class, BaseInterfaceAdapter.class);

            // File storage is needed for profile image upload and image messages
            FirebaseFileStorageModule.activate();

            // Push notification module
            FirebasePushModule.activate();
            builder.publicRoomCreationEnabled(true);
            builder.pushNotificationSound("default");
            builder.pushNotificationsForPublicChatRoomsEnabled(false);
            ProfilePicturesModule.activate();

            // Activate any other modules you need.
            // ...

        } catch (Exception e) {
            // Handle any exceptions
            e.printStackTrace();
        }

**Comment by bensmiley** [comment]
Which class is this in?

**Comment by RahatSaqib** [comment]
AppObj class. which class i added on android menifest file with
android:name=".AppObj"

**Comment by bensmiley** [comment]
Do you get any exception during initialization?

**Comment by RahatSaqib** [comment]
No i didn't . I am trying to resolve this problem for 3 days. Upgrade all the dependency also. But the default chatsdk app is running well. But when I tried to do on my app. It is showing this error

**Comment by bensmiley** [comment]
Ok, so you've added it to your app. Did you make any other changes?

**Comment by bensmiley** [comment]
What do you have in your intent filter as the start activity for your app?

**Comment by RahatSaqib** [comment]
<activity android:name="co.chatsdk.ui.login.SplashScreenActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by RahatSaqib** [comment]
<activity android:name="co.chatsdk.ui.login.SplashScreenActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by RahatSaqib** [comment]
<activity android:name="co.chatsdk.ui.login.SplashScreenActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by RahatSaqib** [comment]
default splash screen activity

**Comment by RahatSaqib** [comment]
<activity android:name="co.chatsdk.ui.login.SplashScreenActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by RahatSaqib** [comment]
<activity android:name="co.chatsdk.ui.login.SplashScreenActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by RahatSaqib** [comment]
![sssss](https://user-images.githubusercontent.com/37343956/82826353-c4c64080-9ece-11ea-9b0a-fbd394ca6bba.PNG)

**Comment by RahatSaqib** [comment]
the splashscrren activity is running well and main activity,profile activity also running well.It shows error when i pressed logout button it shows this error. It shows all the com,google.android.material things as per my guessing

**Comment by RahatSaqib** [comment]
error is showing on loginactivy, chatactivity. when it tries to retrieve material button or material textinputview. It showing the null pointer exception

**Comment by bensmiley** [comment]
Is your project on Github? If you invite me I can see what the issue is. My username is ben_smiley.

**Comment by RahatSaqib** [comment]
Yes i Invited you . to my project. Please check it out brother

**Comment by RahatSaqib** [comment]
Recently i remembered. I have added api 'androidx.legacy:legacy-support-v4:1.0.0'  dependency inside chat-sdk-core's build script. Because there was showing a bunch of error .After following one stackoverflow answer. I added this & resolved my problem.is this a problem ?

**Comment by RahatSaqib** [comment]
hey . did you check my project?

**Comment by bensmiley** [comment]
@RahatSaqib I've looked at this and I'm afraid I have no idea what's going on. The splash screen activity loads up fine but the login activity doesn't. The xml layout is never expanded properly. I've not seen this kind of issue before and I doubt it's related to the Chat SDK. 

There has to be something that's wrong with your project but I'm afraid I can't go through the whole project myself to find out what it is. I would suggest that you re-checkout the Chat SDK and add your own files bit by bit and check each time to see if it breaks. Then you can narrow down what it is.

**Comment by bensmiley** [comment]
My guess would be that one of your Gradle dependencies has messed it up. You could remove some recent dependencies or go back to a previous commit and see if it works then.

**Comment by RahatSaqib** [comment]
if i commit to previous version it show error. cannot resolve
hasdefaultview provider factory something like that.. then i upgrade jst
life cycle extenstion version 2.1.0 to 2.2.0. the error have gone. and the
null error  occurs. what should i do.😐😑😑

**Comment by bensmiley** [comment]
@RahatSaqib there is probably a Gradle conflict. I would recommend that you roll back to the previous version that worked and then see which dependency is causing this issue.

**Comment by RahatSaqib** [comment]
I solved the login activity issue. Because my apptheme was at default . As i told that this issue is occuring for material components so i replace my app theme parent by Theme.MaterialComponents.Light.Bridge this theme. and it solved . But now this issue is showing on chatactivity like this void co.chatsdk.ui.chat.textinputview.setdelegate(co.chatsdk.ui.chat.textinputdelegate)' on a null object reference

**Comment by bensmiley** [comment]
@RahatSaqib I'm afraid I'm not really able to fix this kind of individual issue that is related specifically to your project. We have a lot of people using the library and every project is different, so it's not practical for me to address project-specific issues. If you would like me to look at it further, you would need to purchase some priority support time. As I recommended previously, I would recommend rolling back your changes until you find out which one is causing the trouble.

**Comment by RahatSaqib** [comment]
co.chatsdk.ui.chat.textinputview.setdelegate(co.chatsdk.ui.chat.textinputdelegate)' on a null object reference
This issue has been solved. I was using the same activity and xml file on my project before in main app module. When I delete those previous xml and activity my issue has been solved..
Thank you for your help. @bensmiley

**Comment by RahatSaqib** [comment]
Why did new chat history shows blank? any idea.? Because my firebase connected successfully and all user registers successfully. But new chat shows blank.
