### ISSUE TITLE
I want to fetch all the user who have registered .

### ISSUE THREAD

**Issue by RahatSaqib** [chat-sdk/chat-sdk-android#628]
I have a question that. Is there any method to show all the users who have been registered in this app?
I want to show those in contact fragment..If have, Can you please tell me?
Thank You.

**Comment by bensmiley** [comment]
@RahatSaqib You can do it with something like this:

```
public static Single<List<User>> getAllRegisteredUsers() {
        return Single.create(emitter -> {
            DatabaseReference ref = FirebasePaths.usersRef();
            ref.addListenerForSingleValueEvent(new ValueEventListener() {
                @Override
                public void onDataChange(@NonNull DataSnapshot dataSnapshot) {
                    List<User> users = new ArrayList<>();
                    if (dataSnapshot.exists()) {
                        for (DataSnapshot child : dataSnapshot.getChildren()) {
                            UserWrapper uw = new UserWrapper(child);
                            users.add(uw.getModel());
                        }
                    }
                    emitter.onSuccess(users);
                }

                @Override
                public void onCancelled(@NonNull DatabaseError databaseError) {
                    emitter.onError(databaseError.toException());
                }
            });
        });
    }
```

The reason we don't have an API for this is it's a really bad idea. Imagine you have 100k users and each time a device connects it is downloading 10mb of data. That is going to get very expensive very quickly.

**Comment by RahatSaqib** [comment]
Where do i add this code? How do i call the function getAllregisteredUsers?

**Comment by bensmiley** [comment]
Add this code anywhere, it's a static function. You can put it in any class. You would just call it:

```
getAllRegisteredUsers().subscribe((users, throwable) -> {
            
}); 
```
https://www.vogella.com/tutorials/RxJava/article.html

**Comment by RahatSaqib** [comment]
It is not working. showing blank screen

**Comment by bensmiley** [comment]
You will need to build your own screen to display the users. If you need me to develop the screen for you, I would be happy to provide a quote.

**Comment by RahatSaqib** [comment]
I call this method on SelectContactActivity  class. I think the userlistitem class is not using here

**Comment by RahatSaqib** [comment]
I am not able to build the screen because I am very much noob here. Btw thank you for your support. Stat blessed.

**Comment by bensmiley** [comment]
Ok, the problem is I don't have time to build the screen for you. I would need to charge for the time. The easiest thing you can do is this:

```
        ApiExamples.getAllRegisteredUsers().subscribe(users -> {
            for (User user: users) {
                ChatSDK.contact().addContactLocal(user, ConnectionType.Contact).subscribe();
            }
        });
```

Add this somewhere after the user has authenticated. It will add all the users to the current users contacts.
