### ISSUE TITLE
Upgrade SDk To 5.v

### ISSUE THREAD

**Issue by MOhsain** [chat-sdk/chat-sdk-android#631]
I have a project in which i import chat_sdk almost 4.6 version and i'm working on it  from last 1 year. So for your new updations, what would you prefer me  either i will make a new project, import all the chat_sdk modules and copy paste my all project classes in it or i will just update the modules in my current existing app and it could not alter my code?
Because you know better what things are discard from old version.
So please guide me.

**Comment by bensmiley** [comment]
@MOhsain I think either approach could work. I've made a document that contains a list of updates you will need to make. 

https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/SJLWjxdcL

If you have issues that are not covered in this document, you should join our Discord server;

https://discord.gg/abT5BM4

And I can give you direct advice.

**Comment by MOhsain** [comment]
I'm also using your paid modules like, Encryption, Last Screen and Contacts
Book. These modules could work with the old version or i will need to
update all these with 5.v?

**Comment by bensmiley** [comment]
@MOhsain Can you send me an email with your license details? to team@sdk.chat and I'll check into the details.

**Comment by MOhsain** [comment]
Where can I get this  license  details?

**Comment by bensmiley** [comment]
You would have received an email when you purchased the license. Either forward that email to me or tell me the email you used to make the purchase.
