### ISSUE TITLE
SDK update issue at Android Studio 1.0

### ISSUE THREAD

**Issue by MOhsain** [chat-sdk/chat-sdk-android#632]
I'm facing an issue while update Chat_SDk 4.+ to new Version 5.v.
My Android Studio is Latest 4.0.
Please check screenshot
![image](https://user-images.githubusercontent.com/22424925/84904357-ab2ca900-b0c8-11ea-95ef-9e75871eae3c.png)

**Comment by bensmiley** [comment]
@MOhsain can you show me what you added to your grade file?

**Comment by MOhsain** [comment]
i added these lines in project level build.gradle file ->

classpath "com.android.tools.build:gradle:4.0.0"
classpath "com.google.gms:google-services:4.3.3"
classpath 'com.novoda:bintray-release:0.9.2'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.71"
classpath 'com.jakewharton:butterknife-gradle-plugin:10.2.1'
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.1.1'
classpath 'com.google.firebase:perf-plugin:1.3.1'

**Comment by bensmiley** [comment]
@MOhsain could you plase show me both your project and app level build.gradle files?

**Comment by MOhsain** [comment]
How can I show all my projects to you?

**Comment by bensmiley** [comment]
You need to clean the project (delete the Build directories) and then zip it and email it to me team@sdk.chat. Or invite me to your Git repo if you're using one. My username is ben_smiley.

**Comment by MOhsain** [comment]
Why are you closing this?

**Comment by bensmiley** [comment]
Because I posted a reply a week ago and got no reply. We need to solve it or close the issue.

**Comment by bensmiley** [comment]
I would also recommend looking at this video:

https://www.youtube.com/watch?v=ZzfSd3hc3xw

I started with a clean Android Studio project and setup the Chat SDK.

**Comment by MOhsain** [comment]
But you are using Android Studio Version 3.6 and my Version is 4.0. I also
sent my code base to your given email address. Please check that

**Comment by MOhsain** [comment]
Please reply to me?

**Comment by bensmiley** [comment]
Hi @MOhsain this is an issue directly related to using Android Studio 4.0. It's related to [this](https://github.com/novoda/bintray-release/issues/318). I will update the project as soon as AS 4.0 comes out of beta. In the meantime, I would recommend that you use: AS 3.x, add the Chat SDK using Gradle and remove the bintray release dependency or follow the steps in the issue I posted.
