### ISSUE TITLE
XMPP vs. Firebase

### ISSUE THREAD

**Issue by YimingLi-1996** [chat-sdk/chat-sdk-android#634]
I am a little confused by the pricing. Why is the Firebase Chat SDK free to use while the XMPP requires a license? What are the differences between them? Which one should I choose? Thank you!

**Comment by bensmiley** [comment]
Hi @YimingLi-1996 I've made a tutorial that explains the differences. You can see it [here](https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/Sk8-jryC8). The reason we charge for XMPP is that the library took a massive amount of time to write and is usually used more for large scale commercial projects. If you have further questions let me know and I'd be happy to answer them.

**Comment by YimingLi-1996** [comment]
Hi Ben! Thanks for answering! Just want to double check two things: if I need to run my chat app without any Google services, I have to choose XMPP out of the three options, right? Also, for the XMPP version, the source code will only be available after I purchase the license, right?

**Comment by bensmiley** [comment]
Hi @YimingLi-1996 if you need to run the app without Google Services then you will have to use the XMPP adapter. There are three options in terms of the module. You can sponsor the project in which case you get access to the compiled XMPP module (not source). You could buy the module as a one-off - [details here](https://chatsdk.co/xmpp/). Or if you want to get the source on a pay-monthly option you can let me know and I'll give you further details.
