### ISSUE TITLE
Back press not working on main activity. 

### ISSUE THREAD

**Issue by RahatSaqib** [chat-sdk/chat-sdk-android#635]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**
I implement you code to my project.
3. **Android Version:**
8
4. **Steps taken to reproduce the problem:**
@Override
public void onBackPressed(){
Intent intent =new Intent ( MainActivity.this,HomeActivity.class);
startActivity(intent);
finish();
}
5. **Expected result:**
It will go to my appz homeactivity. 
6. **Actual result:**
But it is not either showing an error or go to activity.It stay where it was.I was doing the same on your previous versiln 4. It was working. But now its an issue. 
Thank you. 
7. **Comments:**
@bensmiley I think you can help me. As you did before

**Comment by bensmiley** [comment]
Hi @RahatSaqib could you provide some more context. Are you subclassing the `MainActivity`? If so, have you tried adding a breakpoint on this line to see if it's actually hitting it?

**Comment by RahatSaqib** [comment]
I implement this code on MainActivity.becauseafter the splashscreenaxtivity the app redirect to mainactivity.  Thats why i add those.  As per my opinion it is not hitting the mainActivity.

**Comment by bensmiley** [comment]
Hi @RahatSaqib if you want the app to redirect to your main activity you can use:

```
ChatSDK.ui().setMainActivity(YourMainActivity.class);
```

Other than that, you would need to add a breakpoint to the main activity `onCreate` method and `onBackButtonPressed`. You are saying that the activity is not launched, but first, you need to confirm that your code is actually executed.

**Comment by RahatSaqib** [comment]
Actually ben I am not tryting to make any difference to your app. I am just trying when I click on a button it will go to your app from mine. and when I back press from your app it will back to my app.thats it.. if you can tell me where should I use onBackPressed method on your app.

**Comment by bensmiley** [comment]
@RahatSaqib you need to override the `MainActivity` and then override the `onBackButtonPressed` method. it is disabled by default. See here:

https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/ByL0mWG0L

**Comment by bensmiley** [comment]
This is the code in the `MainActivity` that disables the back pressed. 
```
    @Override
    public void onBackPressed() {
        // Fixes an issue where if we press back the whole app goes blank
        if (UIModule.config().allowBackPressFromMainActivity) {
            super.onBackPressed();
        }
    }
```
You can also set the setting:

```
UIModule.config().setAllowBackPressFromMainActivity(true);
```

**Comment by RahatSaqib** [comment]
I also tried this method also.. but it is not WORKING.But in the case of chat activity  I use ChatSdk.ui().setMainActivity to my homeaktivity which is working when backpressed it comes to my app activity.. But inside Main Activity of your app it is not working the backkpressed method.

**Comment by RahatSaqib** [comment]
But I want to say that is. When ever I tried to change any of this activity it changes but it is not taking effect on your app. After that I saw that in C:\Users\user\.gradle\caches\modules-2\files-2.1\sdk.chat this directory all of you app's activity,fragments, stored here. That is only read only. It is not changing when i change it shows read only. It stays what you implement. I think my project call this files when runny not the imported module files. As I am thinking. I am not sure. You are professional you can ensure me If i am worong or write . @bensmiley

**Comment by bensmiley** [comment]
@RahatSaqib you shouldn't try to modify the files. Subclass and override them like this:

https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/ByL0mWG0L

I also tested and `onBackPressed` is called. 

![Screenshot 2020-07-05 at 13 01 38](https://user-images.githubusercontent.com/5514010/86531230-c1f03f80-bebf-11ea-998e-f7ef779b131a.png)

If you could give me a clearer idea of what you're trying to do, I can try to advise further.

**Comment by bensmiley** [comment]
You say you've already overridden the main activity. So where do you exactly want to go back to when back is pressed? This isn't really anything to do with Chat SDK, it's a standard Android issue. You can just launch the activity like this:

```
Intent intent = new Intent(this, MainActivity.class);
startActivity(intent);
```

**Comment by RahatSaqib** [comment]
I already did all of the thing you tell.. But it didn't happening in my case. I used Intent also.. But do not happening. As per my guess it should be done with this.

**Comment by bensmiley** [comment]
@RahatSaqib can you please describe your setup in more detail. Tell me how you are integrating Chat SDK. Where are you trying to click back from, where do you want it to go? Did you add a breakpoint? etc...

**Comment by RahatSaqib** [comment]
actually I told you before about it. I just want to launch your app by this button click
![splas](https://user-images.githubusercontent.com/37343956/86531517-cfb7bc00-bee3-11ea-8ff3-a5a40a2987eb.PNG)
when i press the button it goes to your app mainActivity
![Screenshot_2020-07-05-17-17-09-765_com project ramfolinee](https://user-images.githubusercontent.com/37343956/86531529-e827d680-bee3-11ea-9d30-82d709bdc3eb.png)

this activity comes. and I want to back press from this interface. when i back press from this UI. i will back to my app. That's it

**Comment by bensmiley** [comment]
@RahatSaqib I think the problem is that you're launching the splash screen activity. Try launching the main activity instead:
```
        ChatSDK.ui().startMainActivity(this);
```
You will have to make sure that the user is already authenticated with Firebase

**Comment by RahatSaqib** [comment]
No brother. Its not working also

**Comment by RahatSaqib** [comment]
I already authanticated users in my homeactivity

**Comment by bensmiley** [comment]
@RahatSaqib yes, if you just launch the main activity it won't work, because the back button is disabled. You would need to override the main activity and enable the back button and then launch that.

**Comment by RahatSaqib** [comment]
Can you tell me how to override the main activity. I already eneable allowbackpressed variable to true. but how to override this. can you suggest me?

**Comment by bensmiley** [comment]
@RahatSaqib here is the link to the guide on how to override activities: https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/ByL0mWG0L

**Comment by bensmiley** [comment]
1. Subclass the `MainActivity`
2. override the `onBackPressed` method
3. In `onBackPressed` launch your main app activity
4. Register your subclass with Chat SDK framework `ChatSDK.ui().setMainActivity(MainActivitySubclass.class);`

**Comment by RahatSaqib** [comment]
ChatSDKUI.setPostRegistrationActivity(HomeActivity.class);

should i use  this method?

**Comment by RahatSaqib** [comment]
Finally It works with your suggestion. But why this was not working on Mainappbar activity?

**Comment by bensmiley** [comment]
I don't know why it wasn't working, I expect because you were launching the splash screen activity which itself launches the main app bar activity. Even when you enabled back, it would just jump back to the splash screen and immediately back to the main activity. You can subclass `MainAppBarAcrtivity` too, I think that should also work.

**Comment by RahatSaqib** [comment]
I have a question to you. When I recieve msg from others it will give default notification ringtone..But in your app it only receive notification and vibrate no ringtone.I added these lines on NotificationDisplayHandler.java file. but it si not working. can you suggest me something?
![notify](https://user-images.githubusercontent.com/37343956/86883907-9ade7b80-c114-11ea-89c1-f0b2f6e89385.PNG)
