### ISSUE TITLE
Firebase rules file not available

### ISSUE THREAD

**Issue by john-lq** [chat-sdk/chat-sdk-android#638]
Hello Team,
 I have a look on the three-issue. But there is not a link to be available for me to download the Firebase Rule:
https://github.com/chat-sdk/chat-sdk-android/issues/609
https://github.com/chat-sdk/chat-sdk-android/issues/568
https://github.com/chat-sdk/chat-sdk-android/issues/180

Can you help me?
Thanks

**Comment by bensmiley** [comment]
The link is available in the setup instructions [here](https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/BkvpPKFqI)
