### ISSUE TITLE
cannot share full image in chat-window.

### ISSUE THREAD

**Issue by goldiaxy** [chat-sdk/chat-sdk-android#64]
I tried to upload an image. Instead of uploading entire image, it ask for selecting a square region of image. Why full image cannot be uploaded? 
But when I tried to taking picture (instead of uploading image), I can share full image captured by camera (any size).
Is there a option to allow full image size instead of partial image?

**Comment by kykrueger** [comment]
Hi @goldiaxy ,

I believe cropping should only be enabled for profile pictures. This may indeed be a bug. @bensmiley are you cropping all images in the iOS version of the chat SDK?

**Comment by goldiaxy** [comment]
Hi @kykrueger 
This issue is observed in Android version of the chat SDK. I tried HEAD branch.

**Comment by simonsmiley64** [comment]
@kykrueger,

Currently in the latest iOS version we deal with images and profile images slightly differently. Both can be cropped and use the [TOCropViewController](https://github.com/TimOliver/TOCropViewController) for this functionality.

**Profile images:** This image is cropped into a circle to show the user what their image will look like. This then crops the image to the square size which fits into the shown circle.

<img width="187" alt="screen shot 2017-04-03 at 10 17 10" src="https://cloud.githubusercontent.com/assets/8721425/24592274/ff251ba4-1856-11e7-8c34-d1b4ea94a7cb.png">

**Images:** These have a crop functionality enabled on them so the users can make the images specific to the exact part of the image they want. 

I don't know if Android has any similar libraries like this but you can use this as a guide for how the functionality would like to be. 

In the scenario mentioned above the user should be able to use the entire image as well as crop the image to be smaller if they wish.

Simon

**Comment by goldiaxy** [comment]
Hey @simonsmiley64 . 
Issue is not with cropping. My point is that why cropping is needed when user sharing pictures in chat window. 
chat-Widnow --> Choose Picture --> Browse the Picture and select one.
Here you will see it will ask for Cropping ( a square size cropping).

IMO, cropping is not needed here. It should share entire pictures in chat. No cropping is needed. 

This issue I observed in Android  device.

Whereas if I select "Take Picture" and take picture using camera. It does not do cropping. It just share entire picutures.
