### ISSUE TITLE
The app crashes in release mode

### ISSUE THREAD

**Issue by john-lq** [chat-sdk/chat-sdk-android#640]
Hello Team,

The app work well in debug mode. But I have tried to build the app in release mode. The app crashes when updating the user.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.greenrobot.greendao.AbstractDao org.greenrobot.greendao.AbstractDaoSession.getDao(java.lang.Class)' on a null object reference
        at sdk.chat.core.dao.DaoCore.fetchEntityWithEntityID(Unknown Source:2)
        at sdk.chat.core.base.AbstractCoreHandler.currentUser(Unknown Source:28)
        at sdk.chat.core.session.ChatSDK.currentUser(Unknown Source:4)
```
**proguard-rules.pro**
```
-keep class sdk.chat.core.** { *; }
-keep class org.greenrobot.** { *; }

-keepclassmembers class * extends org.greenrobot.greendao.AbstractDao {
    public static java.lang.String TABLENAME;
}
-keep class **$Properties { *; }

-keepclassmembers class * extends org.greenrobot.greendao.AbstractDaoSession { *; }
```

```
classpath 'com.android.tools.build:gradle:4.0.0'
classpath 'com.google.gms:google-services:4.3.3'
```
**Android Studio 4.0**

Pls help me to fix it!

Thanks,
John

**Comment by bensmiley** [comment]
Hi @john-lq I'm currently working on the ProGuard rules. I will be releasing them next week. But until that's finished, the library won't support minification.

**Comment by john-lq** [comment]
Hello @bensmiley,

Thanks for quick reply. 
Setting the `minifyEnabled false` can solve the problem?

Thanks,
John

**Comment by bensmiley** [comment]
Yes, it will.

**Comment by john-lq** [comment]
Yes, It work well. But the app size is increased :(
Pls let me know when the library supports minification.

**Comment by bensmiley** [comment]
@john-lq yes, it would increase the size. The new version will be ready next week.

**Comment by vpulpatil** [comment]
Any update on this @bensmiley ?

**Comment by bensmiley** [comment]
This is fixed in the latest version. You can also add the Proguard rules to your app's proguard file:

```
# ChatSDK
-keep public class sdk.chat.**, sdk.guru.**, firestream.chat.**, app.xmpp.**, co.chatsdk.** {
    public protected *;
}

-keep class org.ocpsoft.prettytime.i18n.**

-keep class .R
-keep class **.R$* {
    <fields>;
}
# End
```
