### ISSUE TITLE
Date detector in chat 

### ISSUE THREAD

**Issue by cristo1985** [chat-sdk/chat-sdk-android#644]
Hello, we saw your SDK to integrate chat into an Android / ios application. Very interesting. What we would like to know is this: there is the possibility of recognizing if a user enters a date for example 24/07/2020 in the chat is converted into something clickable and which allows you to add an event in the Android calendar / iOs. Does this feature already exist?
Thank you
Regards
Cristian Capannini

**Comment by bensmiley** [comment]
@chat-sdk/contributors this would be possible. You would need to create a custom message cell. Here are instructions:

https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/ryxEXfA08
