### ISSUE TITLE
How to delete groups?

### ISSUE THREAD

**Issue by brittle123** [chat-sdk/chat-sdk-android#655]
Helo Sir ,... i just wanna know that how to delete groups ?please reply me ASAP!
Regard & Thanks.

**Comment by nicorevo** [comment]
hi, any news on it ?
br
nico

**Comment by bensmiley** [comment]
@nicorevo group deletion is currently not supported for the Firebase version. I will change this to a feature request. This can be expedited if it can be sponsored.
