### ISSUE TITLE
Is it possible to use fragments of chats without activities?

### ISSUE THREAD

**Issue by anonym24** [chat-sdk/chat-sdk-android#656]
I have activity with bottom toolbar and I want to show chat thread in one of the tabs (a separate fragment), there is `PrivateThreadsFragment` but it seems I can't just do `class ChatThreadsFragment : PrivateThreadsFragment()` and add it to empty activity

So the only method is to subclass activity and then set which custom fragments will be used in that activity? based on https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/ByL0mWG0L

**Comment by anonym24** [comment]
There is https://hackmd.io/@dyR2Vn0UTFaO8tZjyiJyHw/ByL0mWG0L#Using-the-Fragments-in-your-app

so I create my Activity and I don't extend MainActivity of ChatSDK but I have to call some `loadData()` method, what is that and where to find it?

**Comment by anonym24** [comment]
actually it works I've extended `PrivateThreadsFragment` and use it with my own activity which just extend AppCompatActivity and I can conversations, so there is no need for `MainActivity` of ChatSDK

**Comment by marwen-dhahri** [comment]
i have the same issue how did you initialize the chat sdk in your fragment
