### ISSUE TITLE
Visual enhancements to message view

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#66]
We have made a number of improvements to the message view in iOS which could be ported to Android. 

1. Add section headers which have the message date
2. Add the user name below the avatar for group / public chats
3. Have different types of chat bubbles - i.e. one with three corners rounded, one with two corners rounded and one with one corner rounded and the speech bubble tail. So if a user sends multiple consecutive messages it looks better
4. If the user sends multiple consecutive messages, only show the user profile image once at the bottom bubble. Also, only show the time if the time has changed since the last message. 
5. Make the profile image icon smaller and make the message bubbles closer together
6. Change the shade of blue for messages. Sent messages should be light blue (#abcff4) and received messages light gray (#d7d4d3). 

![image1](https://cloud.githubusercontent.com/assets/5514010/24642743/1fa4d668-193c-11e7-8011-9c7a4776f589.PNG)

**Comment by hristoyordanov** [comment]
Hi all, 
"We have made a number of improvements to the message view in iOS which could be ported to Android.

1. Add section headers which have the message date
2. **Add the user name below the avatar for group / public chats**"

From what I can see 2 has not been implemented for Android yet - anyone can advise how I can do that - which is the file at least? - TextMessageViewHolder.java or?

**Comment by hristoyordanov** [comment]
Can someone apply this change in the next version for Android, please?
- **Add the user name of the sender below the avatar in the message for group / public chats**
