### ISSUE TITLE
Empty push notification for image messages

### ISSUE THREAD

**Issue by adkaushik** [chat-sdk/chat-sdk-android#665]
1. **Is the bug present in the demo Chat SDK project?: Yes**

2. **What modifications have you made to the Chat SDK? None**

3. **Android Version: tested in versions 9 and 10**

4. **Steps taken to reproduce the problem: Install the demo app. Add a user to contact and send an image message, The push notification received will be empty**

5. **Expected result:: Show the sent image in the notification or some text like (sent an image)**

6. **Actual result:Blank push notification body **

7. **Comments:**

**Comment by Devishkar** [comment]
Can you assign this issue to me?
