### ISSUE TITLE
How can I implement/Use Facebook, Twitter and Gmail login?

### ISSUE THREAD

**Issue by FidaMOhsin** [chat-sdk/chat-sdk-android#667]
Can you tell me please, how can I implement/Use Facebook, Twitter and Gmail login?

**Comment by bensmiley** [comment]
This is supported by the Firebase UI module. Use something like:

```
FirebaseUIModule.builder()
        .setProviders(EmailAuthProvider.PROVIDER_ID, PhoneAuthProvider.PROVIDER_ID)
        .build()
```
Then follow Firebase docs for setup and configuration.
