### ISSUE TITLE
"online: true" field isn't removed from database when app minimizes 

### ISSUE THREAD

**Issue by anonym24** [chat-sdk/chat-sdk-android#668]
1. **Is the bug present in the demo Chat SDK project?** yes, v5.0.16

2. **What modifications have you made to the Chat SDK?** none

3. **Android Version:** 21-30

4. **Steps taken to reproduce the problem:** open chat demo app, login, minimize (don't remove from history), check firebase, online status is shown for that user, it's only being deleted when app is removed from history

5. **Expected result:**
"online: true" should have removed, or set to false

6. **Actual result:**
"online: true" even after app was minimized

**Comment by anonym24** [comment]
it works on old `5.0.0rc25` when app minimized

but on 5.0.1-5.0.16 online status is removed only when app is removed from history

**Comment by bensmiley** [comment]
Fixed in 5.1.2
