### ISSUE TITLE
Make the + and options button in the chat view white not black

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-android#67]
![chat-sdk-android_1](https://cloud.githubusercontent.com/assets/5514010/24642764/4c6ad396-193c-11e7-9606-8f95bcb54749.png)

**Comment by RyanElliott94** [comment]
Hello, not sure if you were still looking to do this but I've recently done this my app! So try this code:

        Drawable iconDrawable = ContextCompat.getDrawable(getActivity(), R.drawable.your_drawable);

        iconDrawable = DrawableCompat.wrap(iconDrawable);
        DrawableCompat.setTint(iconDrawable, ContextCompat.getColor(getActivity(), android.R.color.white));

Then set the icon:  
     
         item.setIcon(iconDrawable);
