### ISSUE TITLE
Getting old notification of read messages everytime after logged in

### ISSUE THREAD

**Issue by ZaroonRashid** [chat-sdk/chat-sdk-android#674]
I have integrated chatsdk in my application and enabled push notifications with firebase. Whenever I logged in after clearing my cache, I got all the notifications of old messages which I have read previously. I have recheck all integration but didn't find any mistake.

**Comment by bensmiley** [comment]
If you delete the app you would need to install the read receipts module to avoid this. Otherwise, you would need to implement your own method of tracking when the message is read.
