### ISSUE TITLE
Is there any method to find out number of all unread messages?

### ISSUE THREAD

**Issue by anonym24** [chat-sdk/chat-sdk-android#677]
Demo has counter of unread messages on each thread item view on threads list screen.

But I need to get the number of all unread messages - one number - one `int` variable. Is it possible? 

Would be good if this value would be updated automatically - rx observer - firebase realtime datebase value event listener 

I need to show it like this for example (whole number - all unread messages count):

![image](https://user-images.githubusercontent.com/8851301/99673389-61802a00-2a7d-11eb-8995-21f122d6ac19.png)

**Comment by bensmiley** [comment]
You would need to loop over the threads for the current user:

```
int count = 0;
for (Thread t :  ChatSDK.thread().getThreads(ThreadType.Private1to1)) {
    count += t.getUnreadMessagesCount();
}
```

**Comment by slpatidar** [comment]
There is no syncing with the firebase realtime database for "read" status mark in free SDK, this is just maintaining the read unread mark in the local database so when we uninstall the app database will be cleared and then install the app all thread messages becomes show as a new unread message.

**Comment by slpatidar** [comment]
So the read unread status feature is paid service or it's free? please make me clear.
