### ISSUE TITLE
Help regarding overriding of MainActivity

### ISSUE THREAD

**Issue by BismeetSingh** [chat-sdk/chat-sdk-android#678]
I want to make a request to the firebase database when the main activity loads. So, I created a custommainactivity and passed it to the setMainActivity. But the issue is MainActivity is an abstract class and so I also need to implement the functions / make my custom main activity abstract which I cant otherwise it cant be instantiated.

**Comment by bensmiley** [comment]
@BismeetSingh you can either extend the `MainAppBarActivity` which isn't abstract or you will have to implement the abstract methods.

**Comment by BismeetSingh** [comment]
Caused by: java.lang.IllegalStateException: Required view 'toolbar' with ID 2131362506 for field 'toolbar' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
This is what I get on extending MainAppBarActivity.

**Comment by bensmiley** [comment]
It probably means that your layout xml file doesn't match - i.e. you don't have an element with the ID toolbar. 

```
        <include layout="@layout/app_bar_default" />
```

This line
