### ISSUE TITLE
 Unable to click on links in chat window. Missing onclick call.

### ISSUE THREAD

**Issue by DaracBack** [chat-sdk/chat-sdk-android#683]
1. **Is the bug present in the demo Chat SDK project?** yes

2. **What modifications have you made to the Chat SDK?** small ones

3. **Android Version:** all versions have same problem

4. **Steps taken to reproduce the problem:**  send www.example.com to other user

5. **Expected result:** links be auto transfrom in clickable hyperlinks open in browser

6. **Actual result:** just text

7. **Comments:**

**Comment by bensmiley** [comment]
Fixed in 5.1.2.
