### ISSUE TITLE
Chat is laggy on initial loading of the app after signing in

### ISSUE THREAD

**Issue by mwaqassatti** [chat-sdk/chat-sdk-android#689]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**

4. **Steps taken to reproduce the problem:** Install new app which have lots of conversation and sign in

5. **Expected result:** It should be smooth

6. **Actual result:** App freezes for some 20-30 secs

7. **Comments:** Currently we are using version 4.8.9. (e.g. app is uninstalled, you install the app and you log into an existing account with a lot of conversations), the app gets kind of laggy for like 20-30 seconds while the app is loading after sign in.

**Comment by bensmiley** [comment]
@mwaqassatti can you see if this happens in 5.x? We are not developing 4.x any further so even if there are bugs, they will not be fixed.
