### ISSUE TITLE
Contact book integration bug

### ISSUE THREAD

**Issue by DaracBack** [chat-sdk/chat-sdk-android#690]
1. **Is the bug present in the demo Chat SDK project?** Yes

2. **What modifications have you made to the Chat SDK?** None

3. **Android Version:** all

4. **Steps taken to reproduce the problem:** Try invite someone via Contact book. 

5. **Expected result:** invite peope and share app via SMS or similar services.

6. **Actual result:** Opening SMS aplication for invite but typing box is empty.

7. **Comments:**

**Comment by bensmiley** [comment]
You can set the subject and body like this:

```
ContactBookModule.builder().contactBook("Email Subject", "Email body", "SMS body").build()
```
