### ISSUE TITLE
GreenDao & Proguard Issue

### ISSUE THREAD

**Issue by ChatWave** [chat-sdk/chat-sdk-android#692]
1. **Is the bug present in the demo Chat SDK project?** I'm assuming yes

2. **What modifications have you made to the Chat SDK?** A lot

3. **Android Version:** 7.1.1

4. **Steps taken to reproduce the problem:** Turn on minify

5. **Expected result:** It's supposed to launch

6. **Actual result:** Says there's no TABLENAME

7. **Comments:**

Has chatsdk successfully used minify with greendao?
I'm using a pretty old source code, but I noticed the new one doesn't even have the minify on or the release config.
I noticed the proguard rules are all there to fix this issue, but they don't work. Have you actually got it to work? Maybe it's device specific.

**Comment by ChatWave** [comment]
actually nevermind it does use minify
let me see if it launches

**Comment by bensmiley** [comment]
Yes the new version works with minify. You can check the Proguard rules.
