### ISSUE TITLE
Clearing chat history from Firebase

### ISSUE THREAD

**Issue by basims** [chat-sdk/chat-sdk-android#693]
I know chat SDK works because we are saving the messages in Firebase. But, due to some privacy issues, I shouldn't keep user's chat data in Firebase forever. Is there any way I can implement this using chat SDK? Can I do something like deleting the message from Firebase right after the message is delivered? Or does it support any kind of encryption so that even Firebase admin cant see the messages?

**Comment by bensmiley** [comment]
Hi @basims to do this you would need to remove the messages using the Firebase REST API or a Firebase Functions script. It is not supported by the Chat SDK.
