### ISSUE TITLE
Getting all messages from a user

### ISSUE THREAD

**Issue by basimsherif** [chat-sdk/chat-sdk-android#695]
Currently, I am using thread().getMessages() to get all messages from a thread. But due to some issues, I am getting duplicate threads for the same user. Is there any way I can get a merged list of all messages, sent and received from a user? So basically, I need to merge all the messages from all threads from the same user.

**Comment by bensmiley** [comment]
@basimsherif can you give me some more context. I need to know which code you're using to try to get the threads for the user.

**Comment by basimsherif** [comment]
Below is the method I use to get the thread while sending a message to user,
thread().createThread(Collections.singletonList(user))
            .subscribe { thread1: Thread? ->

            }
And I use the below code to list all the threads for all users, where I am getting duplicates
thread().getThreads(ThreadType.Private1to1)

**Comment by bensmiley** [comment]
When you say they are duplicates, can you explain what you mean?

**Comment by basimsherif** [comment]
I am getting two threads from the same user, when I use the below method,
thread().getThreads(ThreadType.Private1to1)
Please see the screenshot below,

![Screenshot_20210305-190234](https://user-images.githubusercontent.com/4938087/110122375-8d81aa00-7de5-11eb-8355-d5380b8a5584.jpg)
