### ISSUE TITLE
Plugin For Flutter

### ISSUE THREAD

**Issue by Arjunraj-k** [chat-sdk/chat-sdk-android#697]
Can you guys release a plugin for Flutter, as your SDK seems to work on all other platforms, it will be easy for flutter devs to integrate this features to our apps.

**Comment by bensmiley** [comment]
I'm afraid it's very unlikely we will be able to make a plugin for Flutter unless we get sponsorship or support from a developer from the community. Currently, we only have the resources to support the iOS and Android clients.
