### ISSUE TITLE
not getting getting last seen for a user i'm using ChatSDK.lastOnline().getLastOnline(thread.otherUser()) getting null

### ISSUE THREAD

**Issue by rajatkhanna506** [chat-sdk/chat-sdk-android#703]
unable to get last seen of user using ChatSDK.lastOnline().getLastOnline(thread.otherUser()) this method to get last seen but null is getting from the method 

@bensmiley

**Comment by bensmiley** [comment]
You would need the last online module for this. https://www.patreon.com/chatsdk/
