### ISSUE TITLE
New repository (instead of JCenter) fails to provide all libraries for ChatSDK

### ISSUE THREAD

**Issue by anonym24** [chat-sdk/chat-sdk-android#704]
ChatSDK Version `5.2.10`

So I use new a repo:

`maven { url "https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android" }`

But still I can't compile my project:

![image](https://user-images.githubusercontent.com/8851301/119971871-2fb2c780-bfba-11eb-83b6-bae139d8f8ce.png)

   > Could not find sdk.chat:chat-kit:0.3.3b14.
     Required by:
         project :component_network > sdk.chat:ui:5.2.10
   > Could not find com.mikepenz:materialdrawer-iconics:8.0.0-a07.
     Required by:
         project :component_network > sdk.chat:mod-ui-extras:5.2.10
   > Could not find com.miguelcatalan:materialsearchview:1.4.0.
     Required by:
         project :component_network > sdk.chat:mod-ui-extras:5.2.10

**Comment by anonym24** [comment]
Also in documentation you till have jcenter (it may worked for you because have cache on your local PC):

![image](https://user-images.githubusercontent.com/8851301/119972318-bc5d8580-bfba-11eb-95e5-9af03f9109ef.png)

But you should remove and do a clean build

**Comment by bensmiley** [comment]
JCenter is still available. It's just read-only. 

>JFrog, the company that maintains the JCenter artifact repository used by many Android projects, made JCenter a read-only repository on March 31st, 2021. According to the announcement, JCenter will allow downloads of existing artifacts indefinitely.

**Comment by anonym24** [comment]
@bensmiley 

from this your comment and email I solved it with:

```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url "https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android" }
        maven { url "https://chatsdk.jfrog.io/artifactory/release/chatkit" }
        maven { url "https://chatsdk.jfrog.io/artifactory/release/matisse" }
    }
}
```

Thanks!

**Comment by rubensfelipe** [comment]
tks, for me was missing the jcenter(), though he will be depricated in the future
