### ISSUE TITLE
Gradle sync error while setting up ChatSDK in my project

### ISSUE THREAD

**Issue by aparajita-sinha** [chat-sdk/chat-sdk-android#705]
As per documentation I have added it to the project. When I checkout the project in another fresh system, this is the error.
Could not GET 'http://dl.bintray.com/chat-sdk/chat-sdk-android/co/chatsdk/chatsdk/chat-sdk-core/4.8.18/chat-sdk-core-4.8.18.pom'. Received status code 403 from server: Forbidden

**Comment by bensmiley** [comment]
@aparajita-sinha Bintray shut down which means that all the builds were removed. Since that's version 4, you would need to host the code on your own maven repository. The closest version is 4.8.16. Available her: 

https://github.com/chat-sdk/chat-sdk-android/releases/tag/4.8.16
