### ISSUE TITLE
[android-sdk]  skipping authentication UI

### ISSUE THREAD

**Issue by Mohadese267** [chat-sdk/chat-sdk-android#711]
I have an app using ChatSDK , it has login process using google sign-in , so it has its own authentication process , I just need to apply this info  in chat sdk , I wonder if there is anyway to skip the login/registration process used it ChatSDK?

**Comment by bensmiley** [comment]
Yes, as soon as you authenticate with Firebase, the Chat SDK will attach the necessary listeners and set itself up. If you want to skip login, just don't load your own activity instead of the splash screen activity.
