### ISSUE TITLE
I can't change the default logo by using setLogoDrawableResourceId() method and also backPress does not work

### ISSUE THREAD

**Issue by Anichur25** [chat-sdk/chat-sdk-android#714]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
Please follow the issue template and also give an example of your Chat SDK initialisation code.

**Comment by Anichur25** [comment]
> Please follow the issue template and also give an example of your Chat SDK initialisation code.

  ChatSDK.config().setLogoDrawableResourceID(R.drawable.logo);
   ChatSDK.ui().startSplashScreenActivity(getContext());

**Comment by MuhammadSulaiman001** [comment]
```
ChatSDK.builder()
.setLogoDrawableResourceID(R.drawable.my_app_logo) // add this here
.build()
```
