### ISSUE TITLE
Please help me, i can't change the default logo of chat sdk.

### ISSUE THREAD

**Issue by Anichur25** [chat-sdk/chat-sdk-android#716]
This is code given in the below to change the default logo:

Config config = ChatSDK.ui().config();
config.setLogoDrawableResourceId(R.drawable.logo);
ChatSDK.ui().startSplashScreenActivity(getContext());

**Comment by MuhammadSulaiman001** [comment]
Here is an [example ]( https://github.com/chat-sdk/chat-sdk-android/blob/master/chat-sdk-demo/src/main/java/sdk/chat/demo/examples/AddFirebaseModules.java) of what you are looking for... use `.setLogoDrawableResourceID(R.drawable.my_app_logo)`
