### ISSUE TITLE
two chat threads are created

### ISSUE THREAD

**Issue by Lavii7** [chat-sdk/chat-sdk-android#72]
noticed that for one message sent to a user creates two threads, meaning let's say there are two people, Chatcat 1 and Chitchat 2: 
Step one: Chitchat 1 sends a message to Chatcat 2 saying hi
Step two: chitchat 2 sees message from chitchat1 but there are two threads on both sections of the users for the same message.

**Comment by bensmiley** [comment]
Do you think you could post the solution to this issue to help future users?
