### ISSUE TITLE
XMPPUploadHandler for sending images using XMPP - Enhancement

### ISSUE THREAD

**Issue by andreamendoza000** [chat-sdk/chat-sdk-android#721]
Hi, I would like to ask if you have a paid version for sending image message using XMPP server. Basically, If you have a XMPPUploadHandler just like the example of FirebaseUploadHandler. Thank you

**Comment by bensmiley** [comment]
Hi @andreamendoza000 we do have an XMPP file upload module for iOS but currently not for Android. If you needed this it would be a custom development and would cost in the order of $200.
