### ISSUE TITLE
Not able to build project

### ISSUE THREAD

**Issue by hardikJoshi123** [chat-sdk/chat-sdk-android#724]
A problem occurred configuring root project 'chat-sdk-android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find any matches for com.jfrog.bintray.gradle:gradle-bintray-plugin:1.+ as no versions of com.jfrog.bintray.gradle:gradle-bintray-plugin are available.

![Screenshot 2021-12-09 at 2 45 27 PM](https://user-images.githubusercontent.com/2733493/145367932-fad01093-b258-4f67-b1fd-3c8d5a9e9452.png)

**Comment by bensmiley** [comment]
Can you update to the latest commit and try again?
