### ISSUE TITLE
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.trackofield.tracker/sdk.chat.ui.activities.PostRegistrationActivity}: android.view.InflateException: Binary XML file line #22 in com.trackofield.tracker:layout/activity_post_registration: Binary XML file line #22 in com.trackofield.tracker:layout/activity_post_registration: Error inflating class

### ISSUE THREAD

**Issue by niranjan2496** [chat-sdk/chat-sdk-android#729]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by bensmiley** [comment]
Please follow the issue template.
