### ISSUE TITLE
Remove logo in ActionBar

### ISSUE THREAD

**Issue by afifnorazmi** [chat-sdk/chat-sdk-android#73]
Hi everyone,
I want to remove the logo in the action bar but failed to locate the source code.
How can it be removed?

![image](https://cloud.githubusercontent.com/assets/27624745/25071289/52f2156e-22b3-11e7-8513-43a9b066ac23.png)

**Comment by matheuaviczki** [comment]
Go to the fragments or activity and set this attributes

    -getActionBar().setHomeButtonEnabled(false);
    -getActionBar().setDisplayShowHomeEnabled(false);

Some classes have a method to custom action bar for example:
initActionBar()
{
ActionBar ab = getActionBar();
...
//then you can add your custom ab.setDisplayShowHomeEnabled(false);.....
}

**Comment by afifnorazmi** [comment]
Thanks a lot @matheuaviczki, it works!
