### ISSUE TITLE
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.trackofield.tracker/sdk.chat.ui.activities.ChatActivityWrapper}: java.lang.NullPointerException: Attempt to invoke virtual method 'void sdk.chat.ui.views.ChatView.setDelegate(sdk.chat.ui.views.ChatView$Delegate)' on a null object reference

### ISSUE THREAD

**Issue by niranjan2496** [chat-sdk/chat-sdk-android#730]
1. **Is the bug present in the demo Chat SDK project?**

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**

4. **Steps taken to reproduce the problem:**

5. **Expected result:**

6. **Actual result:**

7. **Comments:**

**Comment by niranjan2496** [comment]
plz help

**Comment by bensmiley** [comment]
Please follow the issue template. ALSO, don't put the issue details in the title.
