### ISSUE TITLE
Problem using Backendless 4.0

### ISSUE THREAD

**Issue by afifnorazmi** [chat-sdk/chat-sdk-android#74]
Hi everyone,

I've problem registering device using Backendless 4.0. But there is no problem at all when using Backendless 3.x.

I tried to change the dependency library to 4.0.0-beta1, but I will get a few error in import.

Are we bound to Backendless 3.x? If so, hope you can add a note regarding this matter in the documentation. It is useful for beginners like me.

**Comment by bensmiley** [comment]
What was your reason for upgrading to Backendless 4.0? I'd recommend not upgrading while their SDK is in beta. Once the library is stable, we will look into making the upgrade.

**Comment by afifnorazmi** [comment]
I just created the Backendless account and it automatically use Backendless 4.0. I've no knowledge about it before so it took me a whole day to figure out that I'm using different version.

**Comment by akrezic1** [comment]
It would be a good idea to write it down in README to switch to v3 of Backendless.. I've just spent a lot of time figuring out what was wrong.

**Comment by bensmiley** [comment]
I've added this to the documentation.
