### ISSUE TITLE
 Image Picker is not working in Andorid 13

### ISSUE THREAD

**Issue by AshwinN796** [chat-sdk/chat-sdk-android#740]
1. **Is the bug present in the demo Chat SDK project?**
Demo version is targeted to SDK version 31. And our app is targeted to SDK version 33
No, we have integrated latest Chat SDK version in our application.

2. **What modifications have you made to the Chat SDK?**

3. **Android Version:**
OS version :13 
Targeted SDK version: 33

4. **Steps taken to reproduce the problem:**
Go to Chat Screen
Press attach media icon
Select action 'Photo'

5. **Expected result:**
Gallery picker should be open

6. **Actual result:**
It return error "Permission must be enabled to access all the chat feature"

7. **Comments:**
Image picker is working with android version lower than 13.

**Comment by NobilityDeviant** [comment]
This is most likely because of requested permissions.
It is generally supposed to only request READ_EXTERNAL_STORAGE
but i would imagine it's requesting WRITE_EXTERNAL_STORAGE as well.
we should only request write with android 9 and below.
Trust me I had this bug in my app before.
