### ISSUE TITLE
Android app crash

### ISSUE THREAD

**Issue by ronaldo-triibo** [chat-sdk/chat-sdk-android#744]
1. **Is the bug present in the demo Chat SDK project?**
Not sure, as it cannot access the chat activity.

2. **What modifications have you made to the Chat SDK?**
None.

3. **Android Version:**
13

4. **Steps taken to reproduce the problem:**
Add ChatSDK to Android project and try to use it

5. **Expected result:**
No crashes

6. **Actual result:**
App crashes when opening chat activity

7. **Comments:**
Logcat shows:
     Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
        at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:402)
        at sdk.chat.ui.activities.BaseActivity.onCreate(Unknown Source:26)
        at sdk.chat.ui.activities.ChatActivity.onCreate(Unknown Source:0)

[logcat.txt](https://github.com/chat-sdk/chat-sdk-android/files/11479027/logcat.txt)

**Comment by bensmiley** [comment]
Can you test the latest version and tell me if this is still a problem?

**Comment by ronaldo-triibo** [comment]
Hi, thanks for your reply!
I've tried with version 5.4.6 (which is the latest I could use due to other project dependencies) and the issue still happens.

**Comment by bensmiley** [comment]
Unfortunately I can’t fix old versions. Because this issue has probably been fixed already in the latest version. So the options are to upgrade or take some priority support time to get me to fix the issue and make a new release.

**Comment by ronaldo-triibo** [comment]
Hello, Ben! Unfortunately it was may mistake: after I updated my project and its dependencies so I could be able to use the 5.5.1 version of chatSDK for Android, I found out that the issue still happens:

java.lang.RuntimeException: Unable to start activity ComponentInfo{***.MyCustomChatActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content

And the issue seems to be on BaseActivity.onCreate.

**Comment by ronaldo-triibo** [comment]
I've found out that the problem was actually in the androidx.appcompat dependency. I had to upgrade my app to the following settings:
- ChatSDK from 5.2.6 to 5.6.7
- JavaVersion from VERSION_1_8 to VERSION_11
- androidx.appcompat:appcompat from 1.3.1 to 1.5.1
