### ISSUE TITLE
Error when compiling when updating the android studio to the giraffe version

### ISSUE THREAD

**Issue by SalvaFemsa** [chat-sdk/chat-sdk-android#748]
When I updated my android studio I had to update the gradle version to version 7.2 and the library started sending me these errors:

> Could not resolve all files for configuration ':app:wii2DebugRuntimeClasspath'.
   > Could not resolve sdk.chat:firebase-app:5.3.11.
     Required by:
         project :app
      > Could not resolve sdk.chat:firebase-app:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android/sdk/chat/firebase-app/5.3.11/firebase-app-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:firebase-app:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chatkit/sdk/chat/firebase-app/5.3.11/firebase-app-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:firebase-app:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/matisse/sdk/chat/firebase-app/5.3.11/firebase-app-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
   > Could not resolve sdk.chat:mod-profile-pictures:5.3.11.
     Required by:
         project :app
      > Could not resolve sdk.chat:mod-profile-pictures:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android/sdk/chat/mod-profile-pictures/5.3.11/mod-profile-pictures-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:mod-profile-pictures:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chatkit/sdk/chat/mod-profile-pictures/5.3.11/mod-profile-pictures-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:mod-profile-pictures:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/matisse/sdk/chat/mod-profile-pictures/5.3.11/mod-profile-pictures-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
   > Could not resolve sdk.chat:pro-firebase-last-online:5.3.11.
     Required by:
         project :app
      > Could not resolve sdk.chat:pro-firebase-last-online:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android/sdk/chat/pro-firebase-last-online/5.3.11/pro-firebase-last-online-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:pro-firebase-last-online:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chatkit/sdk/chat/pro-firebase-last-online/5.3.11/pro-firebase-last-online-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:pro-firebase-last-online:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/matisse/sdk/chat/pro-firebase-last-online/5.3.11/pro-firebase-last-online-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
   > Could not resolve sdk.chat:pro-firebase-typing-indicator:5.3.11.
     Required by:
         project :app
      > Could not resolve sdk.chat:pro-firebase-typing-indicator:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android/sdk/chat/pro-firebase-typing-indicator/5.3.11/pro-firebase-typing-indicator-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:pro-firebase-typing-indicator:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chatkit/sdk/chat/pro-firebase-typing-indicator/5.3.11/pro-firebase-typing-indicator-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:pro-firebase-typing-indicator:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/matisse/sdk/chat/pro-firebase-typing-indicator/5.3.11/pro-firebase-typing-indicator-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
   > Could not resolve sdk.chat:pro-firebase-read-receipts:5.3.11.
     Required by:
         project :app
      > Could not resolve sdk.chat:pro-firebase-read-receipts:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android/sdk/chat/pro-firebase-read-receipts/5.3.11/pro-firebase-read-receipts-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:pro-firebase-read-receipts:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/chatkit/sdk/chat/pro-firebase-read-receipts/5.3.11/pro-firebase-read-receipts-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict
      > Could not resolve sdk.chat:pro-firebase-read-receipts:5.3.11.
         > Could not get resource 'https://chatsdk.jfrog.io/artifactory/release/matisse/sdk/chat/pro-firebase-read-receipts/5.3.11/pro-firebase-read-receipts-5.3.11.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict

Can somebody help me?

**Comment by bensmiley** [comment]
Check the latest instructions: 
https://chat-sdk.gitbook.io/android/setup/add-chat-sdk-to-your-project
Bintray shut down and the library has been moved to Maven central.
