### ISSUE TITLE
the host of libraries return 409  jfrog 

### ISSUE THREAD

**Issue by ahmad-moblers** [chat-sdk/chat-sdk-android#749]
maven { url "https://chatsdk.jfrog.io/artifactory/release/chat-sdk-android" }
        maven { url "https://chatsdk.jfrog.io/artifactory/release/chatkit" }
        maven { url "https://chatsdk.jfrog.io/artifactory/release/matisse" }
        
   is there any alternative that we can use?

**Comment by bensmiley** [comment]
https://chat-sdk.gitbook.io/android/setup/add-chat-sdk-to-your-project
