### ISSUE TITLE
Imges are not uploading -Chat Sdk

### ISSUE THREAD

**Issue by KavyaHarisha** [chat-sdk/chat-sdk-android#75]
Hi,
This is Kavya, i integrated Chat SDK as module in my app ,but when i try to upload the image, it's not uploading and again it's not showing any error messages to me.
Could you please help how to resolve this problem.
Thanking you.

**Comment by simonsmiley64** [comment]
Hi @KavyaHarisha,

The best way for us to troubleshoot this is to get a bit of additional information. I assume you have successfully added the Chat SDK to your project and configured it to your own Firebase account. 

When you log into your Firebase account you can click your project and then database on the left hand menu. You should then be able to find the thread you are trying to send messages in:

<img width="550" alt="screen shot 2017-04-21 at 09 25 42" src="https://cloud.githubusercontent.com/assets/8721425/25256508/8f11f18a-2674-11e7-94a1-2d4f104272b1.png">

This will update live as you send messages so you can see if the messages are getting through. 

If you can test this out with the app and database in front of you we can see if the app is failing to connect, whether the image is is not uploading correctly or if the image is not being downloaded. 

It would also be worth downloading the base version of the app from Github and trying to send image messages. This will let us know whether it is a problem with the SDK or if there is a configuration problem with your system,

Simon

**Comment by Lavii7** [comment]
yes it was firebase configuration, thanks you can close this

**Comment by bensmiley** [comment]
Would it be possible for you to post what was wrong with your configuration to help future users who may see the same issue?

**Comment by KavyaHarisha** [comment]
Hello,
Great greetings,
Thank you for your help. And sorry my problem was solved , i changed
firebase version according to ChatSdk firebase plugins.
Thank you.
