### ISSUE TITLE
Multiple issues and can not login to the account

### ISSUE THREAD

**Issue by ajutamama** [chat-sdk/chat-sdk-android#751]
Hi, we have some  issues:

1.  login site account errors out with this:

There has been a critical error on this website.
[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)
Tried on 3 different computers with  windows 10 and 11 with chrome and edge and incognito mode

2. sent email for payed support, no answer
Send email in september  2023 to this address [team@sdk.chat] (mailto:team@sdk.chat)

3. android app in google play not updated since 2020

4. can we still trust of this project being maintained?

Some feedback will be helpful, thanks!

**Comment by bensmiley** [comment]
@ajutamama it's possible your email went through to junk - as far as I know, I never received it. If you are still looking for help you could resend it or message me on [Discord](https://discord.gg/abT5BM4). 

If you check the Github commit history, you will see that this project was updated 2 months ago. I don't get paid to maintain this project and I do it in my own time so often extras like the website and Play Store app are left as a second priority. I prioritise fixing bugs and making sure the library keeps working on new versions of Android. 

I've been maintaining this project for the last 7 years and intend to continue. However, as with any open source project, I'm not being paid to maintain it so there are no guarantees ¯\_(ツ)_/¯.
