### ISSUE TITLE
Sync and build are failed

### ISSUE THREAD

**Issue by AKKaung** [chat-sdk/chat-sdk-android#753]
1. **Is the bug present in the demo Chat SDK project?**
    No

2. **What modifications have you made to the Chat SDK?**
    AudioChat, Customize Chat UI

3. **Android Version:**
    6 to 13

4. **Steps taken to reproduce the problem:**
    Gradle Sync, Build

5. **Expected result:**
    Successful Gradle Sync, Build, and run

6. **Actual result:**
    Sync success but occur - Failed to resolve: sdk.chat:android-audio-recorder:1.0.0, and Build failed

7. **Comments:**
    Sync Output:
    Failed to resolve: sdk.chat:android-audio-recorder:1.0.0
    Show in Project Structure dialog
    Show Details
    Affected Modules: app, chat-sdk-core-ui, chat-sdk-firebase-push, chat-sdk-mod-message-location, chat-sdk-mod-ui-extras, 
    chat-sdk-pro-message-audio
    
[Sync_logcat.txt](https://github.com/chat-sdk/chat-sdk-android/files/14218627/Sync_logcat.txt)

    Build Output: 
    Could not HEAD 'https://landing.jfrog.com/reactivate-server/chatsdk'. Received status code 409 from server: Conflict

[Build_logcat.txt](https://github.com/chat-sdk/chat-sdk-android/files/14218638/Build_logcat.txt)

**Comment by bensmiley** [comment]
It looks like you haven't updated the dependencies to get them from Maven. There are instructions here: https://chat-sdk.gitbook.io/android/getting-started/chat-sdk-quickstart
