### ISSUE TITLE
Error in Creating network adapter @ documentation  

### ISSUE THREAD

**Issue by habeebrahmanpt** [chat-sdk/chat-sdk-android#8]
BFirebaseNetworkAdapter adapter = new     BFirebaseNetworkAdapter(getApplicationContext()); // Create new network adapter  is getting error 
 

        BChatcatNetworkAdapter adapter = new BChatcatNetworkAdapter(getApplicationContext());
 // Create new network adapter

**Comment by kykrueger** [comment]
Hello,

Just wondering what the problem is that you are trying to address? Is it a request to better define the difference between the Firebase and Chatcat network adapters? 

-- Kyle

**Comment by kykrueger** [comment]
Hello,

If you have not had any luck with initializing the SDK's network adapter, I reccomend you look at how we launch the demo app. Particularly these lines

```
        // Android chat SDK init!
        ChatSDKUiHelper.initDefault();
        BNetworkManager.init(getApplicationContext());
        // Adapter init.
        BChatcatNetworkAdapter adapter = new BChatcatNetworkAdapter(getApplicationContext());
        BNetworkManager.sharedManager().setNetworkAdapter(adapter);
```

**Comment by simonsmiley64** [comment]
We have now updated some of our Chat SDK Android documentation. Checkout the wiki page [here](https://github.com/chat-sdk/chat-sdk-android/wiki) and then read the [Adding Chat SDK to your custom project](https://github.com/chat-sdk/chat-sdk-android/wiki/Chat-SDK-Android:-Adding-Chat-SDK-to-your-existing-project) tutorial. This includes a video showing you which code you need to add and where exactly to add it.

Let us know if you continue to have issues
