### ISSUE TITLE
Add Own Group Name

### ISSUE THREAD

**Issue by mandeepworld** [chat-sdk/chat-sdk-android#80]
There is an issue to create Private Group by own name. Kindly add option to create private group name. Maximum user will chat on private group by identify group name.

**Comment by simonsmiley64** [comment]
Hi @mandeepworld,

Currently you can name a private group if there are multiple users in the group. This should be easy to modify in your code:

If you navigate to BFriendsListViewController.m you'll see the following code:

```
-(void) setGroupNameHidden: (BOOL) hidden duration: (float) duration {
    [self.view keepAnimatedWithDuration: duration layout:^{
        groupNameView.keepTopInset.equal = hidden ? -46 : 0;
    }];
    if (!hidden) {
        self.navigationItem.rightBarButtonItem.enabled = groupNameTextField.text.length;
    }
} 
```
This code sets whether the name field is hidden or not. Currently we set it hidden when we only have one user selected:

```
[self setGroupNameHidden:_selectedContacts.count < 2 || _contactsToExclude.count > 0 duration:0.4];
```

I would recommend subclassing the view and then modifying the viewDidLoad and selectUser functions to set the nameField as visible at all times. 

Simon

**Comment by bensmiley** [comment]
Added in v4.0.
