### ISSUE TITLE
Random users are added to a thread?

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-android#81]
Hello again, I have another issue! So here it is, for some reason, if you click a contact and create a new thread but back out of it again without any messages being sent and then you go to click on another contact straight after it will sometimes add either the last contact that was pressed or just some random one!

Sometimes though it'll do the same if you delete a conversation and then the contact straight after but THEN click another contact it will do the same!

I'm still using the stock methods for the selecting, the only thing i have added was a full thread delete method, which of course removes the whole thread from the firebase and local database, the only bit it won't remove is the firebase node in the other persons account so the logged in users will be removed but not the other, if that makes any sense!

So yeah any help would be appreciated as always

Thanks
Ryan

**Comment by RyanElliott94** [comment]
Quick update. I had a look at the firebase database when it added the random user but it actually turns out that the random user isn't actually apart of the thread but for some reasons shows the name of that random user at the top of the chat activity!

**Comment by bensmiley** [comment]
This should be fixed in v4.0.
