### ISSUE TITLE
Block user

### ISSUE THREAD

**Issue by sonshark** [chat-sdk/chat-sdk-android#86]
Hi everyone,

I have a problem. I don't want to receive a message from a user.  Could you please tell me how can I block this user?

**Comment by simonsmiley64** [comment]
Hi @sonshark,

This functionality isn't currently available on the Chat SDK. We have it on our TODO list but can't give you an accurate indication of when we will have time to code, test and release it. 

There are two options available to you:

1. Code it yourself
This functionality uses core concepts of the Chat SDK so it would definitely be possible to code yourself. We would be able to give you an explanation of the structure your code should follow - you would be adding a list of entityIDs to a new field on the user object, the app would then check these contacts to see if user messages were allowed through.

If this is the route you want to proceed down we can give you a more detail explanation of how to fit the code together.

2. We can set up a subproject to code it for you
We would be able to prioritise this functionality but would need to allocate some paid time towards it. In the past we have reduced the cost of work if we can add the functionality to the Chat SDK after completion (we usually do this after a few months to ensure your app has the unique code first). Let us know if this is something you might be interested in.

Simon

**Comment by bensmiley** [comment]
This is now supported by the blocking module: https://chatsdk.co/downloads/user-blocking-for-android/
