### ISSUE TITLE
Contacts are not visible

### ISSUE THREAD

**Issue by smartmenia1** [chat-sdk/chat-sdk-android#90]
Hello,

good Job guys :) . I have configured firebase for the app. Login with different users is possible and also sending data files (location, pictures, messages). My doubt:  Why are the app users not visible in my contacts or vice versa and i can't add them. Can anyone help me? Or do i have to make some changes on my databse rules on firebase for user visibility on the app?.
best regards

**Comment by bensmiley** [comment]
Have you searched for users and then added them to your contacts? You need to click the + button on the contacts screen and search by name, email or phone number. Then select the other user and click the add button. Then they should be visible.

**Comment by smartmenia1** [comment]
Thanks !!! That works  !!! 
One more time great JOB :)
I will try to implement for the future something showing a selecion of contacts from my handy contact list of users who are using the app (e.g. like whatsapp). 
I will close the issue and give a feedback if it works. 
Thank you

**Comment by jay2342** [comment]
bensmiley i cant see my contact list in the app and when i search by name or email or number no result found error coming what should i do now
