### ISSUE TITLE
I want to show full contact list instead of searching for contacts via name,phone number.

### ISSUE THREAD

**Issue by marmik57** [chat-sdk/chat-sdk-android#94]
I want to show full contact list instead of searching for contacts via name,phone number. Is it possible to do like that. And if user tap click on that button chat should be happen. Can you help me how to do that?

**Comment by RyanElliott94** [comment]
Why not have a look at how public groups are displayed as there isn't (as far as i know) a filter and it shows every single public thread. You might be able to change the path and show contacts instead

**Comment by marmik57** [comment]
Thanks for your reply. I will check that.
