### ISSUE TITLE
Google Sign In Log in integration

### ISSUE THREAD

**Issue by zkharris** [chat-sdk/chat-sdk-android#95]
I have google sign in in my app already. When I add the chat sdk I want to skip the log in screen and let users chat with their google accounts, is this possible and how can I do this?

**Comment by simonsmiley64** [comment]
Hi @zkharris,

You will need to link your Google Sign in flow with that of the Chat SDK. 

You can see how the code should go [here](https://firebase.google.com/docs/auth/android/google-signin) - looking at google sign in on Android for Firebase. I would also recommend looking at how we currently login with the Chat SDK and then linking that in with your current login flow.

Simon

**Comment by rohitbhoite** [comment]
Hi @simonsmiley64,

I am looking for a similar approach where I can use the usernames to chat with different people?To implement push notification can I use my own server instead of backendless.?

**Comment by kairosart** [comment]
Has anyone done a module to Sign in with Google?
It'll be interesting to make module similar to Facebook one but using Google Auth code.

**Comment by bensmiley** [comment]
Added in v4.0.
